### ISSUE TITLE
Is there a year picker?

### ISSUE THREAD

**Issue by gustojs** [nathanreyes/v-calendar#1]
I'm browsing through the examples and API but can't find it. Is there a way to use the `v-calendar` to quickly set a particular year? For example, to set the date of my birthday without clicking the "previous month" 50 times and without using the keyboard to enter the date in the input field.

**Comment by HapLifeMan** [comment]
The very last important feature to implement before I use v-calendar on my websites 👍🏻

**Comment by nathanreyes** [comment]
Thanks for the feedback. Currently, the only way to accomplish this is use utilize the header title slot to insert your own controls, and call `props.move(month, year)` within the slot to perform the navigation.
I would still like to document this strategy as I think it would be helpful, but I agree there should a built-in way to handle what you are trying to do. I'll fit it in the next update.
