### ISSUE TITLE
Option for stop hiding date picker on scroll

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#100]
I think hiding date picker on scroll is indeed the default behavior, but in my case here it becomes a very bad ux. Please, see this short video:

https://www.useloom.com/share/8ed3bca9ce6d49b5b4158d8d5e0478c1

Is there a way to set an option for this behavior @nathanreyes?

**Comment by nathanreyes** [comment]
That should not happen. Is your `popover-visibility` set to anything other than the default (`"hover"`)?

**Comment by luiztsmelo** [comment]
It set to `'focus'`

**Comment by EricMcRay** [comment]
I am using date-picker with focus option, I dont have any problem on scroll.

**Comment by luiztsmelo** [comment]
Yeah, seems ok now in v0.9.6.
