### ISSUE TITLE
locale documentation

### ISSUE THREAD

**Issue by shrpne** [nathanreyes/v-calendar#101]
Looks like `locale` options is not documented. I don't see it in the [props list](https://docs.vcalendar.io/api.html#calendar-props)

**Comment by rodolfobubb** [comment]
Same issue, how can i change locale?

**Comment by nathanreyes** [comment]
Locale can be set up one of two ways.
1. Automatically: Let the plugin detect the user's locale (uses `Intl.DateTimeFormat().resolvedOptions().locale`)
2. Manually pass in a locale string as an option:
```javascript
import Vue from 'vue';
import VCalendar from 'v-calendar';

Vue.use(VCalendar, {
  locale: 'es' // Spanish
});
```
> Note: If you use the manual approach, that locale will get forced for all users internationally.

As of now, the reason it is not documented is because I see little benefit to forcing all users to use one specific locale.

The only downside to this approach is if you need a locale that is not supported out of the box. See the [list](https://github.com/nathanreyes/v-calendar/blob/master/src/utils/locales.js) for reference. If that is the case, I would need to add support for passing in a custom locale.

**Comment by niksib** [comment]
@nathanreyes How can I change locale if I use the calendar from CDN?

**Comment by nathanreyes** [comment]
Currently, there is no way to force a locale via CDN. However, it still does try and detect the locale automatically. Is there a specific locale you had in mind that needed to be supported?

**Comment by niksib** [comment]
@nathanreyes I need ukrainian, if you can't add this language, how can i customize calendar?.

**Comment by EricMcRay** [comment]
@niksib you can do a little hack like below. You can pass any options and reinstall any plugin which not available on global scope.

```
Vue._installedPlugins.find(function(plugin){
  if(plugin.hasOwnProperty('Calendar')){
     plugin.install(Vue, { locale: 'uk'})
  }
});
```

**Comment by niksib** [comment]
@EricMcRay Thanks, but the calendar doesn't support the Ukrainian language.

**Comment by nathanreyes** [comment]
@niksib What version of the plugin are you currently using?

**Comment by niksib** [comment]
@nathanreyes Sorry it's my fail, I had to put this: weekdays: [1, 7]
1 - Saturday, 7 - Sunday

**Comment by nathanreyes** [comment]
@niksib Yes, I was about to post that :)

**Comment by nathanreyes** [comment]
To resolve this issue, a bug will get fixed that will support *all* locales supported by `Intl.DateTimeFormat` (not just those that aren't cross-checked with the plugin). @niksib This should fix Ukrainian locale detection.

Also, the docs site will more elaborately explain how locales are resolved.

**Comment by nathanreyes** [comment]
Resolved by 19b8d6faba34fb321a3cfcad226fb863805ba3c5.

**Comment by achwilko** [comment]
I really appreciate you work on v-calendar but I have a silly question - how can I update locales during application lifetime?

I'm setting locales during installation, like below:
```
import Vue from 'vue';
import VCalendar from 'v-calendar';

Vue.use(VCalendar, {
  locale: 'pl-PL'
});
```
..and wondering how can I change above locale in component's method etc. Is there any workaround?

**Comment by lgomes2m** [comment]
I have the same problem as @achwilko 
I need to change language on the run.
Is there a solution?

Thanks!

**Comment by hisenbergguj** [comment]
@lgomes2m having the same trouble, did you find any solution for that?

**Comment by lgomes2m** [comment]
@hisenbergguj 
Yes, I did a workaround.

At template I put a key at v-date-picker:

`<v-date-picker
        mode="single"
        v-model="selectedValue"
        :theme-styles='themeStyles'
        :is-inline="true"
        :available-dates="availableDates"
        :min-date="new Date()"
        :max-date="$moment().add(1, 'M').toDate()"
        v-on:dayclick="daySelected"
        @update:page="monthChange"
        :key="currentLanguage" 
      >
      </v-date-picker>`

And currentLanguage is a computed var:

`computed: {
    currentLanguage() {
      setupCalendar({
        locale: this.$store.getters['current_language'] == "br" ? "pt" : "en"
      })
      return this.$store.getters['current_language']
    }
  }`

When you call setupCalendar() it didn't re render vcalendar but it actually change its locale, I am using currentLanguage as a key because when it changes it forces de component to render again and now it will use the correct language.

@Chemahin gave another solution [here](https://github.com/nathanreyes/v-calendar/issues/161#issuecomment-423090226) but I didn't test it yet.

I hope it helps you.

**Comment by hisenbergguj** [comment]
@lgomes2m I have tried your solution but it gives me "setupCalendar" is not defined".
I have already import it like this : import VCalendar, {setupCalendar} from 'v-calendar';

do you have any idea, what am I doing wrong here?

**Comment by lgomes2m** [comment]
@hisenbergguj 

Sorry.... I don't know why...
I am importing like this:
`import { setupCalendar, Calendar } from 'v-calendar'`

And in main.js:

`
import VCalendar from 'v-calendar'

Vue.use(VCalendar)
`

**Comment by Chemahin** [comment]
try to do this:

пт, 21 сент. 2018 г. в 15:41, lgomes2m <notifications@github.com>:

**Comment by Chemahin** [comment]
try to do this:
in main.js

import Vue from 'vue';import VCalendar from 'v-calendar';import
'v-calendar/lib/v-calendar.min.css';

Vue.use(VCalendar, {
firstDayOfWeek: 1,
locale:'nl-NL',
datePickerTintColor: "#00c7d6",
datePickerShowDayPopover: false,
weekdays: 'WW',
});

in your component :

<v-calendar


  </v-calendar>


пт, 21 сент. 2018 г. в 15:41, lgomes2m <notifications@github.com>:

**Comment by nr007** [comment]
Hey @nathanreyes, thank you very much for your work on this amazing calendar! I have one request... Could you add support for Slovenian locale (sl-SI)?  It has the same date format as Croation. Thank you!

**Comment by nxic** [comment]
> Locale can be set up one of two ways.
> 
> 1. Automatically: Let the plugin detect the user's locale (uses `Intl.DateTimeFormat().resolvedOptions().locale`)
> 2. Manually pass in a locale string as an option:
> 
> ```js
> import Vue from 'vue';
> import VCalendar from 'v-calendar';
> 
> Vue.use(VCalendar, {
>   locale: 'es' // Spanish
> });
> ```
> 
> > Note: If you use the manual approach, that locale will get forced for all users internationally.
> 
> As of now, the reason it is not documented is because I see little benefit to forcing all users to use one specific locale.
> 
> The only downside to this approach is if you need a locale that is not supported out of the box. See the [list](https://github.com/nathanreyes/v-calendar/blob/master/src/utils/locales.js) for reference. If that is the case, I would need to add support for passing in a custom locale object.

I want to set custom locale all my date-pickers across my project but it isn't working. It's kinda only available if I set locale attribute on all my date-pickers one by one. How could I set locale default in Vue.use or something.

```js
    Vue.use(VCalendar, {
      componentPrefix: 'v',
      locale: 'mn-MN',
      locales: {
        'mn-MN': {
          firstDayOfWeek: 2,
          masks: {
            L: "YYYY-MM-DD",
          }
        }
      }
    });
```

but it won't make any changes

```html
<v-date-picker v-model="filters.from" :input-props="{ placeholder: $t('startDate') }" locale="mn-MN" class="form-control date"/>
```
if I set my locale on every use I could use my declared locale without problem show as like above.

**Comment by titosobabas** [comment]
I'm from Mexico, so I needed to display the weekdays in spanish, so I used this code:

```
<v-calendar
    locale="es"
></v-calendar>
```

But as this translate to spanish weekday names in lowercase I had to add a css rule (this is up to you) like this:
```

<style>
.vc-weekday {
    text-transform: capitalize;
}
</style>
```

Cheers

**Comment by AlmasF** [comment]
Hello, can you please add kk-KZ locale [nathanreyes](https://github.com/nathanreyes)

**Comment by redhemd** [comment]
i second @AlmasF. can you add kk-KZ please
