### ISSUE TITLE
Is there a way to trigger a navigation popover?

### ISSUE THREAD

**Issue by existe-deja** [nathanreyes/v-calendar#1014]
Hi,

I'm trying to customize my calendar header but once I use the header-title scoped slot I loose th ability to trigger the popover default navigation. I can't found any methods or documentation about this. Do you have some clue on how to achieve this?

Thanks.

**Comment by existe-deja** [comment]
After digging and reading the code I found this workaround in `v-calendar@2.3.4`

```vue
<template>
  <v-calendar ref="calendar">
    <template #header="page">
        <button
          type="button"
          @click="toggleNavPopover($event, page)"
        >
          click me
        </button>
      </div>
    </template>
  </v-calendar>
</template>

<script>
export default {
  methods: {
    toggleNavPopover (evt, page) {
      document.dispatchEvent(new CustomEvent('toggle-popover', {
        detail: {
          id: this.$refs.calendar.sharedState.navPopoverId,
          data: { page },
          ref: evt.target
        }
      }))
    }
  }
}
</script>
```

**Comment by mreduar** [comment]
Any way to do this in vue 3 with v-calendar version 3? I tried it this way and it doesn't work
