### ISSUE TITLE
Bug prop "minDate". Expected Date, got Number.

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#102]
When I set:
```
<v-date-picker 
  :min-date='Date.now()'> // Or 'new Date().getTime()'
</v-date-picker>
```
I get this on console:

![bug](https://user-images.githubusercontent.com/11582056/37858707-6ef4caea-2ee7-11e8-9cd2-5b02a141516b.jpg)

Even setting indirectly this seems to happen.

**Comment by AfonsoGomes** [comment]
You seem to be trying to pass a Number to prop that is expecting an object of Date.

Both [Date.now()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/now) and new [Date().getTime()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTime) return the Number of milliseconds elapsed from a specific date.

The docs on the v-date-picker shows it is expecting to receive a Date object and not a Number, that can be provided by [new Date()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date)
```
<!--Set minimum date-->
<v-date-picker
  :min-date='new Date()'
  v-model='selectedDate'>
</v-date-picker>
```

**Comment by luiztsmelo** [comment]
Yea, I don't know why I wrote this. Thanks
