### ISSUE TITLE
2 components using the same name

### ISSUE THREAD

**Issue by santossoares** [nathanreyes/v-calendar#103]
Hi folks,
how can i import this component inside another component, just to use it locally, because when i import using the default options (globally) provided by the docs, the behavior is not what i want. I have another UI component that uses the same component name <v-date-picker>. So, i have 2 components with the same name and Vue is not using the <v-date-picker> provided by the v-calendar.

How can i solve this conflicts?

Thanks!

**Comment by nathanreyes** [comment]
Hi @santossoares 
I believe you wish use a different component prefix for `v-calendar` (like `vc` for `vc-calendar` and `vc-date-picker`). If so, when you use the plugin
```javascript
import Vue from 'vue';
import VCalendar from 'v-calendar';

Vue.use(VCalendar, {
  componentPrefix: 'v' // Enter your own prefix here, 'v' is the default
});
```

Is this what you are asking?

**Comment by santossoares** [comment]
Yes. That's it!
Thank You!
