### ISSUE TITLE
Interact with individual dates of a date-range object

### ISSUE THREAD

**Issue by 2Clutch** [nathanreyes/v-calendar#1034]
Not sure, if this should be a bug report or a feature request, but I'd like to know if it's possible to interact with individual dates within a specified date range.

My use revolve around availability submission. When a user selects a date range, I would like to offer them the option to apply different times with each date. The documentation mentions `select-attribute` & `drag-attribute` but neither seem to work as expected.

Per the documentation:

![image](https://user-images.githubusercontent.com/13703683/147136228-c8a57a88-34b0-4eb6-92ca-9cc6565c4714.png)

However, all I'm able to get from the date-range component, is the start-date & end-date. I believe that it should be possible to interact with the dates of a date-range object as long as said dates fall within the bounds of the range that has been defined (i.e. no earlier than `start-date` & no later than `end-date`)

If this is currently possible, I'd like to:
```
1. Know the best way to do it
2. Request the documentation be updated with answer to question above
```

If the behavior I'm requesting is not possible at this time, then I'd like this issue to be considered a feature request.

**Comment by nathanreyes** [comment]
Here are a few ways you can get all the dates between the start and end date.

### 1. Use built-in helper class

`DateInfo` is a date helper class that gets used internally so import it and use it to create a new `datesInRange` computed property. It would be an array of all dates from `start` to `end`.

It looks a little funny right now but I can refactor it a little to make it more intuitive if it works. 

```html
<v-date-picker v-model="range" is-range />
```

```js
import { DateInfo } from 'v-calendar';

export default {
  data() {
    return {
      range: null,
    };
  },
  computed: {
    datesInRange() {
      const result = [];
      if (!this.range) return result;
      return new DateInfo(this.range).datesInRange;
    },
  }
}
```

If it works I can release a new version that would work like this instead...

```js
  ...
  computed: {
    datesInRange() {
      const result = [];
      if (!this.range) return result;
      new DateInfo(this.range).iterateDatesInRange(({ date }) => {
        result.push(date);
      });
      return result;
    },
  }
  ...
}
```

or emit an event any time a new range is selected

```html
<v-date-picker v-model="range" is-range @dates-selected="onDatesSelected" />
```

```js
export default {
  ...
  methods: {
    onDatesSelected(dates) {
      console.log(dates); // ['2021-01-21', '2021-01-22', '2021-01-23'] <= Date objects
    }
  }
  ...
}
```

### 2. Use something like `date-fns` to compute the dates

```js
import addDays from 'date-fns/addDays';

export default {
  data() {
    return {
      range: null,
    };
  },
  computed: {
    datesInRange() {
      const result = [];
      if (!this.range) return result;
      let date = range.start;
      while (date <= range.end) {
        result.push(date);
        date = addDays(date, 1);
      }
      return result;
    },
  }
  ...
}
```

**Comment by vip9** [comment]
Will @dates-selected event be available in next (3.x.x) version?
