### ISSUE TITLE
Wrong dates

### ISSUE THREAD

**Issue by javialon26** [nathanreyes/v-calendar#104]
Hello, the plugin is generating wrong dates, you can see this in v-calendar home page (https://vcalendar.io/)

For example, today Monday 26, appears as Sunday 26.

This happens in a machine with Linux in chrome and in my cell phone with android and chrome. In iphone it is ok.

![screen](https://user-images.githubusercontent.com/8138654/37938415-1e808fe6-3134-11e8-9cf2-c2fa9f02495c.jpg)

**Comment by EricMcRay** [comment]
I have the same issue. Open PR for fix #111

**Comment by CristianaPereira** [comment]
Shouldn't it be fixed? it still happens to me.
