### ISSUE TITLE
Time Picker has 2 down arrow icons

### ISSUE THREAD

**Issue by sibi-ghl** [nathanreyes/v-calendar#1041]
![image](https://user-images.githubusercontent.com/67587425/148748834-688408b4-995e-4f62-8670-6dfe936b814f.png)

I'm using Vue 3 and the component appears a little weird here. Am I missing something here?
Thanks!

**Comment by sibi-ghl** [comment]
Fixed it with CSS as a stop-gap solution
`.vc-popover-content-wrapper .vc-container .vc-select select {
  width: 60px !important;
}

.vc-popover-content-wrapper .vc-container .vc-select-arrow {
  display: none !important;
}`

**Comment by nathanreyes** [comment]
Most likely this is from a Tailwind reset style that applies a background-image to all select elements. Both newest versions (`v2.4.0` and `v3.0.0-alpha.7`) have addressed this issue.
