### ISSUE TITLE
ISO mask leading to "DateTime is invalid" errors

### ISSUE THREAD

**Issue by catherineluse** [nathanreyes/v-calendar#1052]
I have a form where I want the v-calendar date picker to be initialized with an ISO and set the data in the same format it was initialized with.

<img width="896" alt="Screen Shot 2022-01-27 at 11 40 03 PM" src="https://user-images.githubusercontent.com/20599230/151499845-70ee01b1-25bb-465c-8082-c978a2548cb1.png">

The initial value is in this format:

```
2022-01-28T00:00:00.000-07:00
```

But once I select a value with the Date picker, the value changes to this format:

```
2022-01-25T00:00:00XXX
```

Other parts of my code need to initialize date objects from the ISO. But when I try to parse that format of ISO using Luxon  like this:

```
let res = new  DateTime.fromISO('2022-01-25T00:00:00XXX')
```

I get the result `Invalid Date`. Am I configuring the Date picker wrong? Is it possible to change the ISO into the first format?

My data is:

```
data(){
    return {
      modelConfig: {
        type: 'string',
        mask: 'iso',
      },
    }
  },
```

My component is:

```
<DatePicker
  v-model="startTime"
  mode="date"
  :modelConfig="modelConfig"
>
  <template v-slot="{ inputValue, inputEvents }">
    <input
      :value="inputValue"
      v-on="inputEvents"
    />
  </template>
</DatePicker>
```

My code is here https://github.com/catherineluse/gennit-vue/blob/master/src/components/forms/create-edit/event.vue#L470

Any help is much appreciated!

**Comment by nathanreyes** [comment]
Hi there. Did your code change since you linked this? It looks like a new date picker is being used ('vue3-date-time-picker'). Either way, v3.0.0-alpha.7 should have patched this up. Just a note when upgrading...importing the component style in now required. https://vcalendar.io/vue-3.html

**Comment by nathanreyes** [comment]
Also, the '2022-01-30T21:50:34.266Z' form should allow you to create a new date via `new Date('2022-01-30T21:50:34.266Z'), but you can also use your own format if you'd like the initial form you mentioned:
```js
modelConfig: {
  type: 'string',
  mask: 'YYYY-MM-DDTHH:mm:SSSZZZZ',
},
```
which would give you something like '2022-01-04T21:49:537-06:00'.
