### ISSUE TITLE
Change date-picker input element

### ISSUE THREAD

**Issue by MrOnlineCoder** [nathanreyes/v-calendar#106]
Hello. Currently, I am using Bootstrap 4 as my main CSS framework. I am using v-calendar for date picking and want to apply Bootstrap style to the date picker input. 

My template:
```
<v-date-picker v-model="filterRange" mode='range' show-caps></v-date-picker>
```

The problem is that input, used for showing date range does not have any classes or styles applied, so looks ugly comparing to other part of my page, where Bootstrap is actively used.

I tried this:
```
<v-date-picker class="form-control" v-model="filterRange" mode='range' show-caps></v-date-picker>
```

But didn't work as expected.

**Suggestion:**
- add a slot for custom input
- or add a prop to v-calendar, something like 'input-class' for setting input styles.

Sorry, if I missed something about it in documentation/readme. If so, I would appreciate your help if you will give a link to it.

Regards,
MrOnlineCoder

**Comment by nathanreyes** [comment]
You can style the input via `input-props` or provide your own default slot element.

[Details here.](https://docs.vcalendar.io/datepicker.html#customize-input-element)

**Comment by MrOnlineCoder** [comment]
That's what I need. Missed it. Thanks a lot.
