### ISSUE TITLE
show-popover="false" not working for me

### ISSUE THREAD

**Issue by freiguy1** [nathanreyes/v-calendar#107]
Hello there, 

I have a v-date-picker and i'm trying to disable the popover. Here is my code:

```xml
<v-date-picker
    mode='range'
    show-popover="false"
    v-model="modalCustomDateRange"
    :max-date="new Date()"
    is-inline
    show-caps></v-date-picker>
```

I've tried with and without a colon before show-popover. I've tried setting popover to null inside `drag-attributes`, and the default popover keeps showing.

![](https://i.imgur.com/VgkuaUO.png)

Please help!

**Comment by nathanreyes** [comment]
As of `v0.8.0` the prop was renamed to `show-day-popover` to avoid confusion with the entire calendar used as a popover for the input control.

**Comment by freiguy1** [comment]
Thanks!

**Comment by Hammster** [comment]
@nathanreyes just stumbled on this, the docs still list `show-popover` and not `show-day-popover`

**Comment by pranaykumar** [comment]
Also correct usage is **:**show-day-popover=false

**Comment by baranelitez** [comment]
> As of `v0.8.0` the prop was renamed to `show-day-popover` to avoid confusion with the entire calendar used as a popover for the input control.

Have you included this in the guide? I can only find this in the changelog. The guide or API documentation does not refer to this.
