### ISSUE TITLE
Popover positionFixed has no effect

### ISSUE THREAD

**Issue by huysal** [nathanreyes/v-calendar#1095]
Hi Guys,

my popup gets cut off by the parent element. I tried variations of positionFixed in the popover settings, without success.
I can replicate the behaviour in a sandbox.

My `v-date-picker` looks like this:

```vue
<v-date-picker
            :value="date"
            :popover="popoverOptions"
            datepicker-mode="date"
            @input="log($event)"
          >
            <template v-slot="{ inputValue, inputEvents }">
              <div>
                <input
                  type="text"
                  :value="inputValue"
                  v-on="inputEvents"
                  placeholder="placeholder"
                />
              </div>
            </template>
          </v-date-picker>
```

with `popoverOptions`

```js
popoverOptions() {
      return {
        positionFixed: this.positionFixed,
      };
    },
```

**Result Screenshot**
![image](https://user-images.githubusercontent.com/464444/157263489-cf4a89a4-3563-430d-9ec1-14a5e0be04f5.png)

**Versions:**
v-calendar 2.4.1
@popperjs/core": "^2.9.2"

**Link to Example**
[https://codesandbox.io/s/issue-232-forked-3q965f?file=/src/App.vue](https://codesandbox.io/s/issue-232-forked-3q965f?file=/src/App.vue)

**Comment by ThibaultNocchi** [comment]
I can reproduce this issue on the latest v3 alpha version

**Comment by huysal** [comment]
I was able to fix this issue, by moving the clip path in a separate div. the clipping occured because of the clip path. after moving it and putting the content to a sibling div i had no more issues. Hope this helps

**Comment by ThibaultNocchi** [comment]
What do you mean by "a clip path"? Do you have an example? :)
