### ISSUE TITLE
Define locale globally

### ISSUE THREAD

**Issue by cdmoro** [nathanreyes/v-calendar#11]
If I use the calendar in multiple pages I'm forced to define a locale in every instance (tag) of the calendar or the datepicker. It would be nice if the declaration _Vue.use(VCalendar)_ accepts an object (locale configuration) as a second argument: _Vue.use(VCalendar, config)_
Or even better, the locales are inside the package, so, all the users have to do is _Vue.use(VCalendar, { locale: 'es' })_ (in my case, because I speak spanish). BTW, if you choose the second solution, here you have the translation ready for use :stuck_out_tongue_winking_eye: 

month-labels: ["Enero","Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"]
weekday-labels: ["D", "L", "M", "X", "J", "V", "S"]
weekday-labels-variant: ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"]

**Comment by nathanreyes** [comment]
That is definitely on the list. The config should probably also have some other default settings like theme styles, for example.

**Comment by cdmoro** [comment]
Even even better, the calendar could detect the locale of the browser and select automatically the language to show.

**Comment by nathanreyes** [comment]
Locale should get auto detected, but you may also supply locale via the plugin options object, [among other things](https://github.com/nathanreyes/v-calendar/blob/master/src/utils/defaults.js).
```javascript
Vue.use(VCalendar, {
  locale: 'es'
})
```
Still working to get the documentation up to speed.

**Comment by cdmoro** [comment]
Exactly! I have only one question about it... what happens if I speak a language that are not supported? Can I put an Object with my translation?

**Comment by nathanreyes** [comment]
I suppose it could be modified to allow specifying custom locales not [currently supported](https://github.com/nathanreyes/v-calendar/blob/master/src/utils/locales.js), but ideally I think we would want to include as many as reasonably possible out of the box. What languages did you have in mind?

**Comment by cdmoro** [comment]
I just saying, with the spanish translation i'm happy :smiley:
