### ISSUE TITLE
[Bug] Default slot doesn't work with a custom input component

### ISSUE THREAD

**Issue by nkeyy0** [nathanreyes/v-calendar#1108]
**V-calendar version**: 2.4.1
**Vue version**: 2.6.11
**Browser**: Google Chrome v 99.0.4844.82

### Steps to reproduce 

1. You need to pass custom input to the default slot and use the variables from the scope (in my example I use b-form-input component from the [bootstrap-vue](https://bootstrap-vue.org/docs/components/form-input) library);
2.  Try to enter date manually;
3. An error will appear in the console.

### Reproduction Link or Source Code

https://codesandbox.io/s/funny-einstein-m6msui

### Expected behavior
Library should work with custom inputs, when we change date manually 

### Actual behavior
An error occurs. `TypeError: Cannot read properties of undefined (reading 'value')`

**Comment by nkeyy0** [comment]
Probably I found an error reason. You suggest that value generates by input evet always will be an object of the event, but in libraries for custom input mostly generate a value of this event(have a look at the picture). Could you fix this? 
How did I solve this issue? I passed a prop `:update-on-input="false"` to the date-picker and wrote custom event handlers on input.
![image](https://user-images.githubusercontent.com/44264841/159906956-f82d1adc-f51d-4030-8d15-9b43baa77327.png)

**Comment by bettysteger** [comment]
@nkeyy0 how did you fix this?

**Comment by bettysteger** [comment]
@nkeyy0 nevermind i fixed it by replacing `b-form-input` with input-tag
