### ISSUE TITLE
bug: ^3.0.0-alpha.8

### ISSUE THREAD

**Issue by kengketa** [nathanreyes/v-calendar#1120]
<img width="562" alt="Screen Shot 2565-03-31 at 22 36 12" src="https://user-images.githubusercontent.com/32511654/161094312-d8016d5d-67d1-4cfb-b09f-6dcce70e961e.png">

Anyone face the same problem?

**Comment by olsoncarsen** [comment]
As of v3.0.0-alpha.7, all installation methods require manual import of component styles. This is due to Vite build restrictions in libary mode.
```js
import 'v-calendar/dist/style.css';
```
https://vcalendar.io/vue-3.html

**Comment by nathanreyes** [comment]
Yes @olsoncarsen is correct about the new required import.

**Comment by DaveL17** [comment]
```
import 'v-calendar/dist/style.css';
```
 in the Vue file that renders the calendar worked great.
