### ISSUE TITLE
Disabled dates wrong

### ISSUE THREAD

**Issue by franrolando** [nathanreyes/v-calendar#1126]
As you can see the disabled dates is disabling one day different than the specified by prop:

![image](https://user-images.githubusercontent.com/42620002/163101633-a545f4ff-ff81-44bf-af9d-a9a32b281196.png)

Vue 3 -> v-calendar 3.0.0 alpha 8

**Comment by depressedpsychiatrist** [comment]
the same thing happens to my code. 14 - 18 disables 13 to 17.

**Comment by depressedpsychiatrist** [comment]
The same thing happened to me. 
This is because of the time zones. Just set the timezone to UTC.
```html
<Date-Picker
      is-range
      mode="date"
      :disabled-dates="{start: '2022-06-10', end: '2022-06-15'}"
      timezone="UTC"
></Date-Picker>
```

**Comment by franrolando** [comment]
Thanks man!
