### ISSUE TITLE
When I show the days of the next month, appears a 1 week more than expected

### ISSUE THREAD

**Issue by ericuss** [nathanreyes/v-calendar#1135]
Hi, 

first of all, thank you for the component. I'm not sure that I make a mistake, but when I show the calendar with prev and next month days I can see a 1 week more than expected:

![image](https://user-images.githubusercontent.com/4225477/165984842-3369634f-2aba-45e9-94d7-ae7a4b1adfb3.png)

I consider that the week from 4 to 10 of May shouldn't be seen.

I show the previous and next days with:
`.vc-day.is-not-in-month *{
            opacity: 1;
            color: #BDBDBD
        }`

**Comment by nathanreyes** [comment]
Hi @ericuss , you can use the [`trim-weeks`](https://vcalendar.io/layouts.html#trim-weeks) prop to remove the extra week. It is there to keep the calendar height consistent. If you trim weeks, then the height will adjust based on the number of weeks in the month, so please keep that in consideration.
