### ISSUE TITLE
Error when you have an open popover and change month

### ISSUE THREAD

**Issue by jim55167** [nathanreyes/v-calendar#1145]
If you have an open popover on a calendar, and then click the arrow to change the month without closing the popover, the following error appear:

**TypeError: Cannot convert undefined or null to object**

This is happening in your documentation examples too, so thatś why I am sending this issue.

[SampleLink](https://codepen.io/Bo-jun/pen/YzYOEKO?editors=1011)

![螢幕擷取畫面 2022-05-26 093334](https://user-images.githubusercontent.com/67188543/170397364-07847d5f-7710-4499-9c46-a02df7ae98f8.png)

**Comment by mirash333** [comment]
@nathanreyes Could you fix it, pls ?
