### ISSUE TITLE
datePicker: default dayContent styles does not work when set with Vue.use

### ISSUE THREAD

**Issue by Alendorff** [nathanreyes/v-calendar#115]
I wanted to preconfigure styles for calendar but found that this doesn't work:

```javascript
Vue.use(VCalendar, {
  themeStyles: {
    dayContent: {
      fontSize: '1.2rem',
    }
  }
})
```
However direct overwrite works as expected:

```vue
<v-date-picker 
  :theme-styles="{dayContent: {fontSize: '1.2rem'}}"
  mode="range"
  is-double-paned
  is-inline
/>
```

I haven't faced with any other issues related to styling with `Vue.use`. For example, `dayCell` could be styled without problems. But that specific `dayContent` doesn't work and that's very unluckily, because I really need to customize `font-size` and it's not a good option to do it every time.

P.S. Your v-calendar is great anyway, I haven't found anything comparable.

P.P.S. Also docs have some bug, check out `HTML Form Integration` section.

**Comment by nathanreyes** [comment]
Should be fixed as of `v0.9.0`.
