### ISSUE TITLE
Question: caps and highlight customization for date picker

### ISSUE THREAD

**Issue by Alendorff** [nathanreyes/v-calendar#116]
Hi there. I spent some time with v-calendar recently and I probably gave up in trying to finish customization, so decided to ask for help.

On my project I have such css `:root { font-size: 62.5% }` for handy `rem` usage. But v-calendar also based on rems and it turns out that I need many customizations for it just because of font-sizes. And there is one I can't finish - caps. 

https://jsfiddle.net/fz7cteca/6/ - this fiddle illustrates the problem. 

All I need is actually a default caps styling as shown on your landing https://vcalendar.netlify.com/ but because of font-size I had to do my own changes in styles, and probably I did something wrong or missing something. I tried to use some defaults but without success. 

How can I set the same caps as defaults but with height customization?

**Comment by Alendorff** [comment]
By the way I noticed today that your .min.css brings `* { box-size: content-box }` don't you think that it's too opinionated for plugin to add some global css rules?

**Comment by nathanreyes** [comment]
Oh yes. It was in a point release I believe.

**Comment by nathanreyes** [comment]
Ok good deal. Closing this issue for now. Also, there will be a patch to remove the single global style.

**Comment by e-d0** [comment]
@nathanreyes , Hi. highlightCaps is working great. But
 1) How could i style font color inside highlightCaps only?
 2) Could i highlight only first selected cap, and last selected date cap switch off?

**Comment by payalord** [comment]
Is it possible to set custom text colors for `highlight` & `highlightCaps` separately? Because right now there is only available `contentStyle.color` with which is possible to set only 1 common text color for them both.
