### ISSUE TITLE
Feature Request: Custom day cell template

### ISSUE THREAD

**Issue by EricMcRay** [nathanreyes/v-calendar#117]
I need to display custom content for some days and I thought this will be nice feature for everyone who want need to display custom data with day or even some image instead of day.

Use Cases:
- Moon Calendar: Moon phases as image instead of day text
- Special days: You can put emoji for some special dates.
- Weather Calendar: Degree instead of days

Moon Calendar Example:
```
<v-calendar>
    <template :slot="day-content" slot-scope="props">
        <moon-phase :date="props.day.date" />
    </template>
</v-calendar>
```

PR is already made. #108

**Comment by nathanreyes** [comment]
Thanks! Yes I think it would be a nice option to have. I'll check to ensure that the existing layout plays nicely with custom slots.
