### ISSUE TITLE
DatePicker unexpected year focus after shift+tab

### ISSUE THREAD

**Issue by Alendorff** [nathanreyes/v-calendar#119]
There is an example: https://jsfiddle.net/rxb83Lb1/

When navigate across inputs with tab button there are some issue with focus. 

1) Select the last input
2) Shift+Tab (picker input has focus)
3) Shift+Tab again - now year input receives focus, but expected that first input will get it. 

Also if something has been changed on step 2 focus just disappears and after another shift-tab it will be on the first input.

**Comment by Alendorff** [comment]
Also with tabindex=-1 there are outlines appear for panes.

**Comment by nathanreyes** [comment]
You have the right approach (setting `tabindex=-1`). However, the year selector also needs `tabindex=-1`, which you don't have access to. The next update will use `tabindex=-1` as the default for the native popover component, which should take care this issue.

For the outline problem, I don't think it would be wise to just set `outline: none` in css, as I think there should be some indication of focus. I think I'll just use a thin dotted border or some other sensible styling.
