### ISSUE TITLE
Urgent: Header Not Working at all

### ISSUE THREAD

**Issue by anthonybudd** [nathanreyes/v-calendar#1194]
I am trying to make a full size calendar with a header so a user can use the arrows to switch between months.

I have copied the code from this example [https://github.com/nathanreyes/v-calendar/.../.../custom-calendar.vue](https://github.com/nathanreyes/v-calendar/blob/master/docs/.vuepress/components/homepage/custom-calendar.vue) which is on the homepage of [vcalendar.io](https://vcalendar.io/)

But the header does not show up. the calendar displays but there is no way to navigate between months.

I have also tested a simple example just using `<v-calendar />` as per this page [vcalendar.io/navigation.html](https://vcalendar.io/navigation.html). This also does not show the header, the calendar renders as expected but there is no month navigation. 

After inspecting the HTML, I see the container `v-calendar-weekly__head` but I was expecting a div for the header above `div.v-calendar-weekly__head`. Since this is not present I can only assume it's absence is a bug.
```html
<div class="v-calendar-monthly v-calendar-weekly v-calendar theme--light" role="grid">
    <div role="row" class="v-calendar-weekly__head">...</div>
    <div role="row" class="v-calendar-weekly__week">...</div>
    <div role="row" class="v-calendar-weekly__week">...</div>
    <div role="row" class="v-calendar-weekly__week">...</div>
    <div role="row" class="v-calendar-weekly__week">...</div>
    <div role="row" class="v-calendar-weekly__week">...</div>
</div>
```

I have also seen in [the API docs](https://vcalendar.io/api/v2.0/calendar.html#header) are slots `header` and `header-...` , if a user is supposed to use these slots to render the header, please could you update the example calendar to demonstrate this as the current docs/examples are very confusing.

**Comment by sduduzog** [comment]
Quick question, how is this urgent?

**Comment by anthonybudd** [comment]
@sduduzog Being able to navigate between months is a critical feature for a calendar.

**Comment by sduduzog** [comment]
@anthonybudd That does not explain the urgency! In fact, I'm using this package with no problem switching between months. 

So the feature is there, and what you're reporting is a bug. In a pool of 500+ other bugs reported, it's unfair to the maintainer to try rank up your apparent issue above the others and it's unfair to everyone else who logged an issue, as I'm sure everyone else's were just as critical as yours.

**Comment by anthonybudd** [comment]
@sduduzog sorry mom
