### ISSUE TITLE
Alpha 6 to Alpha 8 Breaking Change

### ISSUE THREAD

**Issue by DaveL17** [nathanreyes/v-calendar#1195]
I'm not sure what the breaking change is, but updating from a6 to a8 breaks calendar rendering for me.  Reverted back to a6 and all is well.

`Vue 3.0.0`
`Vuex 4.0.2`
`Bootstrap 5.2.0`

-----

`3.0.0-alpha.8`
<img width="127" alt="Screen Shot 2022-09-13 at 1 46 46 PM" src="https://user-images.githubusercontent.com/8534504/189984978-821a88d8-edf2-40e7-80fa-817f185c7713.png">

-----

`3.0.0-alpha.6`
<img width="127" alt="Screen Shot 2022-09-13 at 1 47 29 PM" src="https://user-images.githubusercontent.com/8534504/189985341-f351e19f-a8fb-4641-9ccf-7b167bb63db5.png">

**Comment by PiotrGrobelak** [comment]
I have same problem. I have to downgrade to `3.0.0-alpha.6`.

**Comment by owenconti** [comment]
@DaveL17 @PiotrGrobelak See if this CSS import fixes the problem for you: https://github.com/nathanreyes/v-calendar/issues/1120

**Comment by DaveL17** [comment]
```
import 'v-calendar/dist/style.css';
```
worked.
