### ISSUE TITLE
The calendar doesnt render

### ISSUE THREAD

**Issue by web-programmer-here** [nathanreyes/v-calendar#1199]
I am using the latest version and vue `2.6.11`

in `script.js` I have this: 

```js
import Calendar from "v-calendar/lib/components/calendar.umd";

export default {
	name: "Calendar",
	components: { Calendar },
	data() {
		return {};
	},
};

```

and in my `component.vue` I have: 

```
<template>
	<div>
		This is calendar place holder
		<v-calendar />
	</div>
</template>
```

but the calendar does not render at all, am i doing something wrong?

**Comment by acidbiscuit** [comment]
@web-programmer-here 
From the information above, it looks like the name that calendar is registered with (`calendar`) is different from the name it is being used (`v-calendar`).

Try changing component registration name:
```
import Calendar from "v-calendar/lib/components/calendar.umd";

export default {
	name: "Calendar",
	components: { 
          'VCalendar': Calendar
        },
	data() {
		return {};
	},
};
```

**Comment by web-programmer-here** [comment]
thanks @acidbiscuit
