### ISSUE TITLE
Resetting datepicker like user hasn't interacted with it

### ISSUE THREAD

**Issue by freiguy1** [nathanreyes/v-calendar#121]
I'm trying to figure out a way to reset my datepicker. Here's the situation: I'm using one datepicker in a modal. This modal may be shown many times while a user is on a page. However, each time the modal is used, it's showing the month/year that was used the last time the modal was used. Instead, I'd like the month/year to be the current one, like it is the first time the user sees this control.

How can I go about this?

**Comment by freiguy1** [comment]
I made it work by binding to `from-page` and every time the modal is shown, run this code:

```js
const today = new Date()
this.datePickerFromPage = { month: today.getMonth() + 1, year: today.getFullYear() }
```

**Comment by EricMcRay** [comment]
@freiguy1 Probably your modal always stay in document and you only hide/show that with css. You can use v-if instead of css, that way every time you open that modal it reinitializes itself.
