### ISSUE TITLE
Disable all dates and then allow only those with a dot?

### ISSUE THREAD

**Issue by enforbAlzi** [nathanreyes/v-calendar#1215]
Hi, is there a way to disable all dates and then allow only those where there is a dot, or from array? Thanks

**Comment by naeem-jtr** [comment]
If ``disabled-dates`` is NOT provided and ``available-dates`` is provided, then an infinite disabled date range(``{ start: null, end: null }``) is first added to effectively disable all dates. Then, available-dates is evaluted to re-enable the dates it specifies.

To disable all dates ``:disabled-dates="[{start:null, end:null}]"`` 
then provide _myDatesArray_ which you want to highlight with dot ``:attributes="[ {dates: myDatesArray, dot: true} ]"``
