### ISSUE TITLE
V-calendar disable functionality

### ISSUE THREAD

**Issue by djanjic** [nathanreyes/v-calendar#122]
Hello, does V-calendar support disable functionality? I need to disable calendar based on some boolean value like standard input HTML component already has. Or can I perhaps, just disable navigation and date select option?

**Comment by djanjic** [comment]
Using `disabled-dates` props I managed to disable selecting. I now just need to disable navigation. Can someone help me with that?

**Comment by kl3sk** [comment]
I think using [slots](https://docs.vcalendar.io/api.html#calendar-slots) is a good way (header-right-button and/or header-left-button), event if @nathanreyes made a greatfull documentations, i do not understand this part !

nonetheless i may have an alternative

https://jsfiddle.net/klesk/z5n7ug53/

**Comment by djanjic** [comment]
This works for `v-calendar` but using this trick with `v-date-picker` allows you to select only today's day. Anyway, thanks for the response.

**Comment by kl3sk** [comment]
Maybe you should say you use date-picker ;)

**Comment by djanjic** [comment]
Yeah, sorry for that.

**Comment by kl3sk** [comment]
Updated fiddle

**Comment by nathanreyes** [comment]
Sorry, as of now you just kind of hack through it. Using the approach you are discussing, you could set `disabled-dates` to an empty object.

```html
<v-date-picker
  :disabled-dates='{}'
  v-model='date'>
</v-date-picker>
```

```javascript
export default {
  data() {
    return {
      date: null,
    }
  }
}
```

I think this could of feature would be best as built in prop (`is-disabled`, or something like that).

**Comment by kl3sk** [comment]
I don't think this is what @djanjic want. See [this fiddle](https://jsfiddle.net/klesk/xpyj9h1r/).

With ```:disabled-date='{}'``` none of them are available and all the picker is disabled.

**Comment by djanjic** [comment]
I already implemented using `disabled-date` prop because style changes I user can clearly see that the date cannot be selected. Still, I would like to have the option to also disable navigation bar and ability to change style when `disabled-date` prop is used.

**Comment by nathanreyes** [comment]
You can configure the `disabled-attribute` prop for this. [Docs link](https://docs.vcalendar.io/datepicker.html#customize-attributes)

**Comment by zachheine** [comment]
@nathanreyes The docs links above is borken.

**Comment by maheshwar-tigadi** [comment]
@zachheine seems the doc website got updated. here is new [Docs link](https://docs.vcalendar.io/guide/datepicker.html#customize-attributes)

**Comment by Abdullah-V** [comment]
You can use this:
```html
<v-date-picker
  :value="null"
  style="pointerEvents:none;"
  />
```
or this:
```html
<div style="pointerEvents:none;">
    <v-date-picker
      :value="null"
    />
</div>
```

**Comment by saslavik** [comment]
```
<vc-date-picker
    :popover="{ visibility: readOnly ? 'hidden' : 'click' }"
    mode="date"
    :masks="{input: 'YYYY-MM-DD', weekdays: 'WW'}"
    v-model="dateStart">
    <template v-slot="{ inputValue, togglePopover }">
      <v-text-field
        :value="inputValue"
        readonly
      ></v-text-field>
    </template>
  </vc-date-picker>
```
