### ISSUE TITLE
Formats defined as a property are ignored

### ISSUE THREAD

**Issue by chrisnetonline** [nathanreyes/v-calendar#123]
According to the documentation (https://docs.vcalendar.io/#formatting--parsing) I should be able to pass the formats in as a property. However, it seems to be ignored. I am trying to remove the year from the title. Setting of formats does work globally though.

Pen: https://codepen.io/chrisnetonline/pen/dmabVe

**Comment by nathanreyes** [comment]
Yes..the date picker is not forwarding the prop to `v-calendar`.

**Comment by chrisnetonline** [comment]
Thanks!
