### ISSUE TITLE
Select a range over disabled dates

### ISSUE THREAD

**Issue by petecoop** [nathanreyes/v-calendar#124]
I'm working on the below calendar, where I'd like users to be able to select either the whole of a single green date range, or to be able to select multiple of these green ranges - where there is 1 per month, I don't want them to be able to select dates in between so have these disabled, at the moment if dates inside a range are disabled it won't allow selection of the next range. Is there a way to handle what I want this to do? 

![screen shot 2018-04-10 at 13 07 56](https://user-images.githubusercontent.com/1655361/38556058-3c347b96-3cc0-11e8-9d77-85564f6e44c9.png)

**Comment by nathanreyes** [comment]
If you are wanting users to select 2 distinct regions, you would need to use 2 separate instances of `v-date-picker` with both modes set to `"range"`.

**Comment by petecoop** [comment]
I'd like them to select 1-4 regions, ideally in one motion with the calendar above otherwise it'd be annoying having 4 calendars just for that

**Comment by EricMcRay** [comment]
you can use v-calendar as base for your need and implement your on functionality over it. You can use calendar day mouse events and highlight attributes props to achieve this. It is really easy. I made my own date picker over v-calender which user can select multiple dates.

What you want is a very special case for your own need.

**Comment by petecoop** [comment]
I wouldn't say it was a very special case, but okay I'll look into that thanks.

See another date picker I've found which has something similar on the first "more examples" https://krystalcampioni.github.io/vue-hotel-datepicker/#moreExamples

**Comment by dolbex** [comment]
@barryvdh - I had the same question.

**Comment by pmcp** [comment]
I'm having the same issue. It's not really a special case I feel. I'm building a library system, the library is open every day of the week, except weekends. An item can be reserved for 3 weeks, so it goes further than the first disabled date (first saturday after day selected).

That being said, I can probably figure out how to do this myself, but it might be a nice thing to add to this tool.

**Comment by Inasyah** [comment]
> Is it possible to just disable them for a starting date, but allow them to be included in a range? Eg. Hotel bookings can be restricted by a certain checkin day, but checkout can be different. Or is that not say you meant?

I'd be very interested in this functionality as you describe it, too:
Disabling days for starting/ending of a range, but allow them to be included in between.

Is this something that could be considered being added?

**Comment by AndreasSchmid1988** [comment]
I'm also stuck on the same issue, i need to exclude days where no check out/check in is possible

**Comment by pmcp** [comment]
I fixed it following this code: https://codesandbox.io/embed/test-vcalendar-ombh3?fontsize=14

But I'm stuck to 1.0.0-beta.13. I think the fix for disabled dates in 1.0.0-beta.13 made this solution not work any more.

**Comment by iadambrown** [comment]
Just wondering if this is still being looked at? 
I'm building a "vacation time manager" and would like to allow range selection from one day to multiple (concurrent) weeks, but also exclude Sat/Sun as those aren't working days. Range selection works between Mon-Fri, but won't skip over to the next work week and continue the range selection.

**Comment by palianah** [comment]
@EricMcRay can u give us a example how to implement it? I think a lot people are missing this feature. thanks!

**Comment by yaroslavvertukhov** [comment]
I would be very happy if such a function appears)

**Comment by JohnCuba** [comment]
@palianah, @yaroslavvertukhov I use a silly solution: I find all nodes of blocked days by class, for example "id-2021-02-12", and add the class "is-disabled" and also the style "pointerEvents = 'none'". It also needs to be updated again when the month changes.

**Comment by allevi18** [comment]
> @iadambrown, @palianah, @yaroslavvertukhov I use a silly solution: I find all nodes of blocked days by class, for example "id-2021-02-12", and add the class "is-disabled" and also the style "pointerEvents = 'none'". It also needs to be updated again when the month changes.

Which event did you use to trigger the limitations? I use the input's hover event, but sometimes the approach fails to update the dates as they're not loaded by time the callback is executed. 
Only solution I came up with was an additional sleep before the function that disables the dates. I wonder if there's any better way to achieve that?

**Comment by JohnCuba** [comment]
> > @iadambrown, @palianah, @yaroslavvertukhov I use a silly solution: I find all nodes of blocked days by class, for example "id-2021-02-12", and add the class "is-disabled" and also the style "pointerEvents = 'none'". It also needs to be updated again when the month changes.
> 
> Which event did you use to trigger the limitations? I use the input's hover event, but sometimes the approach fails to update the dates as they're not loaded by time the callback is executed.
> Only solution I came up with was an additional sleep before the function that disables the dates. I wonder if there's any better way to achieve that? I couldn't find any events which would be triggered on v-calendar successful load.

I just wrap v-calendar in component, and call "disableDates" func on component update.
Here is a my component code:
`
```vue
<template>
  <ClientOnly>
    <div class="calendar" ref="calendarRef">
      <VCalendarDatePicker
        color="orange"
        is-expanded
        :disabledDates="disabledDatesNative"
        :value="value"
        :min-date="computedMinDate"
        :max-date="computedMaxDate"
        @moveNextMonth="disableDates"
        @input="handleDateChange"
        @drag="handleDrag"
        v-bind="$attrs"
      />
    </div>
  </ClientOnly>
</template>

<script>
export default {
  name: 'Calendar',
  inheritAttrs: false,
  model: {
    prop: 'value',
    event: 'input',
  },
  props: {
    value: {
      type: Object,
      required: true,
    },
    disabledDates: {
      type: Array,
      default: () => [],
    },
    disabledDatesNative: {
      type: Array,
      default: () => [],
    },
    minDate: {
      type: Date,
      default: null,
    },
    maxDate: {
      type: Date,
      default: null,
    },
    rangeBoundaries: {
      type: Number,
      default: null,
    },
  },
  data() {
    return {
      isCalendarInit: false,
      isListenersInit: false,
      availableDatesInRange: {
        start: null,
        end: null,
      },
    };
  },
  components: {
    VCalendarDatePicker: () => import('v-calendar/lib/components/date-picker.umd'),
  },
  mounted() {
    this.$nextTick(this.initCalendarState);
  },
  updated() {
    this.disableDates();
  },
  computed: {
    computedMinDate() {
      return this.availableDatesInRange.start || this.minDate || null;
    },
    computedMaxDate() {
      return this.availableDatesInRange.end || this.maxDate || null;
    },
  },
  methods: {
    handleDateChange(date) {
      // Reset available dates after changing it in "handleDrag"
      this.availableDatesInRange = {
        start: null,
        end: null,
      };
      // Emit event outward
      this.$emit('input', date);
    },
    initCalendarState() {
      this.isCalendarInit = true;
    },
    disableDates() {
      // Hack to disable dates with range across to him
      if (this.isCalendarInit) {
        if (!this.isListenersInit) {
          this.isListenersInit = true;
          this.$refs.calendarRef
            .querySelector('.vc-popover-content-wrapper')
            .addEventListener('click', this.disableDates);
          this.$refs.calendarRef.querySelector('.vc-arrows-container').addEventListener('click', this.disableDates);
        }

        this.disabledDates.forEach(date => {
          const dayElem = this.$refs.calendarRef.querySelector(`.id-${date} span`);
          if (dayElem) {
            dayElem.classList.add('is-disabled');
            dayElem.style.pointerEvents = 'none';
          }
        });
      }
    },
    handleDrag(range) {
      // Set boundaries if "rangeBoundaries" specified
      if (this.rangeBoundaries !== null && range) {
        let startDay = range.start.getDate();
        let endDay = range.end.getDate();
        let availableDaysOutOfRange = this.rangeBoundaries - (endDay - startDay);
        let minDay = startDay - availableDaysOutOfRange;
        let maxDay = endDay + availableDaysOutOfRange;
        let availableDatesInRange = {};

        availableDatesInRange.start = range.start;
        availableDatesInRange.start.setDate(minDay);

        availableDatesInRange.end = range.end;
        availableDatesInRange.end.setDate(maxDay);

        this.availableDatesInRange.start =
          this.minDate && this.minDate.getTime() < availableDatesInRange.start.getTime()
            ? availableDatesInRange.start
            : this.availableDatesInRange.start;
        this.availableDatesInRange.end =
          this.maxDate && this.maxDate.getTime() > availableDatesInRange.end.getTime()
            ? availableDatesInRange.end
            : this.availableDatesInRange.end;
      }
    },
  },
};
</script>
````
