### ISSUE TITLE
CalendarPane update:page created miss parameter

### ISSUE THREAD

**Issue by MoraesGil** [nathanreyes/v-calendar#125]
previous I could to get current date by page change trigger on created
now, on Created emit update:page but not passing page by the parameter

**Comment by MoraesGil** [comment]
I still can't get the current page on @update:frompage="pageChange"

this event only trigger when next/back page is clicked, 

have any other way to get Initial Page?

**Comment by EricMcRay** [comment]
You can bind frompage with sync modifier.

`:frompage.sync="myFromPage"`

**Comment by MoraesGil** [comment]
@EricMcRay I've  tried as you suggested but myFromPage never change
and currentPage only update when I move  first time to next or back page
maybe I wrote something wrong can you help?

```
<calendar
              is-expanded
              paneCentered
              :attributes="calendarData"
              :from-page.sync="myFromPage"
              @update:page="pageChange"
              @update:frompage="pageChange"
              @dayclick='dayClick'
              /> 

```
  ```
data() {
    return {
      myFromPage: null, 
      currentPage: null, 
    }
  },
```

  ```
methods: {
pageChange (page) {
      this.currentPage = page
      this.fetchData()
    },
}
```

**Comment by nathanreyes** [comment]
Ok I see where the issue is now. It'll get 'repatched' on the next revision.

**Comment by rcascante** [comment]
Has this issue been updated? 
I'm trying to access to the position property of the page object.
`    
@update:fromPage="changeMonth"

changeMonth(page) {
      console.log(page);
    },
I get only this properties:
days: 31
firstDayOfWeek: 2
firstWeekday: 3
inLeapYear: false
month: 1
weeks: 5
year: 2019
`

**Comment by maicss** [comment]
@rcascante you should use `@update:from-page="someFn"`, the document is wrong, source code: https://github.com/nathanreyes/v-calendar/blob/master/src/components/Calendar.vue#L537
