### ISSUE TITLE
is it possible to set half hours with validHours?

### ISSUE THREAD

**Issue by akc4** [nathanreyes/v-calendar#1267]
For my project, I require some dates to have different start time (hours and minutes). 

1. Is it possible to the half hours with `validHours`? 

2. `:minute-increment="30"` will give me `00, 30` for minutes. However, for same dates I required to have `15, 45`. Is there a way to make this possible without too much custom code?

**Comment by nathanreyes** [comment]
Hi @akc4, it sounds like you might need to use [function rules](https://vcalendar.io/datepicker/time-rules.html#function-rules) to achieve this if you need it to be dynamic based on the date.
