### ISSUE TITLE
Fail to compile after upgrading to 3.0.0

### ISSUE THREAD

**Issue by Lafaiet** [nathanreyes/v-calendar#1269]
My app was using version 3.0.0-alpha-8 following the documentation:

```
import { SetupCalendar } from 'v-calendar';
app.use(SetupCalendar, {})
```

After upgrading to version 3.0.0, through `npm install v-calendar@next @popperjs/core `it doesn't work anymore, with some compiling error:

`export 'SetupCalendar' (imported as 'SetupCalendar') was not found in 'v-calendar' (possible exports: Calendar, DatePicker, Popover, PopoverRow, createCalendar, createDatePicker, default, popoverDirective, setupCalendar, useCalendar, useDatePicker)`

Was this 3.0.0 version supposed to be released? I don't see it being tagged in the repo

**Comment by nathanreyes** [comment]
Hi @Lafaiet, please use `setupCalendar` in lieu of `SetupCalendar`. The new docs was released yesterday and I missed that export rename. It should be updated now on the [install](https://vcalendar.io/getting-started/installation) page.
