### ISSUE TITLE
day-content slot not supported in v3

### ISSUE THREAD

**Issue by marius-mcfly** [nathanreyes/v-calendar#1276]
Hello there,

we're using the `day-content` slot of the Calendar component to customize it in version 3.0.0-alpha8 and we wanted to upgrade to 3.0.0 version. Unfortunately the `day-content` slot is not supported in there and there's also nothing documented about it in the [v3 docs](https://docs.vcalendar.io/).

Do we get support for this slot in the near Future or another way to customize the calendar? :)

**Comment by mostafa-A48** [comment]
We are using `day-content` as well.

**Comment by andersonAlmeida** [comment]
I am having the same issue. I can't use day-content slot.
