### ISSUE TITLE
DatePicker: Custom data is not returned in the dayclick event

### ISSUE THREAD

**Issue by Daniil-Zaitsau** [nathanreyes/v-calendar#1277]
Version: 3.0.1

Steps to reproduce:

1. Create an array of attributes in which there will be an object with the customData property
2. Pass this array as a DatePicker parameter and add a handler for the dayclick event
3. In the handler, add event logging
4. Click on the date with the event

Actual results:  custom data is not returned in the event data

Code example:

```
<template>
  <DatePicker v-model="model" :attributes="attrs" @dayclick="dateSelected"/>
</template>

<script>
import { DatePicker } from "v-calendar";
import "v-calendar/dist/style.css";

export default {
  name: "Calendar",
  components: {
    DatePicker,
  },
  data() {
    return {
      model: new Date(),
      attrs: [
        {
          highlight: true,
          dates: {
            start: new Date(),
            end: new Date(new Date().getFullYear() + 1, 0)
          },
          customData: {
            test: "test"
          }
        }
      ]
    }
  },
  methods: {
    dateSelected(event) {
      console.log(event);
    }
  }
};
</script>
```

Results:
![image](https://user-images.githubusercontent.com/44928584/226430283-e2a75ce3-aa29-432c-badc-6a48f0e9c678.png)

Please tell me, is this a bug or a new expected behavior? I remember that in the previous version of the plugin (3.0.0-alpha.8), this functionality worked. The data was returned in the event object (in the attributes array) and could then be used. Are there any other ways to conveniently get the data that is stored on the date? I found one approach, but to be honest, it's not so convenient:

```
const dayIndex = event.dayIndex;
const dayData = this.$refs.datePicker.calendarRef.dayCells[dayIndex];
const dayCells = dayData.cells;
const customData = dayCells.map((cell) => cell.data?.customData);
```

**Comment by nathanreyes** [comment]
The `attributes` array has been added to the event objects in 3.0.2.
