### ISSUE TITLE
How can I use a single DatePicker to be range or non-range in the same component?

### ISSUE THREAD

**Issue by NathanAP** [nathanreyes/v-calendar#1282]
Hello! I updated the library's version to `3.0.1`, where `is-range` is now deprecated. 

The problem is that it was actually useful. I created a component where I set `:is-range="isRange"`, where `isRange = props.modelValue instanceof Object && props.modelValue.start && props.modelValue.end`. With this code, my DatePicker would always know if it was ranged or not, because if it was a `Date` instance, my is `isRange` would be false.

How can I archive the same result using the `v-model` or `v-model.range`?

**Comment by nathanreyes** [comment]
It is soft-deprecated, but I haven't made a final decision on dropping it in future versions.

Either way, you should be able to pass `modelModifiers` as a prop.

```html
<VDatePicker :model-modifiers="{ range: true }" />
```

If you were also binding to numbers, let's say...

```html
<VDatePicker :model-modifiers="{ range: true, number: true }" />
```

**Comment by NathanAP** [comment]
Great! I'm sure you'll find the best way to make it better :) Thanks!
