### ISSUE TITLE
Styling background for selected day cell

### ISSUE THREAD

**Issue by chrisnetonline** [nathanreyes/v-calendar#129]
I am not seeing a way to do this in the documentation. I'd like to change the color.

**Comment by nathanreyes** [comment]
You can customize by providing your own `select-attribute` prop. For your case, you would need to supply your own `contentStyle` within the attribute. You can read more [here](https://docs.vcalendar.io/datepicker.html#customize-attributes).

Hope that helps.

**Comment by chrisnetonline** [comment]
Is it possible to also do this globally? I can just wrap the component if it's not. Thanks!

**Comment by nathanreyes** [comment]
Actually, no. `datePickerDisabledAttribute` is the only global attribute that can be set for `v-date-picker`. I want to say there was a good reason for that, but I'm getting older and my memory is pretty bad lol.

**Comment by chrisnetonline** [comment]
Haha thanks for all of your help!
