### ISSUE TITLE
Masked input

### ISSUE THREAD

**Issue by ezhkov** [nathanreyes/v-calendar#131]
Is it possible to implement date mask inside input field for the datepicker?

**Comment by EricMcRay** [comment]
You can use custom input for your any special need. Check the docs. 

https://docs.vcalendar.io/datepicker.html#using-custom-slot

**Comment by ezhkov** [comment]
Yes, I know that. But it doensn't recognize v-calendar date format.
Input with masked plugin works well with it's own v-model
V-calendar works well with it's own v-model
But they don't work together, when I use v-calendar's model for text input

**Comment by nathanreyes** [comment]
I'm not sure I understand the problem completely. I just updated the [docs](https://docs.vcalendar.io/datepicker.html#using-custom-slot) today to elaborate on the options you can use when calling `updateValue` in your own input.

If this doesn't lead to an answer, would you mind reproducing the bug? I started a [fiddle](https://jsfiddle.net/nathanreyes/pfkun5f3/) for this issue.

**Comment by kl3sk** [comment]
I have the same problem.
I tried @nathanreyes  docs exemple, and it works perfectly in a normal `<input />` element.

But like @ezhkov even if `vue-masked-input` do it's job perfectly, i can't send event `@change/@input` to it.

**Comment by ezhkov** [comment]
Thank you. Your example works perfectly. It seems I didn't understand scope idea completely.
I forked your example and integrated it with Cleave.js, if anyone else will get the same problem.

https://jsfiddle.net/3wtt9r83/

**Comment by ryanulit** [comment]
How do you get the calendar popover to move to a new date that is updated while the popover is open?  The fiddle above does not account for that case?

**Comment by avxkim** [comment]
@nathanreyes https://docs.vcalendar.io/datepicker.html#using-custom-slot this links seems to be broken.

**Comment by VadimSevruk** [comment]
@ezhkov Thank you very much for your solution!
