### ISSUE TITLE
[BUG]: Forgot to use --vc-select-bg

### ISSUE THREAD

**Issue by micDropper** [nathanreyes/v-calendar#1310]
Looks like `--vc-select-bg` is missing in BaseSelect.vue.

https://github.com/nathanreyes/v-calendar/blob/5cec695ce59faf8558421b548329740af07bfedb/src/components/BaseSelect/BaseSelect.vue#L55

Should be:
```css
background-color: var(--vc-select-bg);
```

This is causing weird background colors for `<select>` dropdowns in dark mode when the select isn't hovered.

**Comment by ghost** [comment]
This was fixed in another commit
