### ISSUE TITLE
Input value for range is not updated for date picker

### ISSUE THREAD

**Issue by maximzasorin** [nathanreyes/v-calendar#134]
Hello, I use date picker with ranges, when updating start of range calendar is updated, but input value is not. I created example for this: https://jsfiddle.net/maximzasorin/sknpqze5/, after clicking on the button, start of range is set to April 16, and calendar shows this, but input value does not change.

**Comment by nathanreyes** [comment]
You need to reset the range object instead of just changing its child property.
```javascript
update () {
  // this.range.start = new Date(2018, 03, 16);
  this.range = {
    start: new Date(2018, 3, 16),
    end: this.range.end,
  }
}
```

**Comment by maximzasorin** [comment]
@nathanreyes Thank you, that's exactly what I did, but I was confused that the calendar was updated and the input field is not, why it happens?
