### ISSUE TITLE
How to hide calendar navigation controls?

### ISSUE THREAD

**Issue by chris90210** [nathanreyes/v-calendar#1343]
How to hide calendar navigation controls (previous/next month and month/year selection)?

Haven't seen anything in the documentation.

I'm trying to hide them using the internal CSS classes to no avail.

**Comment by chris90210** [comment]
Never, this works:

    document.querySelector('.vc-header').remove()
    document.querySelector('.is-lg').remove()

**Comment by Yanyz-ok** [comment]
The page label explains that you can use the keyboard keys to switch dates, and the navigation appears again each time you have switched dates
```
data-helptext="Press the arrow keys to navigate by day, Home and End to navigate to week ends, PageUp and PageDown to navigate by month, Alt+PageUp and Alt+PageDown to navigate by year"
```
