### ISSUE TITLE
Suggestion: Render only Years and Months in the :available-dates range

### ISSUE THREAD

**Issue by gabrielslau** [nathanreyes/v-calendar#135]
Currently, if I set the `:available-dates="{ start: new Date(2018, 0, 1), end: new Date(2018, 2, 31) }"` (between January and March) all the remaining days and months of the year are shown in the calendar.

It would be nice to have a way to render only the days, months and years that are in the range of the specified `:available-dates`.  This way, the user don't need to navigate to a lot of useless dates to get the information he needs.

**Comment by nathanreyes** [comment]
If you are just wanting to prevent selection before January and after April, just use the `min-date` and `max-date` props.
`:min-date='new Date(2018, 0, 1)'` and `:max-date='new Date(2018, 2, 31)`.

In theory, `available-dates` should probably do the same thing, but right now there isn't an easy way to do what you would like while supporting complex date patterns.
