### ISSUE TITLE
day-content slot not providing attributes & day prop

### ISSUE THREAD

**Issue by marius-mcfly** [nathanreyes/v-calendar#1352]
Hello there,

I asked a few month ago to implement the `day-content` slot again. It was done, so thanks so far for adding it and resolving the [issue](https://github.com/nathanreyes/v-calendar/issues/1276)! :)
But sadly it's not fully working as in the earlier versions. The props `attributes` and `day` are not provided for this slot anymore, but they were supported until `3.0.0-alpha.8`.
Is it possible to provide the props again? It would make the calendar more powerful and customizable again. 🔥

We are using the `day-content` slot like this currently:
```typescript
<template #day-content="{ day, attributes }">
    <MyComponent :current-day="day"
    <p>{{ attributes.customData }}</p>
</template
```

**Comment by nathanreyes** [comment]
I'm not sure exactly which version this was fixed, but it should be working again in latest 3.0 version.
