### ISSUE TITLE
How to set the previous days to be grey?

### ISSUE THREAD

**Issue by wuzhoubo** [nathanreyes/v-calendar#137]
I use the calendar,
How can i set the previous days 'color:grey' and can't click?

**Comment by jonagoldman** [comment]
You can disable the dates using the `max-date` or `disabled-dates` properties.
You can find that in the [docs](https://docs.vcalendar.io/datepicker.html#disable-dates--patterns).

**Comment by wuzhoubo** [comment]
i do not use the date-picker, only use the calendar.
i select days by the event dayclick.
it's my code
```
<calendar
        :theme-styles='themeStyles'
        :attributes='attrs'
        :min-date="new Date()"
        title-position="center"
        show-caps
        @update:frompage="pageChange"
        @dayclick="dayclick"
        >
        </calendar>
```
the min-date,max-date or disable-dates only work in month ,the day also can click

**Comment by EricMcRay** [comment]
You can change style with attributes option like below. But you need to handle click event by yourself.

```js
{ dates: { start: null, end: new Date() }, contentStyle: { color: 'grey' }}
```

**Comment by wuzhoubo** [comment]
Thanks a lot,I think it's the best solution now.

**Comment by nathanreyes** [comment]
@EricMcRay Thanks for the help there.
