### ISSUE TITLE
Docs site down?

### ISSUE THREAD

**Issue by kylegosen** [nathanreyes/v-calendar#1370]

**Comment by Nick-Getka** [comment]
[It is down.](https://v2.vcalendar.io/)  I am seeing a cloudflare timeout.  I am also having an issue with the range mode not working on the v2 package so this is really bad timing.

**Comment by Nick-Getka** [comment]
@nathanreyes Could you please looking into this?

**Comment by keshavagrawal89** [comment]
@Nick-Getka May be meanwhile this can help? https://dewdad.github.io/v-calendar/guide/

**Comment by BevanR** [comment]
Temporary; https://v-calendar-docs-2.netlify.app/

You can also run docs locally by;

1. cloning the repo
2. `yarn install`
3. `yarn dev`

**Comment by nathanreyes** [comment]
Ok sorry for the issue there. I went ahead and updated the v2 docs url from the main site until I can resolve the issue with the v2 subdomain
