### ISSUE TITLE
Website down ?

### ISSUE THREAD

**Issue by Dalvii** [nathanreyes/v-calendar#1374]
https://vcalendar.io/ is currently down, since its a static website, I suppose it has been manually taken down.
Any updates ?

**Comment by nadirabbas** [comment]
Still not working, any updates @nathanreyes ?

**Comment by nathanreyes** [comment]
It is loading just fine for me. I wonder if it may only be down for some regions?

**Comment by zaherg** [comment]
@nathanreyes I have set up this monitoring, I'll keep it on for the next two days: https://updown.io/l128 . Hopefully, it will help you figure out the issue.

**Comment by BancarelValentin** [comment]
Same for me, cloudfare cannot access the host it seems. 
![image](https://github.com/nathanreyes/v-calendar/assets/5629639/8937b0da-489d-470c-8691-bfb905f907b1)

I managed to accesss the doc throught the way back machine, i hope it's not too much outdated: https://web.archive.org/web/20230617140741/https://vcalendar.io/

**Comment by EvanSchleret** [comment]
522 from Switzerland too. I hope he comes back soon.

**Comment by Sovai** [comment]
522 from Cambodia too

**Comment by EvanSchleret** [comment]
For your information, https://v2.vcalendar.io/ works but https://vcalendar.io/ not. Maybe only the v1 documentation is down ?

**Comment by zaherg** [comment]
The issue is more related to those who access the internet via IPv4 only (like me), not IPv6

![image](https://github.com/nathanreyes/v-calendar/assets/27624/496363de-f7d4-4d5b-a7d5-481eea3c259a)

**Comment by foxted** [comment]
I am facing the same issue here (IPv6 / Canada). Going on VPN in the US over IPv4 fixes the issue.

**Comment by EvanSchleret** [comment]
I tried to access with both IP versions (I can quickly switch with my access provider) but had the same problem.

**Comment by nathanreyes** [comment]
Ok I have tried clearing the cache in Cloudflare. I'm hoping maybe something got out of whack. Could someone verify if the site is still down on their end?

**Comment by manuelmeindl** [comment]
Still broken for me, but netlify works thx!

**Comment by EvanSchleret** [comment]
I can now access with an IPv4 address at https://vcalendar.io/. I'll let you know if that changes. 

Many thanks👍🏼

**Comment by nathanreyes** [comment]
This issue should be resolved.
