### ISSUE TITLE
Manual input dropped with version 3.1.1

### ISSUE THREAD

**Issue by mbrodala** [nathanreyes/v-calendar#1387]
A date value can be entered manually in an input element provided with the `default` slot. With version 3.1.1 of this package that input is dropped immediately when leaving the field (Tab/blur by click anywhere else):

| ![image](https://github.com/nathanreyes/v-calendar/assets/5037116/5c7d3bd8-b925-46ed-a316-d163e2f21a79) | ![image](https://github.com/nathanreyes/v-calendar/assets/5037116/e75d41c8-c03c-40a6-a2a2-c2bd8d16cb85) |

(Using `locale: 'de'` here

The very odd thing: it works for some dates. E.g. given today's date is 2023-10-09, it works for -10, -11 and -12:

![image](https://github.com/nathanreyes/v-calendar/assets/5037116/0c7789f9-3063-4bc1-be2d-decbffc8c8c0)

But not for any date after that. For the working dates also the marker for the current date appears in the calendar. For broken dates this does not happen.

Unfortunately there are no errors in the browser console.

**Comment by nathanreyes** [comment]
This should be fixed as of 3.1.2. Thanks for reporting.

**Comment by mbrodala** [comment]
Yup, that did the trick, thanks a lot!
