### ISSUE TITLE
When one v-calendar is opened, other is not closing

### ISSUE THREAD

**Issue by ituyakpaev** [nathanreyes/v-calendar#1388]
I have date input component with this code:
`<template>
  <div class="ui-field-container ui-field-date">
    <v-date-picker :key="_uid" ref="datepicker" v-model="dateValue" v-bind="config" @popoverWillShow="move">
      <template v-slot="{ inputValue, inputEvents }">
        <InputBox
            :label="label"
            :error="error"
            :value="range ? \`${ inputValue.start || 'dd:mm:yy' } - ${ inputValue.end || 'dd:mm:yy' }\` : inputValue""
            :disabled="disabled"
            v-on="disabled ? {} : (range ? inputEvents.start : inputEvents)"
        />
      </template>
    </v-date-picker>

    <button class="ui-field-date__cancel"
            :class="{'date-input__cancel--showed': range ? value.start && value.end : !!value }"
            @click="clear()">
      <icon name="close" width="24"/>
    </button>
  </div>
</template>

<script lang="ts">
import Vue, {PropType} from "vue";

type RangeDate = { start: string | null, end: string | null }

export default Vue.extend({
  name: "DateBox",
  inheritAttrs: false,
  props: {
    timezone: {
      type: String as PropType<"native" | "UTC">,
      default: "UTC"
    },
    label: {
      type: String
    },
    value: {
      type: [String, Object] as PropType<string | RangeDate>,
      required: true
    },
    error: {
      type: String
    },
    mode: {
      type: String as PropType<'date' | 'dateTime' | 'time'>,
      default: 'dateTime',
    },
    default_date: {},
    required: {
      type: Boolean,
      default: false
    },
    disabled: {
      type: Boolean,
      default: false
    },
    range: {
      type: Boolean,
      default: false
    }
  },
  data() {
    return {
      date: null
    }
  },
  computed: {
    config(): object {
      return {
        'is-required': this.required,
        'is-range': this.range,
        mode: this.mode,
        is24hr: true,
        timezone: this.timezone === 'native' ? null : this.timezone,
        popover: {
          visibility: 'click',
          autoHide: true
        },
        attributes: [],
        'model-config': {
          type: 'string',
          mask: 'iso'
        }
      }
    },
    dateValue: {
      get(): string | RangeDate {
        return this.value
      },
      set(v: string | RangeDate) {
        this.$emit('input', v)
      }
    },
  },
  methods: {
    move() {
      if (this.default_date) {
        if (!this.value) {
          // @ts-ignore
          this.$refs.datepicker.move(this.default_date)
        }
      }
    },
    clear() {
      // @ts-ignore
      this.date = this.range ? { start: null, end: null } : ''
    }
  },
})
</script>
`

When i have 1 date component on the page, it opens when focus on input and closes when click somewhere else.
When i have 2 components, i click on first one, it's opens. Then i click to the second one, it's opens, but the first one is not closed.
Anyone know how to fix it?

**Comment by sevenmay** [comment]
@ituyakpaev How did you solve the problem?

**Comment by ElenaPrygun** [comment]
The same problem. Has anyone found a solution?
Upd. In my case the problem was with the styles.
If I use this solution, the datepickers switch correctly:

`
 <DatePicker v-model="licenseExpirationDate" :masks="masks"
              :popover="{ visibility: 'click', placement: 'bottom-end' }" :first-day-of-week="2" :min-date="new Date()">
              <template #default="{ inputValue, togglePopover }">
                <div class="relative w-full ">
                  <input :value="inputValue" v-on:click="togglePopover" placeholder="Expiration date"/>
                  <button @click="() => togglePopover()" class="">                  
                  </button>
                </div>
              </template>
            </DatePicker>
`
