### ISSUE TITLE
v-calendar on mobile is appearing different

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#14]
The month and weekdays are appearing different on mobile relative to desktop (without modifications, except the color style), look:

**Desktop:**
![desktop](https://user-images.githubusercontent.com/11582056/33089428-b567e536-ced7-11e7-951c-3ab00109dcd5.jpg)

**Mobile:**
![mobile](https://user-images.githubusercontent.com/11582056/33089490-e981d340-ced7-11e7-92df-d28175c0a44d.jpg)

It's a known bug @nathanreyes?

**Comment by nathanreyes** [comment]
Yes, it seems that your locale is not getting detected on your mobile browser or it is not supported out of the box? May I ask what mobile browser you are using?

**Comment by luiztsmelo** [comment]
Oh, my mobile browser is in english, but desktop is in portuguese, that's the case. Thanks
