### ISSUE TITLE
ReferenceError: Can't find variable: Intl

### ISSUE THREAD

**Issue by chrisnetonline** [nathanreyes/v-calendar#141]
I receive this error on iOS Safari 9.3 even though I've tried both polyfill options described in the docs (https://docs.vcalendar.io/#polyfill).

**Comment by chrisnetonline** [comment]
I just came across this in the README for the polyfill referenced in your docs.

Reference: https://github.com/zloirock/core-js/blob/master/README.md#missing-polyfills

"ECMA-402 Intl is missed because of size. You can use this polyfill." (https://github.com/andyearnshaw/Intl.js/)

**Comment by nathanreyes** [comment]
Thanks for the info. I'll update the link.
