### ISSUE TITLE
Clicking same date reset date to 1.1.1970

### ISSUE THREAD

**Issue by zlajaa1** [nathanreyes/v-calendar#142]
Clicking on the same day while it is already selected, reset date to 1.1.1970, single mode

**Comment by nathanreyes** [comment]
Clicking on the same day will reset to `null` value (ref [this fiddle](https://jsfiddle.net/nathanreyes/mze12dg5/)). Are you saying you would like to reset to 1.1.1970?

**Comment by zlajaa1** [comment]
I'll make fiddle, it;s not that it's null, but the custom input gets populated instead of emptied

**Comment by zlajaa1** [comment]
My bad, it was updated on the other place
