### ISSUE TITLE
Dependency was not found error

### ISSUE THREAD

**Issue by heash0000** [nathanreyes/v-calendar#1423]
If you install the web anew and proceed with the npm installation and proceed with the npm run build, the following problems occur. 

![image](https://github.com/nathanreyes/v-calendar/assets/120258749/c8e1e108-2f7a-4cfd-bf46-c8be416e5b16)

If you proceed with npm run build with the node_modules folder that you previously installed, there is no problem.

The npm install --save v-calendar/lib/components/date-picker.umd also causes problems.
![image](https://github.com/nathanreyes/v-calendar/assets/120258749/70401473-b2cc-4928-9180-c3ae545465df)

What should I do?

**Comment by shubzz2110** [comment]
Re install it, and use plugins instead

**Comment by heash0000** [comment]
I've already reinstalled it a few times, but the same problem occurs. The same problem occurs in the new environment. The v-calendar version I use has been in the same environment as before, but this problem has occurred. 

After checking the installed node_modules/v-calendar, we found that the configuration was different from the previous one. Existing v-calendar had components folder, but not newly installed v-calendar.

Before
![image](https://github.com/nathanreyes/v-calendar/assets/120258749/aa1e321a-8e4e-4355-b1c7-69cfef072028)

Recently
![image](https://github.com/nathanreyes/v-calendar/assets/120258749/780b2a8f-8ebc-4b3c-8ac6-e2aa275d87ab)

**Comment by vascofbribeiro** [comment]
I had the same problem after updating from `2.4.1 -> 2.4.2` although after looking at the changes from the previous version I don't see anything that could affect /.lib folder generation.
A workaround, for now, is to import specifically `DatePicker` or other components from `'v-calendar/lib/v-calendar.umd'` on your files

```
import { DatePicker } from 'v-calendar/lib/v-calendar.umd'
```

If this is the new way to go then the documentation should be changed: https://v2.vcalendar.io/installation.html

**Comment by heash0000** [comment]
Thank you for your response. First of all, I'll have to use version 2.4.1.

**Comment by rkhandev** [comment]
Going back to 2.4.1 fixed this for me.

**Comment by leodip** [comment]
I'm having the same issue. My code has:

```
import DatePicker from 'v-calendar/lib/components/date-picker.umd';
```

When I upgrade from 2.4.1 to 2.4.2, I get:

Module not found: Error: Can't resolve 'v-calendar/lib/components/date-picker.umd'

The documentation needs to be updated because this import statement doesn't work anymore in version 2.4.2.

What's the correct way to import the DatePicker component?

**Comment by cchacholiades** [comment]
Having the same issue. Updated to 2.4.2, downgrading does not seem to resolve this for me. Any thoughts @nathanreyes ?
