### ISSUE TITLE
Adjust Calendar's Size

### ISSUE THREAD

**Issue by flowingcloud516** [nathanreyes/v-calendar#143]
is there anyway to adjust the size of calendar?
I have  tried  style = "height: xxx px; width: yyy px;" like:
```
<v-calendar :attributes='attrs' :formats='formats' style="height: xxx px; width: yyy px;"></v-calendar>
```
When height is larger than default height, its background is longer but content not become longer, like this:
![image](https://note.youdao.com/yws/api/personal/file/WEB6a3898cdab110a0e44548f63cf63e524?method=download&shareKey=869e2f97c1ec6e7f3cf527b9376fbc65)
when height is smaller than default height, the calendar seems to be broken, like this:
![image](https://note.youdao.com/yws/api/personal/file/WEB3903b987a3d2393ed9cf7040a935246c?method=download&shareKey=395fa44fbaf1d37c8506905162844341)

P.S.
also, I found using _paneWidth_ can introduce performance unexpected, like when i use _paneWidth_: 400, it holds original width; when i annotate __paneWith_:400, it become wider.

**Comment by mjbates7** [comment]
To add to this, would be nice if there was an equivalent of `is-expanded` for vertical sizing so it can fill 100% vertically and the rows etc resize to accommodate this

**Comment by joao-ortiz** [comment]
I have been testing around this bug since it happened with a website I'm working on as well, and, after quite a lot of time researching and trying out different aproaches, I've managed to fix it by setting padding values to the dayContent elements. Here is what I did:
`themeStyles: {
        wrapper: {
          background: 'linear-gradient(to bottom , #0d47a1, #6596e0)',
          color: 'white'
        },
        weekdays: {
          padding: `20px ${hSpacing} 5px ${hSpacing}`,
        },
        weeks: {
          padding: `20px ${hSpacing} ${hSpacing} ${hSpacing}`,
        },
        dayContent: {
          padding: `30px ${hSpacing} ${hSpacing} ${hSpacing}`,
        }
      }`

**Comment by joao-ortiz** [comment]
I have been testing around this bug since it happened with a website I'm working on as well, and, after quite a lot of time researching and trying out different aproaches, I've managed to fix it by setting padding values to the dayContent elements. Here is what I did:
themeStyles: {
        wrapper: {
          background: 'linear-gradient(to bottom , #0d47a1, #6596e0)',
          color: 'white'
        },
        weekdays: {
          padding: `20px ${hSpacing} 5px ${hSpacing}`,
        },
        weeks: {
          padding: `20px ${hSpacing} ${hSpacing} ${hSpacing}`,
        },
        dayContent: {
          padding: `30px ${hSpacing} ${hSpacing} ${hSpacing}`,
        }
      }

**Comment by nnishimura** [comment]
For anyone who has this issue, it's possible by resetting css var like this:

```
.vc-container {
  --day-content-height : 40px;
  --day-content-width : 40px;
}
```

**Comment by SamuelALSN** [comment]
> For anyone who has this issue, you can change calendar size by changing css var like this:
> 
> ```
> .vc-container {
>   --day-content-height : 50px;
>   --day-content-width : 50px;
> }
> `
in which file can we find this class vc container

**Comment by nathanreyes** [comment]
The calendar container element has since been updated with `height: max-content` to properly display in flex containers with larger height than the calendar itself.
