### ISSUE TITLE
How to make the provided date visible in the date field?

### ISSUE THREAD

**Issue by harishankards** [nathanreyes/v-calendar#144]
Hi,
Please find the image below. I have provided default date to the v-datepicker. It's shown in the calendar while hovering. But it's not in the placeholder. 
My code is
```js
<v-date-picker
            mode='range'
            :min-date='new Date()'            
            v-model='contestData.date'>
        </v-date-picker>
```
What am I doing wrong?

![2018-05-09-131217_1360x768_scrot](https://user-images.githubusercontent.com/5006693/39802144-e76c91e8-538a-11e8-9cc3-6451343f7529.png)

**Comment by EricMcRay** [comment]
@harishankards, Can you provide some example to reproduce the bug. You can use codesandbox below.

[![Edit VCalendar Sandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zknjxol864)

**Comment by harishankards** [comment]
Hi @EricMcRay,
Thanks for the response.
Here it is: https://codesandbox.io/s/k991xo3xqr

**Comment by EricMcRay** [comment]
@harishankards thanks for link. Looks like there is a bug when parsing a string to input value. You can avoid this by casting your date strings to Date object. I also advice to use "null" for zero value instead of empty string.

For your example your properties should be like this:
```
export default {
  name: "Example",
  data() {
    return {
      date: {
        start: null,
        end: null
      }
    };
  },
  mounted() {
    this.date.start = new Date("2018-05-17T18:30:00.000Z");
    this.date.end = new Date("2018-05-19T18:30:00.000Z");
  }
};
```

**Comment by harishankards** [comment]
@EricMcRay thanks for the prompt response.

I tried setting up using `null`. The error is still the same. But when I cast like
```
date:{
start: new Date()
end: new Date()
}
```
which displays current date which I dont want. I want to display the date, I'm assigning.

**Comment by harishankards** [comment]
Hey @EricMcRay, just want to check whether do I have any updates on this issue or not.

Looking forward!

**Comment by RomeroMsk** [comment]
@harishankards, just wrap your string date values into `new Date()`:
```js
  mounted() {
    this.date.start = new Date("2018-05-17T18:30:00.000Z");
    this.date.end = new Date("2018-05-19T18:30:00.000Z");
  }
```
instead of
```js
  mounted() {
    this.date.start = "2018-05-17T18:30:00.000Z";
    this.date.end = "2018-05-19T18:30:00.000Z";
  }
```

Here is a working example forked from yours: https://codesandbox.io/s/p921kx9ol7

**Comment by harishankards** [comment]
Hey @RomeroMsk. That helped a lot. Thanks mate!
