### ISSUE TITLE
Problem with popover when used with clear button

### ISSUE THREAD

**Issue by akki-jat** [nathanreyes/v-calendar#152]
When Date Picker used with clear button there are few problems with popover.

### 1.
When we click on clear button popover opens and closes sometimes.
### 2.
After clicking clear button if we again open the popover and select date then popover stays open
### Here is the jFiddle link
[https://jsfiddle.net/akki_jat/ua0njcyg/6/](https://jsfiddle.net/akki_jat/ua0njcyg/6/)

**Comment by EricMcRay** [comment]
v-date-picker listens children on click events. So you need to move clear button outside of v-date-picker.

**Comment by akki-jat** [comment]
Hi @EricMcRay, I will try that but in example of github button is in v-date-picker.
Why is that?

**Comment by akki-jat** [comment]
It's working properly now.
Thanks @EricMcRay.
