### ISSUE TITLE
Calendar icon not visible on date picker input area

### ISSUE THREAD

**Issue by harishankards** [nathanreyes/v-calendar#153]
Hi,
I'm trying to have the calendar icon in the input area of date picker like [this](https://github.com/nathanreyes/v-calendar#date-picker)
But, I'm not able to display the calendar icon:
Below is my code:
```html
<v-date-picker
  mode='single'
  v-model='selectedDate'>
  <b-field >
    <b-input
      type='text'
      icon='calendar'>
    </b-input>
  </b-field>
</v-date-picker>
```
Please let me know what am I doing wrong?

**Comment by EricMcRay** [comment]
This issue may not be about date picker. If you thinks date picker cause this problem, please provide a a code example to reproduce the issue.

You can fork from this:
[![Edit Vue Datepicker demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/rrzjwrxl2n)

**Comment by prathamMantri** [comment]
Not able to get calendar icon. I am trying to display calendar on a page with core-ui template.
Tried everything, but not able to to display calendar.

Please find below code.

``
<b-form-group label="Drop Off Date" align="left">
										<b-input-group>
											<v-date-picker v-model='dropOffDate'
														   mode='range'
														   is-double-paned
														   :max-date='new Date()'
														   show-caps>
												<b-date-input
													type='text'
													slot-scope='props'
													icon='calendar'
													size="lg"
													:value='props.inputValue'
													:placeholder='inputState.message'
													@change.native='props.updateValue($event.target.value)'
													expanded>
												</b-date-input>
												
											</v-date-picker>
											<b-input-group-append>
												<b-button variant="primary" @click='selectedValue = null'>
													Clear
												</b-button>
											</b-input-group-append>
										</b-input-group>
									</b-form-group>
``

`import { Component, Vue } from 'vue-property-decorator';
	
	import { setupCalendar, DatePicker } from 'v-calendar'
	import 'v-calendar/lib/v-calendar.min.css'


	setupCalendar({
		firstDayOfWeek: 2 // Monday
	})

	const today = new Date()


	export default Vue.extend({
		name: 'RepairSearch',
		components: {
			'v-date-picker': DatePicker
		},
		data () {
			return {
				dropOffDate: {
					start: new Date(today.getFullYear(), today.getMonth()-1, today.getDate()-1),
					end: new Date(today.getFullYear(), today.getMonth(), today.getDate())
				}
			}
		},
		computed: {

			inputState() {
				if (!this.selectedValue) {
					return {
						type: 'is-danger',
						message: 'Date required.',
					};
				}
				return {
					type: 'is-primary',
					message: '',
				};
			},

		},
		methods: {
		}
	});`

**Comment by nathanreyes** [comment]
Date pickers now require a custom slot now if wanting to use an input.

https://vcalendar.io/datepicker.html#input
