### ISSUE TITLE
[Feature Request] Set locale from prop

### ISSUE THREAD

**Issue by akki-jat** [nathanreyes/v-calendar#154]

**Comment by iboldurev** [comment]
hi @akki-jat, can be used in the following way

```javascript
<template>
  <div>
    <v-date-picker v-model="selectedDate" />
  </div>
</template>

<script>
import { setupCalendar } from 'v-calendar'
import 'v-calendar/lib/v-calendar.min.css'

export default {
  data: () => ({
    selectedDate: new Date()
  }),
  created () {
    setupCalendar({
      locale: 'uk'
    })
  }
}
</script>
```

**Comment by akki-jat** [comment]
hi @iboldurev, I was talking about the scenario where I want two date-picker on same page with different languages.

But as per your example the last locale value overwrites both calender's languages.

### Example
```
setupCalendar({
   locale: this.language_code ? this.language_code : 'en'
}) 
```

and language_code is a prop.

**Comment by kostaricic** [comment]
Hi @akki-jat , in your case you can make custom components (wrappers) for each picker on the same page, and use  **setupCalendar** with _locale_ settings you prefer for each picker (component).

**Comment by akki-jat** [comment]
Hi @kostaricic, I also thought that but event in custom components it overrides the claendar's locale.

### You can see here
[https://codesandbox.io/s/nrqk941p2p](https://codesandbox.io/s/nrqk941p2p)

**Comment by EricMcRay** [comment]
@kostaricic it is not possible with current setup function. It sets global defaults every time it runs. I did not dive into base code but as I think there is no way to hack this easily.

This is a really proper request and should be implemented.

**Comment by kostaricic** [comment]
@EricMcRay @akki-jat I had a different use case and I needed it for inline calendar and it worked. But, you are right, I can't manage it to work when prop _isInline_ is set to false.
[](https://codesandbox.io/s/y031285rzv)

**Comment by nathanreyes** [comment]
I'll try and do a proper investigation into this issue. I'm curious as to the use case for having multiple locales. I'm not saying it isn't a valid use case...just curious as to how you are using it.

Apologies for being late to the discussion here...just started a new job and also working on some bigger changes for this plugin...just taking a bit longer than expected.

**Comment by akki-jat** [comment]
Hi @nathanreyes, Congratulations for new job.

### And about the use-case
 I am creating the **vue-custom-element** with multi-language support and using **v-calendar** in it.
For multi-language support, I am passing language prop and based on that language changes.

And one day out of curiosity I placed two custom element on one page page with different languages.
Everything was working fine, only v-calendar's language was overwritten by new one.

So, as you can see, for me this feature is like nice to have. That's why I added it as **Feature Request**  not **Bug Report**

**Comment by nathanreyes** [comment]
Closing outstanding issue. Please reference the guide for locale documentation.
https://vcalendar.io/i18n.html#locales
