### ISSUE TITLE
[Feature Request] Use popper.js for aligning popover

### ISSUE THREAD

**Issue by akki-jat** [nathanreyes/v-calendar#155]
### Issue (You can see)
[https://jsfiddle.net/akki_jat/0baL52zv/2/](https://jsfiddle.net/akki_jat/0baL52zv/2/)

### Answer
Use popover-align

### Proper Solution
When using responsive design we doesn't know where date-picker will be placed.
So, it will be good if date-picker automatically align itself according to window size.
Popper.js is a good library, you can have a look.

**Comment by akki-jat** [comment]
If anyone looking for dynamic aligning, I am using it like this : 

### Add this event to `v-calendar`
`@popover-did-appear="alignPopover"`

### And in the `alignPopover` method
```
alignPopover() {
    let popoverElement = document.querySelector('.popover-origin');
    if (popoverElement.getBoundingClientRect().right >= document.body.offsetWidth) {
      if (popoverElement.classList.contains('align-left'))
        popoverElement.classList.replace('align-left', 'align-right');
    }
  }
```

**NOTE** : I am only checking for right boundary and making it align-right dynamically.

**Comment by nathanreyes** [comment]
`popper.js` support has since been added. Closing outstanding issue.
