### ISSUE TITLE
Highlight today

### ISSUE THREAD

**Issue by thiagocolebrusco** [nathanreyes/v-calendar#156]
Hello, 

I'm trying to find a way to hightlight today on every datepicker that I have on my application. Is there a easy way to do it or do I need to set the attributes param on every v-date-picker I have? 

Thanks

**Comment by nathanreyes** [comment]
Yes, providing custom `attributes` is the recommended way to accomplish this. Very sorry for late reply.

Doing some issue cleanup.

**Comment by StevenInc** [comment]
It is still broken
