### ISSUE TITLE
Popover is not opening after coming from another tab

### ISSUE THREAD

**Issue by akki-jat** [nathanreyes/v-calendar#158]
### Problem
When we open the calendar then without closing it, we got to another tab then after coming back calendar popover doesn't open. (We have to click outside one time to open it)

### Repo Link
[https://jsfiddle.net/akki_jat/a86Lbcuk/1/](https://jsfiddle.net/akki_jat/a86Lbcuk/1/) 

### Steps to Reproduce
Open the calendar then go to another tab and come back & try to open calendar again.

**Comment by nass600** [comment]
Happening to me also. Looks like the Datepicker doesn't get blurred and is not listening to the FocusEvent that would happen when coming back from changing tab.

**Comment by nass600** [comment]
My workaround for the moment is hooking up on `popover-will-disappear' and trigger a blur event by hand on the Datepicker input. Not sure if this will help in your scenario

**Comment by kl3sk** [comment]
It seems to be happening under Chrome (67.0.3396.99) . With Firefox (61.0.1) it works perfectly.

**Comment by nathanreyes** [comment]
Closing outstanding issue as it seems to have been remedied. Apologies for late reply.
