### ISSUE TITLE
Way to mutate vuex

### ISSUE THREAD

**Issue by vukadinFE** [nathanreyes/v-calendar#160]
Hi,
Is there any option for `v-date-picker` like `:value` and `@update` instead of `v-model` so I can mutate `vuex` state?

**Comment by EricMcRay** [comment]
`<v-date-picker v-model="date" />` equivalent is `<v-date-picker :value="date" @input="date = $event" />`. So you can use input event and value binding.

**Comment by vukadinFE** [comment]
Thank you.

**Comment by EricMcRay** [comment]
Please close the issue if it is solved.
