### ISSUE TITLE
Programmatically set currently visible month

### ISSUE THREAD

**Issue by shmarts** [nathanreyes/v-calendar#163]
Is there a way to programmatically set the current month visible on the v-calendar component? I looked for a while about page objects and the moveThisMonth() function but couldn't figure out where to use them or how.

**Comment by EricMcRay** [comment]
You can use `from-page` prop. it also have update event so you can bind that to your data with sync modifier.

**Comment by shmarts** [comment]
@EricMcRay Would you mind giving me a quick example? I'm not sure I understand what you mean by using the prop

**Comment by EricMcRay** [comment]
@shmarts check the below example. I hope it helps.

https://codesandbox.io/s/3y0ol019j6?module=%2Fsrc%2Fcomponents%2FExample.vue

**Comment by shmarts** [comment]
@EricMcRay EXACTLY what I was looking for, thank you so much!
