### ISSUE TITLE
Enhancement request: Allow firstDayOfWeek to be set via props rather than one-time at initialization

### ISSUE THREAD

**Issue by psarin** [nathanreyes/v-calendar#164]
Would like to have different calendars starting at different first day of week. Rationale is that I want to implement a "week" / "X days" view which only renders between a certain date rate (related to issue https://github.com/nathanreyes/v-calendar/issues/135).

I implemented setting of this via props and could submit a PR, if interested. There were a couple of changes to the source code I wasn't sure about, though. 

Also, after implementing firstDayOfWeek via props, I was able to implement the "X days" / "week" views in my application via v-if directives, some JS, and CSS to show/hide appropriate weeks, but perhaps there is way to do this in your plugin instead.

BTW, thanks for the excellent plugin!

**Comment by nathanreyes** [comment]
Apologies for late reply. Closing this outstanding issue as there has since been a `first-day-of-week` prop added. Please generate a new issue if needed.
