### ISSUE TITLE
DatePicker double paned - initial monthes to show per each calendar?

### ISSUE THREAD

**Issue by payalord** [nathanreyes/v-calendar#166]
My both calendars not allowed to use dates that is higher than current time. So I set max limit for selection. And because of this + because by default range must be selected starting from current date minus 7 days both datepicker calendars showing same month on first loading. After any action(let say selection range on current month) the left one moves automatically to previous month, while right one is still on current.

Is it possible to set initially which month to show per each calendar in double paned date picker? Thanks.

**Comment by payalord** [comment]
Is it possible to trigger click or run some API function - on one of calendar in `v-date-picker` to move to previous month?

**Comment by EricMcRay** [comment]
@payalord there is 2 props for changing shown month, `from-page` and `to-page`. these may help you to solve your issue. 

Docs: https://docs.vcalendar.io/api.html#calendar-props

**Comment by payalord** [comment]
Thanks, this props helped. I'm using moment.js for dates. This is how I implemented the values, in case if someone need it:
```html
<v-date-picker
    mode="range"
    v-model="myRange"
    :max-date="max"
    :from-page="fromPage"
    :to-page="toPage"
    is-double-paned
    is-inline></v-date-picker>
```
```javascript
max: moment().toDate(),
fromPage: {
    month: parseInt(moment().subtract(1, 'months').format('M')),
    year: parseInt(moment().subtract(1, 'months').format('YYYY'))
},
toPage: {
    month: parseInt(moment().format('M')),
    year: parseInt(moment().format('YYYY'))
}
```
