### ISSUE TITLE
Reduce Size Modular Import.

### ISSUE THREAD

**Issue by nereuseng** [nathanreyes/v-calendar#168]
I noticed the file size import between Components Method and Plugin method was same(which 93.2kb and 25.5k gzipped)
Is that any possible to reduce file size if I only need import Calendar component like the way of lodash?

FYI:
https://www.npmjs.com/package/lodash
https://marketplace.visualstudio.com/items?itemName=wix.vscode-import-cost

BTW I really love this package, I enjoy from your package! :)

**Comment by hmaesta** [comment]
Close this issue in favor of https://github.com/nathanreyes/v-calendar/issues/479
