### ISSUE TITLE
Can't disable multiple date ranges in a date-picker

### ISSUE THREAD

**Issue by bnthor** [nathanreyes/v-calendar#169]
Hi there, I have a page with a calendar & a date picker.
Is it possible to use the array of highlighted dates from the calendar in my date-picker's disabled dates?

Thanks by advance

**Comment by kl3sk** [comment]
Is it what you are looking for ?

https://jsfiddle.net/klesk/av4gb9h7/

**Comment by nathanreyes** [comment]
Closing outstanding issue. Please provide a more detailed explanation/example if needed.
