### ISSUE TITLE
background theme for Popup

### ISSUE THREAD

**Issue by kishorevaishnav** [nathanreyes/v-calendar#17]
I was trying to set theme / background linear-gradient on a popup (not inline), its not working but it works only when I use `is-inline` attribute. 

I tried with the same ExStyling-3.vue example.

https://github.com/nathanreyes/v-calendar/blob/37dc4e1be4c8f72461b2a05f66228748ba0db13b/docs/components/app/examples/ExStyling-3.vue#L8

Guide me if I am missing something.

**Comment by nathanreyes** [comment]
Thanks for the catch. Please verify that the latest release was able to resolve your issue.
