### ISSUE TITLE
Find out current displayed month

### ISSUE THREAD

**Issue by nass600** [nathanreyes/v-calendar#170]
Hi all,

I am trying to perform some operation when the Calendar is displayed on the event `popover-will-appear` based on the rendered month but no page object is returned in this event.

How can I figure this information out? Would be interesting to return the page object?

Currently the only way I find out to work around my need is accessing thru a `ref` and all the chain of components that comprises the plugin this way:

    popoverWillAppear () {
        // nothing coming from the event popover-will-appear
        let month = this.$refs.picker.$children[0].$children[0].$children[0].fromPage.month;
        ...
    }

Thanks

**Comment by EricMcRay** [comment]
Hi @nass600,

You can use `from-page`prop with sync modifier for 2 way data bind so you can access it any time or on any event.

```js
<v-date-picker 
  :from-page.sync="currentPage" 
  @popover-will-appear="doSomething(currentPage)" 
/>

**Comment by nass600** [comment]
Thanks @EricMcRay, that would work!
