### ISSUE TITLE
dayCellNotInMonth not working properly

### ISSUE THREAD

**Issue by rafaeltrestin** [nathanreyes/v-calendar#174]
Hello,
dayCellNotInMonth only hide "day", and events continue be available.
"pointer-events" not working.

![pointer-events](https://user-images.githubusercontent.com/21268925/42681581-6177b532-8688-11e8-883f-d65e27949ac5.PNG)

Thanks.

**Comment by octaviangrozman** [comment]
Try to use display: 'none'
It worked for me
![image](https://user-images.githubusercontent.com/33148154/44264962-db813300-a224-11e8-8428-edc4863c526d.png)
