### ISSUE TITLE
get customData in day slot

### ISSUE THREAD

**Issue by ciro-webcom** [nathanreyes/v-calendar#177]
Hello,
Is it possible to access customData within the day-content slot? Or at least get the attribute(s) of the current day? I have to show some additional information in the day-content slot.

Thank you and really nice work :-)

**Comment by kl3sk** [comment]
Is this what you are looking for ?

https://jsfiddle.net/klesk/mg4akx8n/

**Comment by ggirodda** [comment]
Hello, thank you for answering me. No, I talk about the customData Object wich we can pass in the attributes prop:
https://docs.vcalendar.io/attributes.html#using-customdata

**Comment by kl3sk** [comment]
Hello,
Be more explicit I don't understand what is your purpose between ``customData`` and ``day-content slot``

In the day content slot you can show more text, as i did in the fiddle. Maybe it is in the popover you want it ?

An other clue could be that:  https://docs.vcalendar.io/data.html#step-1-converting-data-to-attributes

Could you provide a fiddle event if this is not working 100% as expected ? Just to understand your problem.

**Comment by kl3sk** [comment]
An other solution may be [that](https://docs.vcalendar.io/popovers.html#slots)

**Comment by nathanreyes** [comment]
@ggirodda The `attributes` array is passed in as a parameter to your `day-content` slot, so you should be able to get to your `customData` object.

**Comment by riseoflex88** [comment]
The day-content slot code as proposed above doesn't trigger the hover / click actions. As I understand it from here: https://github.com/nathanreyes/v-calendar/issues/297 "passing dayEvents to the scoped slot and then using v-on="dayEvents" works", however, I can't get that to work. 

Just wondering if you managed to get that working on your code and if so, can you post an example?

**Comment by dima-horror** [comment]
> The day-content slot code as proposed above doesn't trigger the hover / click actions. As I understand it from here: #297 "passing dayEvents to the scoped slot and then using v-on="dayEvents" works", however, I can't get that to work.
> 
> Just wondering if you managed to get that working on your code and if so, can you post an example?

Try [pass dayEvents  parameter](https://github.com/nathanreyes/v-calendar/issues/495#issuecomment-592047614). It's works for me.

```
<v-calendar>
  <template v-slot:day-content="{ day, dayEvents }">
    <div v-on="dayEvents">
      <span>{{day.label}}
      <span> blah blah blah </span>
    </div>
  </template>
</v-calendar>
```

**Comment by nathanreyes** [comment]
Closing outstanding issue. The `day-content` slot provides an `attributes` and `attributesMap` to access the attributes only assigned for that particular day.
https://vcalendar.io/api/v2.0/calendar.html#day-content
