### ISSUE TITLE
Doesn't work in IE11 - The package should be ES5

### ISSUE THREAD

**Issue by francoislevesque** [nathanreyes/v-calendar#18]
It appears this package is ES6 code which isn't compatible IE 11 and other older browsers.
Can you distribute a compiled ES5 version instead of ES6?

**Comment by nathanreyes** [comment]
I don't really have a way to test IE11 at the moment as I don't have access to a Windows PC, but the project uses Babel to transpile ES6 into ES5 so I don't understand why that would be the cause. Does the [website](https://vcalendar.netlify.com) not load at all?

**Comment by francoislevesque** [comment]
The website doesn't load in IE11 because of a syntax error. As you can see, there is ES6 syntax in the console. To use this package (which I really love by the way 💯), I must recompile it with babel.

![capture](https://user-images.githubusercontent.com/14022409/33437623-8b60207e-d5b6-11e7-9821-a78bb85fc645.PNG)

However, even with a forced babel compilation, the events don't show up on the calendar (it does in all other browsers). Maybe a CSS error since IE11 doesn't support the full flexbox standart.

**Comment by kl3sk** [comment]
To bump @francoislevesque answer, i just test my working app in Firefox under IE11

@See screen

![image](https://user-images.githubusercontent.com/2953145/34947119-7274b88c-fa09-11e7-846d-e3a7806c2a0e.png)

**Comment by mariusj** [comment]
Just add the Array.prototype.find polyfill and it will work in IE11.
You can include this script before loading v-calendar:
`<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=Array.prototype.find" />`

**Comment by kl3sk** [comment]
@mariusj Babel didn't transpile it ?

**Comment by nathanreyes** [comment]
`Array.prototype.find` is not transpiled so it has to be polyfilled for older browsers (IE11). Rather than polyfill it and punish modern browsers I think I will just put an explanation for developers on how to polyfill it so that they can choose which platforms to support.

**Comment by kl3sk** [comment]
@nathanreyes Why not implemented it, if browser doesn't support it ?

**Comment by nathanreyes** [comment]
I could choose to support it, but it would require unnecessary code for all browsers, including modern ones that can support `Array.prototype.find` natively.

It is more of a matter of whose decision should it be to punish newer browsers. I could include it (and any polyfills needed in the future) and make the decision for everyone, or allow the developer to make that decision to support older browsers. It is a simple script import.

I don't know, I asked this question in the Vue forums and got some feedback that it would be best left to the developer. Also, I would like to keep the package as minimal as possible.

I am open to other opinions though.

**Comment by francoislevesque** [comment]
Letting the developper make the decision concerning the polyfills is indeed the way to go. The package is correctly distributed in ES5 in `lib`. I was getting an error in webpack because I was directly importing `v-calendar/src/utils/helpers` in one of my files.

Thus, I personally consider this issue closed.

**Comment by nathanreyes** [comment]
I agree. Like I said before I think I will just make sure to carefully document the required polyfill(s) and procedures for requiring them.
