### ISSUE TITLE
v-date-picker was duplicated with key of vuetify

### ISSUE THREAD

**Issue by htran78** [nathanreyes/v-calendar#187]
I am going to use feature range date of **v-date-picker**. But I also use v-date-picker of **veutify**. It was be conflict by **v-date-picker** key
I think **v-date-picker** should be export as a independent component like **v-calendar.**

**Comment by maxdobeck** [comment]
FYI I ran into this as well.  Component names are identical.

Vuetify --->  https://vuetifyjs.com/en/components/date-pickers
V-Calendar ---> https://docs.vcalendar.io/#date-picker

**Comment by nathanreyes** [comment]
If you scroll to the bottom of the [readme](https://github.com/nathanreyes/v-calendar/blob/master/README.md), there is the documentation for `componentPrefix`.

**Comment by htran78** [comment]
Hi @maxdobeck , @nathanreyes 
V-Calendar - 0.9.7
Vue - 2.5.17

After all, i comeback to use v-calendar, but i got stuck and i don't know why.
If i create new Vue app, install the packages (vuetify, v-calendar), import and use them into project, it works well as expected. I logged v-calendar in console and can see components of it.

But with my project current, I installed v-calendar, imported and logged it. Nothing is appear in my console. Do you have any idea for my issue?

I am very appreciated if  i got idea from you. Thank you so much!
Hanh

**Comment by parvizhojiev** [comment]
How to do it with nuxtjs?
