### ISSUE TITLE
Add new prop avaliable-dates

### ISSUE THREAD

**Issue by adrianoresende** [nathanreyes/v-calendar#19]
To facilitate the development, it would be interesting to have a new option to mark the available date that disables the rest.

`<v-date-picker is-inline ... :avaliable-dates="{ start: today, end: oneMonth" />`

And set `max-page` and `min-page` too.

**Comment by nathanreyes** [comment]
Good idea.

**Comment by nathanreyes** [comment]
Thanks for the kind words. I was actually planning on pushing it out today, but I would like to do some more testing. It will most likely be some time early next week.
