### ISSUE TITLE
FeatureRequest: MonthPicker and YearPicker

### ISSUE THREAD

**Issue by gigioSouza** [nathanreyes/v-calendar#190]
I'm enjoying working with your components. 
I'd just suggest a MonthPicker and a YearPicker

**Comment by highstone** [comment]
+1 see also #90

**Comment by vukadinFE** [comment]
Hi @nathanreyes 
Are those features implemented yet?
Thanks for awesome plugin.

**Comment by paolog22** [comment]
+1 for this good idea

**Comment by ajithsimon** [comment]
@nathanreyes please update it..
thanks for the plugin BTW. :)

**Comment by pengguna21** [comment]
hi @nathanreyes , i enjoyed with your component bro.
so please update that feature. thanks for your plugin

**Comment by nathanreyes** [comment]
Closing this outstanding issue. Please reference #90 for further updates.
