### ISSUE TITLE
Feature Request: show calendar of more than 2 months (pages)

### ISSUE THREAD

**Issue by topvis** [nathanreyes/v-calendar#195]
My application needs to show all 12 months of a year like the screenshot below. Current I use v-for to render 12 `v-calendar` components:
```Javascript
<v-calendar
  v-for="m in 12"
  :key="m"
  :from-page="{month: m, year: 2018}"
  :attributes="attr(m)">
</v-calendar>
```
It works. The problem is that it takes about **one second** to render the 12 components every time the page is updated. Is it possible to add a feature so that `v-calendar` can show multiple months (pages)? currently one `v-calendar` can show 1 or 2 months (is-double-paned). I'm not sure but I assume rendering one `v-calendar` of 12 months would be more efficient than rendering 12 `v-calendar` of 1 month?

Any advice will be appreciated.

![image](https://user-images.githubusercontent.com/5996531/45918949-81474380-be5c-11e8-9939-b76a876a1202.png)

**Comment by nathanreyes** [comment]
Apologies for the late reply but this has been addressed for a while. Please use the `rows` and `columns` props.
https://vcalendar.io/layouts.html#multiple-rows-columns

**Comment by inyutina** [comment]
> Apologies for the late reply but this has been addressed for a while. Please use the `rows` and `columns` props. https://vcalendar.io/layouts.html#multiple-rows-columns

Hello, can you please tell me hoe can I disable the popover of the 2nd row opening? I only need the popover opening when clicking on the first row in the date picker.
