### ISSUE TITLE
Better UI for year month/year picker?

### ISSUE THREAD

**Issue by HapLifeMan** [nathanreyes/v-calendar#2]
Thank you for the month/year picker ❤️

Can you implement a better UI experience to switch between them?
Like [Semantic-UI Calendar](https://github.com/mdehoog/Semantic-UI-Calendar) would be lovely 😊

When we click on the month we can have something like this:
<img width="224" alt="capture d ecran 2017-11-03 a 10 20 02" src="https://user-images.githubusercontent.com/1854141/32366949-a769182a-c080-11e7-84f8-5b5de7c1ceec.png">
 
And on the year:
<img width="219" alt="capture d ecran 2017-11-03 a 10 20 13" src="https://user-images.githubusercontent.com/1854141/32366965-b904019e-c080-11e7-88c2-3e78b2057864.png">

And when we click we go deeper to date (and maybe hour/minute picker?) 🙂

**Comment by nathanreyes** [comment]
That layout does look nice and I think it would offer a better user experience as well. Appreciate the input as I'm not that familiar with Semantic. I'll see what I can whip up.

**Comment by nathanreyes** [comment]
The latest release is the first crack at this. It is semantic inspired with some additional functionality built in such as previewing attributes at the month level. I'm going to ponder over hour/minute picker integration, but that should probably be discussed on a different issue.
