### ISSUE TITLE
set date range on date select

### ISSUE THREAD

**Issue by Cre3z** [nathanreyes/v-calendar#204]
Hey Guys, 

Thanks for the awesome plugin, it really works great. Is there a way to set a range of dates once a user has selected the date. 

The range mode needs you to select an end date too, I have a specific length I need to set. So if a user clicks Monday the calendar needs to stay open and highlight up to Friday. 

Or maybe even highlight the days on hover? Could also be an option. 

Anyway of achieveing this? TIA

**Comment by mrcat323** [comment]
Hi @Cre3z ,
It's possible. Create a computed method (for *attributes* attribute) and in `dates` object set today's date by default. Place it in array, and as second element of an array create a date and set it 5 days forward by that date. Something like:
```JAVASCRIPT
dates: [
    new Date (), new Date(dates[0].getFullYear() + '/' + (dates[0].getMonth()+1) + '/' + (Number(dates[0].getDate()) + 5))
]
```
It will perfectly work! :muscle: 
**P.S (*it was just an example, you can do the same with another way, but with computed stuff*)**
