### ISSUE TITLE
How do you style v-date-picker's selected day?

### ISSUE THREAD

**Issue by muxcmux** [nathanreyes/v-calendar#210]
It might be just me, but I just spent about an hour trying to figure out how to style the highlighted day. The best I could do is change the tint color, but I couldn't find anything in the docs that says how you can apply styles to it, e.g. remove border radius, adjust width and height, etc. etc. Can anyone point me in the right direction?

**Comment by mrcat323** [comment]
Hi @muxcmux 
If you wanna change the highlighted days in `mode="single"` which means single mode, check this gist out https://gist.github.com/3e222277bcb14f1b7786b52871833ff9 *(this stuff also works with multiple mode)*
But if you wanna change highlighted days in `mode="range"` which is range mode, you've to change the caps' style. To do this check [THIS PR](https://github.com/nathanreyes/v-calendar/pull/207) and [THIS GIST OUT](https://gist.github.com/mrcat323/789be8082ae3e88dba7daa8e95051a74) **(THE GIST IS THE EXAMPLE OF USING THE CODE FROM PR)**

**Comment by mrcat323** [comment]
just let me know if everything is :ok_hand:

**Comment by muxcmux** [comment]
Hey @mrcat323 Thanks for this! I ended up using `selectAttribute` and `disabledAttribute` to make it work. Leaving this here for other people that might be looking for it:

```javascript
selectAttribute: {
  highlight: {
    backgroundColor: 'white',
    borderColor: 'red',
    borderWidth: '3px',
    borderStyle: 'solid',
    width: '2.4rem',
    height: '2.4rem',
  },
  contentStyle: {
    color: 'grey',
  }
},
disabledAttribute: {
  contentStyle({ isHovered }) {
    const config = {
      color: 'red',
      textDecoration: 'line-through',
      opacity: .4
    }
    if (isHovered) {
      config.backgroundColor = 'transparent';
      config.cursor = 'not-allowed';
    }
    return config;
  },
},
```
