### ISSUE TITLE
How to fire function on date-picker update?

### ISSUE THREAD

**Issue by warhost** [nathanreyes/v-calendar#221]
This might seem like a stupid question, but I can't seem to figure out how to fire a function when the date changes. I am using the `date-picker` as follows:

```
	<v-date-picker
		mode="range"
		v-model="selectedDate"
		show-caps>
	</v-date-picker>
```

This shows a input on my page, and when you click it, the date picker opens, when changing dates in there, the input also updates.

How can I fire one of my methods upon change?

**Comment by Arwany** [comment]
Here:

```

<v-date-picker
		mode="range"
		v-model="selectedDate"
		@input="handleInput"
		show-caps>
	</v-date-picker>

....
handleInput(val){
    	// do what you want with val
    },

```

**Comment by warhost** [comment]
Thanks!

**Comment by FutureFutureTo** [comment]
@input seems to fire on component load as well as update...is there a way to fire only on update and not initial load?
