### ISSUE TITLE
config property to disable ALL the transitions/animations?

### ISSUE THREAD

**Issue by Landen13** [nathanreyes/v-calendar#223]
Is it posible to disable all the transitions/animations? It behaves weird sometimes on not-good laptops, in Opera/Chrome etc.

**Comment by peterdicecco** [comment]
I'd also like to disable the transitions.

**Comment by nathanreyes** [comment]
Closing outstanding issue. Please use `transition` prop in newer versions to achieve this behavior.
https://vcalendar.io/api/v2.0/calendar.html#transition
