### ISSUE TITLE
The value is subtracted by one

### ISSUE THREAD

**Issue by handhikadj** [nathanreyes/v-calendar#228]
### Current behavior

I've got a problem to which get the value from the input. Vue devtool (vuex) records it properly but when I try to console.log, it shows the value of the date is subtracted by one 
e.g the input ( & vuex state) is "Wed Nov 07 2018 00:00:00 GMT+0700 (Indochina Time)" but when I console.log and output the state to the DOM, it shows "Wed Nov 06 2018 00:00:00 GMT+0700 (Indochina Time)". And by the way, how to format the date for mysql date? The docs is not well written (to me)

https://youtu.be/BtRgFpQjeU4

DOM (I/O): 
![image](https://user-images.githubusercontent.com/22522638/48965411-31693200-efef-11e8-826d-6b0f6e7dacd1.png)

console.log:
![image](https://user-images.githubusercontent.com/22522638/48965420-4f369700-efef-11e8-84ab-a9c124dd637e.png)

state (vue devtool):
![image](https://user-images.githubusercontent.com/22522638/48965430-72614680-efef-11e8-83d0-e07f98d9f9ec.png)

### Expected behavior

Proper output

### Code
template: https://pastebin.com/JDgcbpwp
store (vuex): https://pastebin.com/1UiBE5x0

**Comment by alexgalkin1994** [comment]
Same issue.

**Comment by irtzamazhar** [comment]
Facing same issue any solution of this.

**Comment by handhikadj** [comment]
I have cross-checked this again and seems the problem's solved. thanks
