### ISSUE TITLE
Scoped CSS not passed down to named slots

### ISSUE THREAD

**Issue by xavianaxw** [nathanreyes/v-calendar#230]
I'm facing an issue when trying to set up a custom slot for `day-content`. Here's my markup.

```
<v-date-picker
  v-model='selectedDate'
  mode='range'
  :disabled-dates='disabledDates'
  is-required
  is-inline
  is-double-paned
></v-date-picker>
```

Note: I've stripped out all the styles in this case.

With my original markup, I get my ideal outcome with the following:

![screen shot 2018-11-28 at 5 10 17 pm](https://user-images.githubusercontent.com/8082158/49132427-83cc8a80-f330-11e8-91ac-e9e025595072.png)

Now when I add a custom slot `day-content` so I can add additional markup to my `dayCell` to cross out the disabled dates.

```
<div slot="day-content" slot-scope="{ day, attributes, contentStyle }" class="c-day-content" :style='contentStyle' >
  <div>{{"{{ day.label }}"}}</div>
</div>
```

to my `v-date-picker`, I get the following.

![screen shot 2018-11-28 at 5 11 18 pm](https://user-images.githubusercontent.com/8082158/49132454-a363b300-f330-11e8-89c3-acfcb9bed823.png)

I've had a look at the HTML that gets rendered and noticed that for my original markup, it has an additional `data-v-3db80f80` attribute on `c-day-content`. Here's a screenshot of my rendered HTML.

![screen shot 2018-11-28 at 5 12 29 pm](https://user-images.githubusercontent.com/8082158/49132510-d148f780-f330-11e8-94ed-ad5127743f09.png)

and the one with the custom slot which omits this additional data attribute.

![screen shot 2018-11-28 at 5 12 10 pm](https://user-images.githubusercontent.com/8082158/49132520-d9089c00-f330-11e8-89c1-4a345e0fbcc8.png)

I hope someone can point me in the right direction for this.

CC: @EricMcRay (because you made the PR for custom `day-content` slot) and @nathanreyes

**Comment by peda** [comment]
When you add the deep selector (`>>>` or `/deep/`) to your CSS selector like `.parent-class >>> .child-component-class` then (at least with the standard Vue and Webpack build, the parent selector will be scoped but anything after the deep selector won't be scoped)

**Comment by xavianaxw** [comment]
@peda i don't have any custom css and i'm using `v-calendar`'s css styles only. And looking at `CalendarDay.vue` there are no deep nesting involved :\
