### ISSUE TITLE
Clicking outside the component while range select is not complete does not cancel the selection

### ISSUE THREAD

**Issue by BogdanBartis** [nathanreyes/v-calendar#231]
The issue I'm facing is pretty simple. I have an inline date picker configured like this:
```
<v-date-picker 
    mode="range"                 
    v-model="selected"                                 
    is-inline                
    show-caps 
    :max-date="new Date()"                 
    :show-day-popover="false"                
></v-date-picker>
```
I start to select a range, but before I select the end date for that range, I click outside the calendar. I would expect the range selection to be reset as the calendar lost the focus. However the range selection is still active and when I return the cursor to the calendar it is still waiting for me to select the end of the range.

Here's a fiddle showcasing the problem: http://jsfiddle.net/badger9000/eywraw8t/484390

The example there is a basic use case I'm trying to accomplish using the calendar, which is to allow the user to click a button that sends a custom range to the calendar. 

As you can see from the demo, if the user starts selecting the range and then decides to press the button, it can't because while the range selection is active the calendar ignores any value changes to the `selected` field. Once the selection is finished, it accepts the custom range just fine.

![DEMO](https://i.imgur.com/9e9mQCL.gif)

I've searched the documentation for a solution, or at least a way to programmatically tell the component to cancel the selection process, but was not able to find one. Setting the selected value to `null` is ignored just as much.

Thanks

**Comment by geronimoaris** [comment]
Did you manange to sort this out?
