### ISSUE TITLE
Cannot format date tp DD-MM-YYYY or YYYY-MM-DD after picking date?

### ISSUE THREAD

**Issue by tim-hub** [nathanreyes/v-calendar#234]
## Formating place holder is OK
![screenshot from 2018-12-10 09-31-33](https://user-images.githubusercontent.com/2884320/49702590-a6c73a80-fc5e-11e8-825f-d85632774b24.png)

## But after picking is
![screenshot from 2018-12-10 09-32-57](https://user-images.githubusercontent.com/2884320/49702593-b21a6600-fc5e-11e8-8b65-b851b166ea2f.png) `MM-DD-YYYY`

My config file is,
```
the_formats: {
        title: 'MMMM YYYY',
        weekdays: 'W',
        navMonths: 'MMM',
        input: ['L', 'DD-MM-YYYY'], // Only for `v-date-picker`
        dayPopover: ['DD-MM-YYYY'], // Only for `v-date-picker`,
        data: ['DD-MM-YYYY'] // For attribute dates
      }
```

and my template
```
<div ><v-date-picker   :input-props='{ class: "input", placeholder: "DD-MM-YYYY - DD-MM-YYYY", readonly: true }' mode='range' v-model='selectedDate' show-caps>></v-date-picker> </div>
```

Is it `MM-DD-YYYY` hard coded somewhere in source codes?

**Comment by nathanreyes** [comment]
The first format in the array is used to display, while all are used to parse (in the order they are listed).

In your case, it is using the `L` format to display, which is localized. You can switch the order and use `['DD-MM-YYYY', 'L']` in order to display using the format you want.

Also, if you leave out the placeholder when configuring `input-props`, it should display according to the proper format as well.

**Comment by tim-hub** [comment]
I did v-bind for placeholder to force placeholder display date in the same format of last input.

Anyway, thank you very much.

**Comment by MohanishVsh** [comment]
I want to display the date in YYYY-MM-DD format, i tried doing what you said but the dates are still visible in DD-MM-YYYY format

Code:
<v-date-picker
          :popover="{ visibility: 'click' }"
          :formats="formats"
          v-model="date"
          mode="multiple"
          :value="null"
          color="blue"
          :attributes="attrs"
        >
         </v-date-picker>


formats: {
        title: 'MMMM YYYY',
        weekdays: 'W',
        navMonths: 'MMM',
        input: ['YYYY-MM-DD','L'], // Only for `v-date-picker`
        dayPopover: ['YYYY-MM-DD'], // Only for `v-date-picker`,
        data: ['YYYY-MM-DD'] // For attribute dates
      }
![Screenshot from 2019-07-12 19-12-09](https://user-images.githubusercontent.com/51692284/61132470-0fb6af80-a4d9-11e9-81a1-c3235bb9c858.png)
