### ISSUE TITLE
A warning on the console when using the date-picker in-line option.

### ISSUE THREAD

**Issue by ktt9117** [nathanreyes/v-calendar#235]
This is my implementation.
`<v-date-picker
    mode='single'
    is-inline=true
    v-model='selectedDay'
    @dayclick='dayClicked'>
    </v-date-picker>`

Everything works fine, but I got these warning 
![screen shot 2018-12-11 at 1 24 07 pm](https://user-images.githubusercontent.com/5284987/49778382-444a6900-fd48-11e8-97c9-d272bfdaf1f6.png)

Do you mind if I just ignore it or what action should I take?

**Comment by alexgalkin1994** [comment]
You could try to use "is-inline".

**Comment by ktt9117** [comment]
@alexgalkin1994 Thanks. no more appears warn logs.

**Comment by ktt9117** [comment]
@kl3sk You do not need to enter a value (="true") but just type an attribute (is-inline).

**Comment by kl3sk** [comment]
I totally agree but you wrote `is-inline=true` any way it seem resolved, you could close this issue isn't it ?

**Comment by ktt9117** [comment]
@kl3sk I did not know if I could close the issue. Now that I know, I will close the issue. :)
