### ISSUE TITLE
12 months layout

### ISSUE THREAD

**Issue by joannesalfa** [nathanreyes/v-calendar#238]
Is possible to make look like this?

![alt text](https://i.imgur.com/HfzCukY.png)

**Comment by nathanreyes** [comment]
Currently it is but it is not recommended. It would require creating multiple instances of `v-calendar` in your own layout and synchronizing the navigation for each one. I'm currently completing a rewrite in order to accomplish this in a performant way with custom `rows` and `columns` prop.

**Comment by joannesalfa** [comment]
Thanks for your answer, I was wondering too about creating multiple instances of 'v-calendar'. Custom rows and columns prop seems nice idea.

**Comment by Georgian** [comment]
Amazing component. Looking forward to this "yearly" feature. :-)

**Comment by vesper8** [comment]
looking forward to your new and improved version very much @nathanreyes !

**Comment by nikwins** [comment]
Really need this feature. Hope to see updates on this soon! :)

**Comment by nathanreyes** [comment]
This is on the `next` branch but I'm going to go ahead and close it now.
