### ISSUE TITLE
Range all selected

### ISSUE THREAD

**Issue by sigjak** [nathanreyes/v-calendar#242]
Congratulations on a very nice calendar/datepicker and excellent documentation. 
A new instance of datepicker  (range) with selected dates empty shows everything selected with NaN appearing on hover. Is this a bug or am I at fault? Having start and end days fixes the issue but I would like to start with nothing selected.

**Comment by highstone** [comment]
Just noticed this behavior as well. Did you manage to find a solution for this?

**Comment by nathanreyes** [comment]
The fix for this bug (see #254) has been committed. Just waiting to get merged into the main branch.
