### ISSUE TITLE
Change day label

### ISSUE THREAD

**Issue by ggirodda** [nathanreyes/v-calendar#25]
Hello,
Thank you for your work, I really like this plugin.  I read the documentation and look at your code, but I'm not really familiar with Vue.js yet. Is it possible to chenge dynamically the day label in the current showed days? I have to put a price in the bottom of each day. I see that you create a object `dayInfo` in CalendarWeeks.vue, and push it in `weeks` array, but I don't know how to access this array from within the parent template, maybe it's not possible?

Thank you

**Comment by ggirodda** [comment]
Ok, I just put a emit method at the bottom of the computed weeks function that callback me the weeks array. Can anyone tell me if this is the correct way?

Thank you

**Comment by nathanreyes** [comment]
_Currently_ it is not possible to do what you are asking. If you are forking the project, the best way to achieve this now is to look at the CalendarDay component, specifically here...
```html
  <!-- Content layer -->
  <div class='c-day-layer c-day-box-center-center'>
    <div
      class='c-day-content'
      :style='contentStyle_'
      @touchstart.passive='touchstart'
      @touchend.passive='touchend'
      @click='click($event)'
      @mouseenter='mouseenter'
      @mouseleave='mouseleave'>
      {{ label }} <!--This is where you want to put in your custom content-->
    </div>
  </div>
```
Adding support for custom content slots is something I am currently investigating. Let me know if this is really what you are looking for.

**Comment by ggirodda** [comment]
Thank you for the answer. I read something about passing slots from parent to children, but I think that I cannot do that in more than one level relationsheep. For now I just create a $emit in CalendarListener.vue:
`
computed: {
    weeks() {
      ...
      this.$emit('daysLoad', weeks);
      return weeks;
    }
}
`
And get the array in the on:daysLoad listener and edit the days label in a parent template method

**Comment by ggirodda** [comment]
Finally I added a prop 'rates' wich is passed through all child templates until CalendarWeeks, then in the weeks day loop I retrive the current day value from the rates prop and put it in the day object

**Comment by nathanreyes** [comment]
Glad you were able to find a solution. I'll try and notify you when/if there becomes a better way to solve this problem in the future.

**Comment by riseoflex88** [comment]
Is there any update on whether there is a better solution for this? Or whether the OP's solution works well enough?

**Comment by cchacholiades** [comment]
@nathanreyes thank you for your work! I'd also like to do something similar to this. Is there maybe an updated way to achieve this?
