### ISSUE TITLE
Edge case that hangs the browser on range select: null range, min-date, max-date, is-double-paned

### ISSUE THREAD

**Issue by xvaara** [nathanreyes/v-calendar#254]
So I have a date-picker like:
```
<v-date-picker
	v-model="range"
	mode="range"
	min-date="2019-01-01"
	max-date="2019-01-31"
	is-double-paned
	is-inline
>
```
and range is null or {start: null, end: null} (latter causes also weird rendering)
When I select a range, the browser hangs. Latest chrome. I think there is a loop that doesn't exit.

codepen: https://codepen.io/anon/pen/WPGpgL

**Comment by Georgeek** [comment]
any updates?
"v-calendar": "^0.9.7",
