### ISSUE TITLE
Date Range too slow

### ISSUE THREAD

**Issue by bocanhcam** [nathanreyes/v-calendar#267]
This package seems very nice but I think it's too slow.

I used the date range. I just want to ask why it is and may we have a solution for that.

The animations and response time make me feel like working with server and waiting for the server to response something. Not like just working with javascript.

Hope you can do something to make it better.

Good work!

**Comment by wemod123** [comment]
Same Feeling, 

Had anyone dive into the source code to see what's the root-reason of the slow response?

Otherwise this nice components no possible to utilized in large-scale and modern web based apps.

**Comment by nathanreyes** [comment]
It is simply transition animations that are used for the date range. I decided a few months ago to remove all selection animations and that will come in the next release. Hoping to get that out as early as sometime next week.

You can check the `dev` branch for new changes coming. It is focused on some pretty big changes, including responsive multi-row and column layouts and performance improvements.

**Comment by bocanhcam** [comment]
@nathanreyes Very happy to hear that. I can't wait.
