### ISSUE TITLE
Sass in components

### ISSUE THREAD

**Issue by golgote** [nathanreyes/v-calendar#268]
Hi, your component looks great, but it will unfortunately be unusable by people like us who do not deploy code the same way as you. The problem is mostly having sass code in your components because Sass is supposed to be compiled and we use libsass to do so directly from the server. If we have to scan each of your .vue files for sass code, this cannot work. I can understand why some people would put css in their component, although I think this is bad for optimization, but Sass doesn't seem to belong here since it is a programming language on its own. So it would be more manageable for us to have sass code in the styles/ directory along with vars.scss and mixins.scss.

**Comment by nathanreyes** [comment]
Yeah, I have come to dislike the headaches with SASS and I'm probably going to remove it.

I'm curious...for your environment, would PostCSS be a deal-breaker? I'm assuming not, since I believe Vue depends on it internally I think for auto-prefixing. Could be wrong about that though.

Anyways, all I really would like to have is nesting and variables, which I could probably pull off with PostCSS.

**Comment by golgote** [comment]
We use libsass and an on-demand compiler/cache directly in nginx for our own scss files, but we will use the generated css file from your component and try to figure out how to style the component with the attributes instead, as described here : https://docs.vcalendar.io/datepicker.html#customize-attributes

Usually, I don't like to mix code and styles (firstly because it is done by different people in our team) but it looks like it is the way to go with v-calendar. I favor separation of concerns.

For me, the more dependencies you add, the more complex it becomes and the less people can use it. PostCSS would be yet another dependency.

Thank you for this component, I think it is the best calendar and datepicker for Vue that I have seen.
