### ISSUE TITLE
Typed dates are not being parsed correctly

### ISSUE THREAD

**Issue by unikitty37** [nathanreyes/v-calendar#272]
When I set up a date picker like this with v-calendar 0.97:
```html
        <v-date-picker
          mode="range"
          v-model="eventDates"
          :formats="dateFormats"
          :input-props="{ class: 'input', name: 'event_dates' }"
        ></v-date-picker>
```

with the following set in `data`:
```js
        dateFormats: {
          input: ['YYYY-MM-DD'],
          data: ['YYYY-MM-DD'],
        },
```

the input field displays the date range as `2019-03-20 - 2019-03-21`, which is correct. I can change the date range with the mouse as expected.

However, if I try to type a date range, it seems to get misparsed. For example, if I enter `2019-03-10 - 2019-03-12` the date range is set to `2001-03-01 - 2019-01-01`, which is not even vaguely correct!

Have I misconfigured this (likely) or run into a bug?

(I'm also have trouble testing the date picker with Capybara as part of my system tests, as the watcher on `eventDates` doesn't seem to get called after executing `fill_in 'event_dates', with: '2019-03-20 - 2019-03-21'`. Is there an example Capybara test somewhere that I can crib from?)

**Comment by Eibx** [comment]
I think the issue here is that [dash is hardcoded to be used as a range dates seperator](https://github.com/nathanreyes/v-calendar/blob/master/src/utils/pickerProfiles.js#L113).

This breaks when date formats contains a dash.

Would it be possible to make a option to either change this separator or add an option to change pickerProfile for your own custom one?

**Comment by unikitty37** [comment]
I would be happy with requiring whitespace either side of the range separator when hyphens are used in the date:

`2019-03-20-2019-03-21` — not valid  
`2019-03-20 - 2019-03-21` — valid

Not sure how easy that is, though — allowing the caller to change the separator might be a quicker fix.

`yyyy-mm-dd` is valid under ISO 8601, so it should probably be supported 😉
