### ISSUE TITLE
Unnecessary extra tap for date selection on iPhone

### ISSUE THREAD

**Issue by askochypets** [nathanreyes/v-calendar#278]
Here is a fiddle example of that issue:
https://jsfiddle.net/dm6tufp8/4/

On the desktop version and Android devices, it works as expected.
Unfortunately, it doesn't work on iPhone devices.

I tried to use "update-on-input" attribute, but it didn't help.

Steps to reproduce:
- click on the first date
- click on end date
Expected:
 date rage selected
Actually: 
 Visually date range is selected marked by the line, but the output dates are not updated.
 You need to extra tap on the end date to confirm selected date rage.
 
I don't know why, but an example on the [web site](https://vcalendar.netlify.com/) does work well on iPhone.

Thanks!

**Comment by PhantasWeng** [comment]
Same here.
can we custom touchstart event?

**Comment by askochypets** [comment]
I found that it's work well under iOS version 12.2, maybe it is an iOS issue in v12.1

**Comment by nathanreyes** [comment]
Yeah I'm actively looking into this. Should get fixed in the next beta for v1.

**Comment by PhantasWeng** [comment]
![image](https://user-images.githubusercontent.com/5707062/56010827-c9a25200-5d17-11e9-8344-b5ceaf87bbd6.png)

![image](https://user-images.githubusercontent.com/5707062/56010841-d626aa80-5d17-11e9-80e0-76e2f651d54b.png)

@askochypets This is what I do to reach goal achieved.

**Comment by vk2r** [comment]
> Yeah I'm actively looking into this. Should get fixed in the next beta for v1.
Any possibility to make this fix for the stable version (0.9.7)?
Apparently, the beta version changes many things internally.

**Comment by vk2r** [comment]
@nathanreyes I'm sorry.
Right now, I'm using your calendar plugin for a project and unfortunately I found this bug in the IOS browsers. I've been reviewing the code you've modified to solve the problem, however, emulating it in the old version has taken me longer than estimated.

Do you have any advice to solve this problem ?

**Comment by nathanreyes** [comment]
As far as I can tell, this shouldn't be an issue anymore as of the Beta 6, at least on my test devices. I'll close this but someone please comment if it hasn't been fixed on their mobile device.

**Comment by ademyalcin27** [comment]
it's bug still continue at iphone 7, do you have any advice for this ?

**Comment by ademyalcin27** [comment]
> As far as I can tell, this shouldn't be an issue anymore as of the Beta 6, at least on my test devices. I'll close this but someone please comment if it hasn't been fixed on their mobile device.

we came cross this bug, it's Iphone 6S safari browser. Could you help me

**Comment by KDPANDYA** [comment]
I am also facing this issue in iPad, anyone have suggestions???
