### ISSUE TITLE
Duplicate keys detected: 'T'

### ISSUE THREAD

**Issue by octaviangrozman** [nathanreyes/v-calendar#28]
Hello,
I am getting a bunch of warnings  'Duplicate keys detected: 'T'. This may cause an update error.'  when trying to render v-calendar.
![image](https://user-images.githubusercontent.com/33148154/34074506-067fc4ce-e2b1-11e7-8713-62dc7d584881.png)

![image](https://user-images.githubusercontent.com/33148154/34074481-4b359900-e2b0-11e7-90ea-ce691568591b.png)

I am wrapping it with NoSSR, because the app is rendered on server. And registering v-calendar component globally in the beforeMount hook

![image](https://user-images.githubusercontent.com/33148154/34074492-9903edf8-e2b0-11e7-85c7-e4762a51eb52.png)

May be I should not register it globally in beforeMount hook and import directly the calendar?
Thank you.

**Comment by nathanreyes** [comment]
Honestly, it may be a while until I can properly test for server rendered environments. Please feel free to provide any input or testing you can, but until then I'll file this as 'help-wanted'.

My apologies...just want to be straight-forward about it until I can investigate what is required for components in general to make them compatible with server rendered apps.

**Comment by Gannon001** [comment]
Hi,
I found the problem.

Line 97-98 in CalendarPane. 
Key if dupliquer if two day start with same letter.

**Comment by nathanreyes** [comment]
Oh ok. I will make a note to use the weekday position as the key instead of its label. Thanks for the input.

**Comment by wolflingorg** [comment]
Have the same issue. Looking forward to fixing.
