### ISSUE TITLE
Update just one format.

### ISSUE THREAD

**Issue by chopfitzroy** [nathanreyes/v-calendar#282]
Currently I want to update the `input` format to `DD/MM/YYYY` but nothing else, so I tried:

```js
Vue.use(VCalendar, {
    formats: {
        input: ['DD/MM/YYYY'],
      }
});
```

This caused all manner of issues so I had to update it to:

```js
Vue.use(VCalendar, {
    formats: {
        title: 'MMMM YYYY',
        weekdays: 'W',
        navMonths: 'MMM',
        input: ['DD/MM/YYYY'],
        dayPopover: 'L',
        data: ['L', 'YYYY-MM-DD', 'YYYY/MM/DD']
      }
});
```

I was wondering it it would be possible to merge my config over the default and save all the boiler plate.

Otherwise is there someway I can access the default and do this manually something like:

```js
Vue.use(VCalendar, {
    formats: Object.assign({}, VCalendar.formats, {
        input: ['DD/MM/YYYY'],
      })
});
```

Cheers!

**Comment by nathanreyes** [comment]
Yeah for the beta defaults are deep merged, so this will definitely be possible.

If you'd like to try it out, make sure to rename `formats` to `masks`. I'll leave this issue open until I can confirm.

**Comment by nathanreyes** [comment]
`masks` does merge correctly.
