### ISSUE TITLE
min and max dates don't prevent dates from being selected

### ISSUE THREAD

**Issue by lukaVarga** [nathanreyes/v-calendar#289]
If min date is set to today, I cannot move back to March 2019 (using the arrow functions or the menu), but I can still select eg. April 5th. Likewise, if max date is set to today, I cannot move to May 2019, but I can still click and select eg. April 25th.

I would usually expect dates that are earlier than the min date (or later than the max date) to not be clickable, to not receive hover state, etc., and I would usually expect them to be greyed out to signal that they are disabled and cannot be clicked.

**Comment by nathanreyes** [comment]
This should be fixed as of `1.0.0-beta.8`
