### ISSUE TITLE
disabled-dates not working in 1.0.0.beta4

### ISSUE THREAD

**Issue by sigjak** [nathanreyes/v-calendar#293]
I am unable to get disabled-dates working for date-picker in 1.0.0.beta.4 using the example given in Disable Dates & Patterns. Is this a bug?

Regards

Sig

**Comment by AruXc** [comment]
same problem in 0.9.7

**Comment by sigjak** [comment]
I was referring to date-picker not calendar. disabled-dates works fine in 0.97 with date-picker.
Sig

**Comment by nathanreyes** [comment]
Now that beta 5 is out, this is next on my list. It is certainly a bug, and I'm revisiting if I'd like to make `disabled-dates` part of `v-calendar` itself instead of just leave it with `v-date-picker`.

Any thoughts are welcome on this.

**Comment by sigjak** [comment]
Thanks for the answer. This is the best and most flexible calendar I have come across. So, congratulations and thanks for all the work! By the way, there might be  a problem with firstDayOfWeek.
regards

sig
