### ISSUE TITLE
[Feature request] support for both "focus" and "hover" at the same time.

### ISSUE THREAD

**Issue by Rinux55** [nathanreyes/v-calendar#294]
Right now we have the possibility to set `popover-visibility` to `focus` or `hover`. I really love the hover functionality, but when I'm tabbing through input fields, the calendar should also display. 

There are ways to make this by using 'visible' and 'hidden' as properties and applying your own logic, but all of the solutions have some kind of drawback and I never got it to work properly.
This is why it would be nice to support both options at the same time.

**Comment by nathanreyes** [comment]
The `hover-focus` state is available as of `1.0.0-beta.10`.

**Comment by Rinux55** [comment]
Fantastic, thanks!
