### ISSUE TITLE
1.0.0-beta.4. custom day-content slot cannot trigger dayclick

### ISSUE THREAD

**Issue by hoobill** [nathanreyes/v-calendar#297]
Hi Nathan,
  1. when I use a custom `day-content` slot,  the dayobj cannot click. But it works on 0.9.7. Is there something wrong?
```            
<div slot="day-content"
    slot-scope="{day, attributes, contentStyle}"
    :day='day'>
  <div class='c-day-content'
    :style='contentStyle'
    v-if="day.date.getDay() !== 0 && day.date.getDay() !== 6">
    <div>{{ day.label }}</div>
  <div>{{ xx }}</div>
  </div>
  <div class='c-day-content isweekend'
    :style='contentStyle'
    v-else>
    <div>{{ day.label }}</div>
    <div>{{ xx }}</div>
  </div>
</div>
```
 please check it.

**Comment by nathanreyes** [comment]
Right. Apologies..the documentation is still a little out of date. I specifically updated [this portion](https://vcalendar.io/api/calendar.html#scoped-slots) for your refrence.

There are new properties you can use..the one you want is the `dayEvents` property. Just assign it to one of your content divs
```html
<div class="c-day-content" v-on="dayEvents">
...
</div>
```
This should add the `click` event, as well as any others needed (popover support, for example). Let me know if this works out for you.

**Comment by nikwins** [comment]
Had the same problem and can confirm passing dayEvents to the scoped slot and then using  `v-on="dayEvents"` works.

**Comment by maicWorkGithub** [comment]
```
<div class="c-day-content" v-on="dayEvents">
...
</div>

// dayEvents: {
//   click: function (e) {console.log(e)}
// }
// just get the origin dom Mouse Event...
```
does works, but how to get the events on this day? and what's the difference wth this?
```
<div class="c-day-content" @click="(e) => console.log(e)">
...
</div>
```
