### ISSUE TITLE
Logo for docs site.

### ISSUE THREAD

**Issue by nathanreyes** [nathanreyes/v-calendar#3]
I would much rather continue to work on improving the plugin rather than stumbling through Illustrator.
If anyone has the chops for a simple logo...something perhaps medium sized (like the main [Vue logo](https://vuejs.org)) as well as the favicon, I'm up for submissions. I'd recommend something with a more simple flat design using a variant of either of the two site colors (#66b3cc or #ff5050).

Proper attribution would be noted in the docs site homepage.

**Comment by HapLifeMan** [comment]
Here's my participation! I think it's a good idea to keep Vue on the logo :)

![v-calendar](https://user-images.githubusercontent.com/1854141/32799307-9c1316f6-c977-11e7-86bd-9539b50db7a7.png)

**Comment by nathanreyes** [comment]
Thanks for the contribution! I do agree that the Vue logo should probably be referenced in the design, and I like the calendar outline you have. Not sure if the colors of the Vue logo really match the style of the pink, though. Maybe the numbers could be replaced with a modified version of the "V" with a "C" shape in there as well. I'll try and sketch what I'm envisioning here. I'm going to leave this issue open for a bit, but this is a nice start.
