### ISSUE TITLE
no work in laravel 5

### ISSUE THREAD

**Issue by gitcoffee** [nathanreyes/v-calendar#30]
Hi! v-calendar no functions in laravel 5 ? :(

**Comment by nathanreyes** [comment]
I'm sorry I have never used Laravel and I'm not sure what would be required to get it to work in that kind of environment. Are all apps server rendered in Laravel?

**Comment by francoislevesque** [comment]
@gitcoffee I have no problem whatsoever with Laravel using laravel mix. Can you detail the error you are getting?

**Comment by nathanreyes** [comment]
Issue closed until an clearer explanation is provided.
