### ISSUE TITLE
Is it possible to programmatically change start and end date in range date picker?

### ISSUE THREAD

**Issue by vlada-symphony** [nathanreyes/v-calendar#301]
First of all, v-calendar is awesome!

Is it possible to customize range date picker, so that when range is selected and user clicks outside of range, the range extends (if they click left of range then start date moves to clicked date, if they click to the right of range then end date moves)?

Basically, is it possible to programmatically change start and end date? Currently what I can do is listen to @dayclick and inside set bound start and end date based on my needs (to extend range) and then re-render datepicker and it works, but it is really hacky.

**Comment by fcaivano** [comment]
Hi, could you share how you solved this?

thanks

**Comment by vlada-symphony** [comment]
@fcaivano I figured out how to do it without faking clicks and re-rendering. It goes something like this in template:

```
<v-date-picker
  ref="datepicker"
  v-model="selectedDate"
  mode="range"
  @dayclick="onDayClick"
></v-date-picker>
```

and then in `onDayClick` method something like this:

```
onDayClick({ date }) {
  const picker = this.$refs.datepicker;
  if (! picker.dragValue || !this.selectedDate) {
    return;
  }

  const { start, end } = this.selectedDate;
  if (date < start || date > end)) {
    const newStart = date < start ? date : start;
    const newEnd = date > end ? date : end;
    picker.dragValue = null;
    this.selectedDate = {
      start: newStart,
      end: newEnd,
    };
  }
},
```
