### ISSUE TITLE
Duplicate month when first load

### ISSUE THREAD

**Issue by kamontat** [nathanreyes/v-calendar#308]
![CleanShot 2019-05-05 at 23 02 38](https://user-images.githubusercontent.com/14089557/57196743-eaae3980-6f89-11e9-93b3-49db0b23edab.png)

**Comment by kamontat** [comment]
Here is my settings

```html
<v-date-picker
          color="red"
          is-dark
          is-expanded
          is-inline
          :rows="$screens({ md: 2 }, 1)"
          :columns="$screens({ md: 2 }, 1)"
          :max-date="new Date()"
          :attributes="events"
          v-model="dates"
          mode="range"
        />
```

**Comment by sigjak** [comment]
Same here. Works fine with :columns="2" but fails with $screens.... repeating first month. (vs 1.0.0.8.beta

**Comment by nathanreyes** [comment]
Not able to reproduce. Can you post what `events` is in your example?

**Comment by sigjak** [comment]
Thanks for a quick response.
With :columns="$screens({ default: 1, lg: 2 })" and a large screen program inits with two May 2019 panes (fig1)
![fig1](https://user-images.githubusercontent.com/27348716/57239064-63f56d00-701a-11e9-8f57-c42d63e360f4.PNG)

No event is fired
Upon shrinking screen one panel appears and update: fromPage and update:toPage are fired (fig2)
![fig2](https://user-images.githubusercontent.com/27348716/57239074-6b1c7b00-701a-11e9-8130-3b240499495e.PNG)

Resizing screen to large two panes appear correctly and the fromPage toPage events fire (fig3) 
![fig3](https://user-images.githubusercontent.com/27348716/57239087-7374b600-701a-11e9-97dc-2560d20eda98.PNG)

Refreshing the page now the two May panels reappear (as in fig1)  and no event is fired

**Comment by kamontat** [comment]
Thank you for fixes very fast :)
