### ISSUE TITLE
Unable to find a way to change the first day of week

### ISSUE THREAD

**Issue by thfontaine** [nathanreyes/v-calendar#31]
Hey =)
I was wondering if there is a way to change the first day of week, i went through the documentation a couple of times but i don't find any hints on how to do that.
If it is possible, could you show me how to do that ?
Thanks a lot for your work, this library is cleary the greatest calendar library i have found for vue.js =)

**Comment by nathanreyes** [comment]
Yes. When you use the plugin pass in `firstDayOfWeek` as one of the default settings, [among others](https://github.com/nathanreyes/v-calendar/blob/master/src/utils/defaults.js) if you desire.
```javascript
Vue.use(VCalendar, { firstDayOfWeek: 3 }); // Tuesday as first day of week
```
Apologies for the lack of clarity on this. I will keep this issue open until the documentation has been updated.

**Comment by thfontaine** [comment]
Ok, thank you very much for the quick reply!

**Comment by Abdulla1995** [comment]
This is not working for me. 
"v-calendar": "^1.0.8",
"nuxt": "^2.9.0",
```
import Vue from 'vue'
import Vcalendar from 'v-calendar'

Vue.use(Vcalendar, {
    firstDayOfWeek: 2,
})
```

But result is not changed. @nathanreyes . I have done lie so - :first-day-of-week="2" and it worked. I cant set globally first day of week. Please tell why this is not effecting globally.

**Comment by vedmant** [comment]
I have the same issue, chan't change firstDayOrWeek globally
