### ISSUE TITLE
Hidden border in DatePicker.vue component

### ISSUE THREAD

**Issue by Alex-M0** [nathanreyes/v-calendar#313]
Vue 2.6.10 and v-calendar 1.0.0-beta.10
https://github.com/nathanreyes/v-calendar/blob/21c8be7f6353d5d8a445869e7c63232d88608411/src/components/DatePicker.vue#L401

![calendar_bug](https://user-images.githubusercontent.com/49482532/57733694-cb5d8d80-76a8-11e9-83c8-a14e8fab20b2.png)

**Comment by jallen** [comment]
Seeing the same using Nuxt 2.6.3 and v-calendar 1.0.0-beta.10.

**Comment by nathanreyes** [comment]
Fixed as of `1.0.0-beta.11`
