### ISSUE TITLE
Dragging over highlighted days in range mode

### ISSUE THREAD

**Issue by sigjak** [nathanreyes/v-calendar#318]
I am using the datepicker (beta12) in range mode If I select by dragging over a highlighted day and then back off the highlighted day the highlight disappears and only reappears on reload. This was not an issue in .97. 
All the best

Sig

**Comment by PhantasWeng** [comment]
in `beta12`, I also found disabled-dates wont re-render when date change.
here is a quick [example](https://codesandbox.io/embed/test-vcalendar-ombh3?fontsize=14)
