### ISSUE TITLE
Implementing :min date question

### ISSUE THREAD

**Issue by huenisys** [nathanreyes/v-calendar#32]
Any idea how to best implement :min date so that dates before today are disabled?

**Comment by nathanreyes** [comment]
There are 2 ways to disable dates, either explicitly via `disabled-dates` or by assigning `available-dates` and all other dates are disabled. In your case, the simplest way is to assign a date range to `available-dates`, using `{start: new Date(), end: null}` to enable all dates from today to infiniity.

Here is a [codepen](https://codepen.io/nathanreyes/pen/EbjrRJ) if it helps.

**Comment by huenisys** [comment]
Hi Nathan,

I'm not capable of debugging this. Maybe you can take a look?

Whenever I change dates, it ruins the fixed-top and fixed-bottom elements
when using bootstrap 4.

Here's the demo site:

http://serensort.paolo.ph/suite/L1

Observe the header and footer affected when I change dates.
https://www.screencast.com/t/4trBN0grl

Any idea why?

**Comment by huenisys** [comment]
I realized it's because of the popover that shows on selection. I think I
will just disable it. Hopefully, it's possible.
