### ISSUE TITLE
current documentation 

### ISSUE THREAD

**Issue by guushamann** [nathanreyes/v-calendar#321]
the current docs on custom slot do not work, without putting the slot-scope on the button it does not work.
https://vcalendar.io/guide/datepicker.html#custom-slot

at the end of the page you have a link, "improve this page", the link is dead

looking in github it is not clear what the current docs for 1.0 are, so therfore this issue

**Comment by nathanreyes** [comment]
All examples are for the `next` branch. What version are you currently using?

**Comment by guushamann** [comment]
The next branch, and in the example is a custom slot with 1 button, without the scope tag on it, it does not work without it

**Comment by guushamann** [comment]
I am using the datepicker in combination with "vue the mask", and some other customizations in the slot. If you are intrested i can share it

**Comment by guushamann** [comment]
> All examples are for the `next` branch. What version are you currently using?

the issue is more complicated

in my dev env i use the same version ("v-calendar": "^1.0.0-beta.12") as in this example
[https://codesandbox.io/s/kirrk](url)

the example works, but the exact same code does not work in my webpack environment, maybe something to do with how i connect the vue parts

You can close the issue

**Comment by nathanreyes** [comment]
That is interesting. Let me know if you figure it out.
