### ISSUE TITLE
[Vue warn]: Unknown custom element: <vc-date-picker>

### ISSUE THREAD

**Issue by ezeike** [nathanreyes/v-calendar#325]
I have to use the prefix option because it's a vuetify project.

Console error:

`
[Vue warn]: Unknown custom element: <vc-date-picker> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
`

My main.js:

```
import VCalendar from 'v-calendar';

Vue.use(VCalendar, {
    componentPrefix: 'vc'
});

```

Version installed:

v-calendar@1.0.0-beta.13
vue@2.6.10
vuetify@1.5.14

**Comment by stivenramireza** [comment]
I have the same warn, did you fix it?

**Comment by xueyongg** [comment]
Howcome its closed? What was the issue and how did you resolve it?

**Comment by o-nasteka** [comment]
Use <vc-date-picker /> instead of <v-date-picker />

**Comment by LG0012** [comment]
Same config, using <vc-date-picker ... and getting the same warning - [Vue warn]: Unknown custom element: <vc-date-picker> - did you register the component correctly? For recursive components, make sure to provide the "name" option.
