### ISSUE TITLE
v-date-picker isn't working on ie11

### ISSUE THREAD

**Issue by AndreyCh1989** [nathanreyes/v-calendar#339]
TC:
1. ie11: open https://vcalendar.netlify.com/guide/#mask-tokens
2. try to choose any date from any instance of v-date-picker on the page

During loading the page a lot of "SCRIPT1002: Syntax error" occurred:
![image](https://user-images.githubusercontent.com/47121546/59034752-74487400-8874-11e9-9605-4aa10f15231c.png)

the same observing in my project.
looks like because of arrow functions.

**Comment by nathanreyes** [comment]
Closing this issue as IE11 is not officially supported.
