### ISSUE TITLE
Year-Picker missing page bounds with min-date or max-date

### ISSUE THREAD

**Issue by bernardoduarte** [nathanreyes/v-calendar#340]
Checking the [documentation](https://vcalendar.io/guide/#disabling-dates), it states the the following quote:

> When using **disabled-dates** and **available-dates**, **v-calendar** will not automatically disable page navigation for you, whereas using **min-date** and **max-date** will disable pages that are before **min-date** and after **max-date**.
> Use the **min-date**, **min-page**, **max-date** or **max-page** props to manually assign the page bounds when using **disabled-dates** or **available-dates**.

However when I use the **year-picker** with min or max dates it allows the user to navigate through instead of blocking years out of bounds.

Here is an [example](https://vcalendar.io/guide/#_2-explicitly-via-max-date), just check the **max-date** documentation date-picker.

**EDIT:** It also doesn't block the month-picker.

**Comment by swey** [comment]
Yes, can confirm this issue. Same problem here.
