### ISSUE TITLE
Accessibility audit

### ISSUE THREAD

**Issue by DavidRouyer** [nathanreyes/v-calendar#346]
I'm trying this carousel for the first time, thank you for your great work!

I'm not an accessibility expert but I ran into a lot of issues when I tried the component.

- [ ] The major issue is that there is no keyboard navigation support. You can see an example [here](http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm).
- [ ] Actually, the tab navigation browse to all the grid items, even if they are empty. Only the selected date should be "tabbable" and the other grid items should be accessible via the arrow keys. Also, add a default style when the grid item is focused.
- [ ] Add aria-label to all the grid items. Something like "9, Tuesday July 2019", which is automatically updated when you change the language.

Here is an article about accessible calendars: https://axesslab.com/accessible-datepickers/

**Comment by nathanreyes** [comment]
Thanks for providing the reference link. I will definitely take a look at it. I have been working on keyboard navigation support, but it is in the early stages and the example does provide a nice overview of basic functionality.

**Comment by eriese** [comment]
@nathanreyes I consider this necessary. Without keyboard accessibility I can't use this api, and I'd really like to. What's your progress on this and can I help?

**Comment by briandhill** [comment]
I also need the ability to navigate via keyboard input for accessibility. Has there been any planning on a potential time frame of that functionality? Thanks!

**Comment by nathanreyes** [comment]
@briandhill @eriese @DavidRouyer  I was able to complete the calendar navigation over the weekend. It basically mirrors this [basic ARIA picker calendar](http://whatsock.com/tsg/Coding%20Arena/ARIA%20Date%20Pickers/ARIA%20Date%20Picker%20(Basic)/demo.htm). Just need to add the aria-label support and work out some quirks with the date picker.

**Comment by briandhill** [comment]
NICE! I guess just let us know when it's in there. :)

**Comment by nathanreyes** [comment]
So `1.0.0-beta.15` is my first attempt at this. Please advise of any recommended changes. If none, I'll go ahead and close this issue.

**Comment by aarongerig** [comment]
@nathanreyes Just tested `1.0.0-beta.16` on one of my projects and it works great for me. One thing that could be improved is the following use case. When navigation a form with your tab key, it would be great to close the date picker automatically, once the input field respectively the date picker itself looses focus. Otherwise, the date picker stays open and covers up some of the following form fields. WDYT?

**Comment by briandhill** [comment]
@nathanreyes This is working well on my end. Thanks again for putting all the time in to help us out. 😄

**Comment by briandhill** [comment]
I just ran into a small problem where the app will not load at runtime in IE 11. It was working fine with the latest stable version. I would give you more context, but the error in IE 11 only points to what file it's happening in, `v-calendar/lib/v-calendar.umd.min.js`

**Comment by eriese** [comment]
Much Improved! 

Thoughts:
- I agree that the datepicker should close on focusout, same as it would for a non-keyboard user proceeding to the next input. 
- I think that the API should give the option to automatically set focus inside the datepicker when the user focuses inside the input that triggers it. The code for this will need to make sure that the user can tab back to the input if they would prefer to type, though. So this is maybe a nice-to-have that I could implement for myself.
- You're missing some ARIA roles that I think would be helpful. Using [`role=application`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/Application_Role) with `aria-roledescription` and `aria-activedescendant` would be great. I don't know why whatsock put the use instructions in a data-helptext, but that doesn't make a screen reader read them aloud, whereas aria-roledescription will.

**Comment by eriese** [comment]
I also would like the option to decide what date takes `tabindex=0` in v-calendar. Right now when I tab through, it goes to today's date, but I think it'd be nice to be able to choose to tab to the first date that has an attribute

**Comment by bellangerq** [comment]
First things first: thanks for adding these accessibility features @nathanreyes :tada:.

To develop @eriese last comments, it could be nice to add an `aria-current="date"` to the currently selected date. You can [learn more about this attribute here](https://tink.uk/using-the-aria-current-attribute/).

If you need an example, the first example submitted by @DavidRouyer implements this attribute.

**Comment by briandhill** [comment]
Hey @nathanreyes, wanted to check in to see if there was any plan to finalize this soon? I noticed that the latest version is still beta. I was also experiencing a problem with the Vue app not being able to load in IE 11. Will IE still be supported moving forward?

Thanks!

**Comment by briandhill** [comment]
Saw in your latest beta that you're not planning to support IE. I just wanted to mention that here in case anyone else was wondering.

**Comment by fkadhum** [comment]
Thanks for the huge effort.

I think mirroring https://dequeuniversity.com/library/aria/date-picker should be a better option. Navigating through months and years is not intuitive at all. It should uses tab to select the previous and the next button. Combinations (alt+pgdown and alt+pgup) are not very recomanded.

Thanks

**Comment by nathanreyes** [comment]
I believe the original requests of this issue have been addressed. Please feel free to open new issues for any follow-up concerns.

**Comment by mgalkus** [comment]
@nathanreyes, the original issue mentioned that "Only the selected date should be "tabbable"". Has this been resolved? Because now the current month day is being tabbed, not the selected day: 

https://user-images.githubusercontent.com/42642867/128026942-bf66f9d9-58ba-4906-b336-1bb2d824611b.mov

v-calendar version: 3.0.0-alpha.5
browser: Chrome
