### ISSUE TITLE
First day of week & locale

### ISSUE THREAD

**Issue by Simskii** [nathanreyes/v-calendar#35]
This doesn't seem to be documented.
How is this configurable?

**Comment by nathanreyes** [comment]
Yes, apologies for the lack of documentation for this. I am retooling the docs site at this time.

Both can be provided when using the plugin. [Here](https://github.com/nathanreyes/v-calendar/issues/31) is another issue that covers the `firstDayOfWeek` setting. The locale is detected in the browser, but you can also provide a `locale` string setting manually if it is supported.

I will accept the Swedish locale you provided.
