### ISSUE TITLE
Date Picker Range Highlight Not Working As Intended

### ISSUE THREAD

**Issue by liujustin** [nathanreyes/v-calendar#350]
Hi, great package you have here and the documentation is amazing. I'm trying to get the range to work on my project and I'm running into some issues. I'm not sure if some specificity has changed since `1.0.0-beta.10` but from `1.0.0-beta.11` - `1.0.0-beta.14`, the range seems to be broken. I'm importing v-calendar by using the cdn by the way. 

I believe that this is some css specificity issue with the reset possibly since it works on a simple html file that I have locally.

How it should look like:
![correct](https://user-images.githubusercontent.com/22507508/59802597-4e30c400-92b7-11e9-95aa-c38084c86628.gif)

notice how the range hover has no problems when dragging backwards

How it looks like on mine:

![incorrect](https://user-images.githubusercontent.com/22507508/59802658-70c2dd00-92b7-11e9-8ee2-c37234cebeda.gif)

notice how when dragging back the range, the highlights and circle does not go away.

Any thoughts on how to fix this or if you know the reason behind this?

**Comment by nathanreyes** [comment]
This problem should now be fixed in latest 1.0 or 2.0 releases.
