### ISSUE TITLE
How do I use default month when I open the calendar?

### ISSUE THREAD

**Issue by AruXc** [nathanreyes/v-calendar#357]
How do I use default month when I open the calendar?

example: 

today is 2019-06-26

but I want open the calendar is show 2019-05

I try `:to-date="new Date('2019-05-01')"` but didn't work

anyone use before?

**Comment by rahveiz** [comment]
Hi,
try using ```fromDate``` (or ```from-date```) instead.
```:fromDate="new Date('2019-05-01')"```

**Comment by AruXc** [comment]
@rahveiz  thx it worked
