### ISSUE TITLE
datepicker doesn't work on iOS

### ISSUE THREAD

**Issue by MohammadAbusaleh** [nathanreyes/v-calendar#358]
datepicker doesn't work when using :min-date on iOS, I tested it on iOS 12.3.1.

here's a codepen of the issue, it works fine on Android, Ubuntu, and Windows.
https://codepen.io/MohammadAbusaleh/pen/BgoKLv

**Comment by MCYouks** [comment]
Any update on this issue? How did you fix it?

**Comment by samuelkitazume** [comment]
I'm having issue with this as well 😔
