### ISSUE TITLE
Can you add some beautiful theme properties?

### ISSUE THREAD

**Issue by wuyungen1996** [nathanreyes/v-calendar#36]
I want to use datePicker. but it's difficult to adjust the theme properties.  please paste some beautiful theme properties

**Comment by nathanreyes** [comment]
I'm currently working on the new docs site and plan to provide more design examples. It may take a little bit before I can get to it though?

Do you have any examples I could work with that you had in mind? Some snapshots from Dribbble for example.

**Comment by nathanreyes** [comment]
I'll close this issue for now, as the new docs site is set for release soon and I hope to remedy many of these problems through the documentation. Please feel free to reopen after that point if you still feel this is needed.

**Comment by nathanreyes** [comment]
Just an update, you can reference the new [docs site](https://docs.vcalendar.io/layout.html#demo-walkthrough) for steps on how the configure the above calendar.
