### ISSUE TITLE
DatePicker component's name collides with Vuetify DatePicker

### ISSUE THREAD

**Issue by knagyorg** [nathanreyes/v-calendar#37]
Hi, DataPicker component collides with component with same name from Vuetify library.
Can you please add the 'componentPrefix' option to make this component unique?
Best regards
Karel

**Comment by paladin2005** [comment]
Any progress?

**Comment by nathanreyes** [comment]
You can pass `componentPrefix` as an option when using VCalendar.

```javascript
Vue.use(VCalendar, {
  componentPrefix: 'vc'
})
```
Then when using in template
```html
<template>
  <vc-calendar>
  </vc-calendar>
</template>
```

**Comment by VishalGulati** [comment]
Saved my day!! https://github.com/nathanreyes/v-calendar/issues/442

**Comment by bhaidar** [comment]
Hello @nathanreyes @VishalGulati 

Even by adding componentPrefix, I am still facing a problem. The v-calendar date picker is always taking precedence over the Vuetity one. Any idea why?
