### ISSUE TITLE
Can't build

### ISSUE THREAD

**Issue by LucaRainone** [nathanreyes/v-calendar#38]
I try to build ( ```npm run-script build``` ) from current source (6f25fa45139093e00d364b0b460f583df3064c8b)  and I got:

> Error: Cannot find module 'uglifyjs-webpack-plugin'

So I've tried with ```npm install uglifyjs-webpack-plugin --save-dev ``` but I got

>ValidationError: UglifyJs Plugin Invalid Options
options['compress'] should NOT have additional properties

I'm missing something else?

**Comment by nathanreyes** [comment]
Interesting. I just did a fresh git clone on my local machine, ran `npm install` and then `npm build` and it didn't see any issues. Are you running node v8.9.3 on your build machine?

**Comment by LucaRainone** [comment]
I'm on 9.2.1.
Maybe some module installed as cli or globally?
this line https://github.com/nathanreyes/v-calendar/blob/master/build/webpack.prod.conf.js#L12 where should fetch the module?

**Comment by nathanreyes** [comment]
Can you try using version 1.1.1 of the UglifyWebpackPlugin?

**Comment by LucaRainone** [comment]
Using the 1.1.1 version, i got:

> Error: Cannot find module 'tapable'

installng tapable i got:

> Error: Cannot find module 'source-list-map'

then 
```
Template.js:20
module.exports = class Template extends Tapable {
                                        ^

TypeError: Class extends value #<Object> is not a constructor or null
```

**Comment by nathanreyes** [comment]
Ok. At this point, I think I need to do some testing on another machine to take mine out of the equation. I'll report back here on my findings as soon as I can.

**Comment by LucaRainone** [comment]
Wait. I've deleted the whole node_modules directory and I've done a npm install again. Now I can build correctly. I don't know how, why and where was broken, but now it's all ok.

**Comment by nathanreyes** [comment]
Ok. I've definitely had to do that before. Glad you were able to get it working.
