### ISSUE TITLE
Components Method setup

### ISSUE THREAD

**Issue by nntai** [nathanreyes/v-calendar#380]
Hi @nathanreyes,

I'm using the component method to use v-calendar in my project. I just want to use your DatePicker component because of your Popover conflict with v-tooltip's [Popover](https://github.com/Akryum/v-tooltip).

https://vcalendar.io/guide/#_2b-components-method

When I use your sample code, I have some error. I read your code and I think it should be: 

```
    setupCalendar(Vue, opts);
```
instead of 
```
    setupCalendar(opts);
```

**Comment by nathanreyes** [comment]
Thanks for the heads up. Docs have been updated accordingly.
