### ISSUE TITLE
vc-reset forces !important

### ISSUE THREAD

**Issue by JoeCianflone** [nathanreyes/v-calendar#381]
Hi there,

I'm working with the date-picker and it's great, I have a small issue though with borders. I have a custom input with a  class that has a border on it, but the `.vc-reset` is in a wrapper `span` element and it resets the border to `none`. Obviously, I can just set my borders to `!imporant` and the issues "goes away" but I hate to use the important for something like this. Is there some way I can tell the date-picker to *not* add the reset class? Here's my code to see what I'm doing: 

```
        <v-date-picker :min-date='new Date()' v-model='selectedValue' :input-debounce='500'>
            <input slot-scope='{ inputValue, updateValue, inputProps, inputEvents }'
                   class="input:text"
                   ref="input"
                   :class="{ 'input:error': errors.length }"
                   v-bind="inputProps"
                   v-on="inputEvents"
                   @change.native='updateValue($event.target.value)'>
        </v-date-picker>
```

Oh, I should point out I'm on `next`

**Comment by nathanreyes** [comment]
![](https://media.giphy.com/media/10PcMWwtZSYk2k/giphy.gif)

**Comment by nathanreyes** [comment]
Fixed in `beta.20`
