### ISSUE TITLE
v-calendar.umd.js is too big

### ISSUE THREAD

**Issue by benliu723** [nathanreyes/v-calendar#388]
vue version: 2.6.10
v-calendar version: 1.0.0-beta.14
webpack: 4.28.4
babel:7.4.3

Currenctly, i am only using calendar component, however, i must import the all modules to make it work. 

I'm hoping to only load the required component instead of the whole components.
That is the right direction to go. 
Looking forward for your reply!

**Comment by nathanreyes** [comment]
The next beta dynamically loads calendar, picker and popover components so they will only get loaded when actually used.

**Comment by buremba** [comment]
I'm using `v-calendar@1.0.0-beta.23` and the DatePicker component is 250kb minified. It's almost same as our app bundle size, is this expected @nathanreyes ?

**Comment by mattsGitHub123** [comment]
We are running into the same problem. The bundle size is larger than our entire app. Are there any ways to reduce this?

**Comment by hmaesta** [comment]
Close this issue in favor of https://github.com/nathanreyes/v-calendar/issues/479

**Comment by hmaesta** [comment]
Close this issue in favor of https://github.com/nathanreyes/v-calendar/issues/479
