### ISSUE TITLE
How to disable tooltip ?

### ISSUE THREAD

**Issue by nkostadinov** [nathanreyes/v-calendar#39]
Can't find a way to disable the toolptip on daterange picker e.g. "24 days, 23 nights" ? Is it possible to disable this tooltip ?

**Comment by nathanreyes** [comment]
Yes, `select-attribute` and `drag-attribute` props are mixed in with the default ones, so you can turn it off by doing this.
```html
  <v-date-picker
    mode='range'
    :select-attribute='noPopoverMixinAttr'
    :drag-attribute='noPopoverMixinAttr'
    v-model='selectedDate'
    is-inline>
    
  </v-date-picker>
```
```javascript
export default {
  data() {
    return {
      selectedDate: null,
      noPopoverMixinAttr: {
    	popover: null,
      },
    };
  }
};
```
I think I will provide a `popover` prop for this in the next revision.

**Comment by nkostadinov** [comment]
Thank you. 
No way I could have guessed that from the documentation :)

**Comment by paulg446** [comment]
I've tried the above example the disable the tooltip when selecting a range, but it still appears.  It wouldn't bother me if it respected the weekdayLabels/monthLabels attributes, but it doesn't (it still renders them in English, despite rendering them with the provided labels in other areas of the calendar). Is the above approach still valid? Is there some other way I can disable the tooltip when selecting a range?

**Comment by nathanreyes** [comment]
There is now a `show-popover` prop for `v-date-picker` to hide the day popover. Is that what you are referring to?

**Comment by nathanreyes** [comment]
Also, here is the [reference](http://docs.vcalendar.io/popovers.html#components) for customizing the popover via your own component if you wish to do that.

**Comment by paulg446** [comment]
it turns out the above example works by specifying popover: {} (instead of popover: null). Thanks anyway for the link.

**Comment by paulg446** [comment]
also, yes, show-popover=false works too ... is that in the docs? I hadn't seen it.

**Comment by nathanreyes** [comment]
@paulg446 Also, the next version will appropriately display the dates in the date picker popover (not just English).

**Comment by seanzi86** [comment]
just a quick note in case anyone else lands here from google.
This property has been updated to `:show-day-popover`

**Comment by annelhote** [comment]
with v-calendar v.0.9.7, I had to do :
```
<v-date-picker
        mode="range"
        v-model="selectedDate"
        :select-attribute='noPopover'
        :drag-attribute='noPopover'></v-date-picker>
```
and
```
data () {
    return {
      noPopover: {
        popover: {
          component: null
        }
      }
    }
  }
```

**Comment by PuskyWasTaken** [comment]
How do I disable the tooltip in the latest version?

**Comment by thuannh1027** [comment]
@PuskyWasTaken do you have any progress? I have the same question.
