### ISSUE TITLE
I use slot of day and trigger click ,but when I click navbar's button to next or preview,that page is not working?

### ISSUE THREAD

**Issue by xiaojia90s** [nathanreyes/v-calendar#390]
<v-calendar ref="calendar"  :style="currtab == 3?'height:100%':'margin-bottom:10px'"  is-expanded  :attributes="attrs">
    <div slot="day-content" slot-scope="{ day }" @click="getChooseDate(day)" class="normalClick" :class="{ 'chooseDate':attrs[0].dates.indexOf(day.date) != -1, 'currClickDate': day.date == attrs[0].excludeDates}" @dblclick="cancelDate(day)" :attributesMap="attrs[0].dates">{{day.day}} 
    </div>
</v-calendar>

getChooseDate(val) {
      this.attrs[0].excludeDates = val.date;
      if (
        JSON.stringify(this.attrs[0].dates).indexOf(JSON.stringify(val.date)) ==
        -1
      ) {
        this.attrs[0].dates.push(val.date);
      }
    },
    cancelDate(val) {
      let index = this.attrs[0].dates.indexOf(val.date);
      this.attrs[0].dates.splice(index, 1);
    }

.normalClick {
  width: 28px;
  text-align: center;
}
.chooseDate {
  position: relative;
  color: #fff !important;
}
.chooseDate::before {
  position: absolute;
  content: "";
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  width: 100%;
  height: 28px;
  border-radius: 50%;
  background: #979899;
  line-height: 1;
  text-align: center;
  z-index: -1;
}
.currClickDate::before {
  background: #ff7f5b !important;
}

**Comment by haoshuohang** [comment]
秀儿
