### ISSUE TITLE
Display issues in Microsoft Edge

### ISSUE THREAD

**Issue by dewdad** [nathanreyes/v-calendar#391]
The component does not flashes and disappears on MS Edge browser at https://vcalendar.io/

Microsoft Edge 44.18362.267.0

**Comment by ablunier** [comment]
Problems also in Mozilla Firefox 68.0.2 for Ubuntu
![Screenshot_2019-08-22 V-Calendar](https://user-images.githubusercontent.com/4113587/63503714-4ae0d100-c4d0-11e9-9b85-a149c07cfdb6.png)

**Comment by nassosyian** [comment]
the problem also happens on Google Chrome 76.0.3809.100 (64-bit, win10)
in both https://vcalendar.netlify.com/ and https://vcalendar.io/

i get this error in console repeatedly

> app.d4dfe6b9.js:9 TypeError: Cannot read property 'data' of undefined
>     at new vu (app.d4dfe6b9.js:14)
>     at app.d4dfe6b9.js:14
>     at Array.map (<anonymous>)
>     at new gu (app.d4dfe6b9.js:14)
>     at app.d4dfe6b9.js:14
>     at Array.forEach (<anonymous>)
>     at mu.refresh (app.d4dfe6b9.js:14)
>     at new mu (app.d4dfe6b9.js:14)
>     at a.initStore (app.d4dfe6b9.js:14)
>     at a.created (app.d4dfe6b9.js:14)

**Comment by nassosyian** [comment]
there seems to be an error in "v-calendar/src/utils/locale.js" in the `resolveConfig()` function
it does not seem to return the correct default when it does not find the browser's current locale in the `defaultLocales` array.

@dewdad @ablunier can you please open console in your browser, execute `new Intl.DateTimeFormat().resolvedOptions().locale` and post the string it returns?
my guess is that the returned string is not in "v-calendar/src/utils/defaults/locales.js"

mine returns "el"

**Comment by ablunier** [comment]
Mine returns "gl"

**Comment by nassosyian** [comment]
so i went ahead and made a fork, fixed some things and did a pull request

 you can check [on the preview page here](https://deploy-preview-399--vcalendar.netlify.com/)
that everything works ok

**Comment by nathanreyes** [comment]
I think this issue can be safely closed now.
