### ISSUE TITLE
When specifying available-dates, only the first 2 are read

### ISSUE THREAD

**Issue by georgeboot** [nathanreyes/v-calendar#394]
I am using version `1.0.0-beta.16`

When using the following code:
```vue
<template>
<date-picker
    mode="single"
    :available-dates="[new Date('2019-08-20'), new Date('2019-08-25'), Date('2019-08-23'), Date('2019-08-28')]"
    is-inline
/>
</template>
```
It will only enable the first 2 dates of that array. All the following items will be ignored.

**Comment by nathanreyes** [comment]
Looks like the last 2 dates are missing the `new` specifier in your example.

**Comment by georgeboot** [comment]
Wow, missed that so badly. Thanks!
