### ISSUE TITLE
Do does not work, gives error about i18n.DoFn missing

### ISSUE THREAD

**Issue by verbeeksteven** [nathanreyes/v-calendar#396]
Hello,

The format Do does not work with the latest next. It gives an error about DoFn missing off i18n namespace.

Looks like next is missing 3893d07d2a2e4cb4fda300538257560236012ba8

**Comment by nathanreyes** [comment]
Nice catch! Adding it in for the next beta.

**Comment by nathanreyes** [comment]
Fixed as of `1.0.0-beta.19`
