### ISSUE TITLE
Webpack code splitting not working as intended

### ISSUE THREAD

**Issue by georgeboot** [nathanreyes/v-calendar#397]
I'm using this awesome library in a Vue Cli 3 project. Because we like to keep the bundle size of our entry point as tiny as possible, we code split our different views.

The documentation of this plugin suggest globally registering the plugin, but this would add the plugin to my entry point code, something I don't really need since the plugin is only being used on a few pages.

I've tried to fix this by doing the following:

```js
// main.js

import Vue from 'vue'
import App from './App.vue'
import router from './router'
import store from './store'
import { setupCalendar } from 'v-calendar'

setupCalendar(Vue, {
    firstDayOfWeek: 2,
})

new Vue({
    router,
    store,
    render: h => h(App),
}).$mount('#app')
```

```js
// router.js

import Vue from 'vue'
import Router from 'vue-router'
import Home from '@/views/Home.vue'

Vue.use(Router)

export default new Router({
    routes: [
        {
            path: '/',
            name: 'home',
            component: Home,
        },
        {
            path: '/calendar,
            name: 'calendar,
            component: () => import(/* webpackChunkName: "calendar" */ '@/views/Calendar.vue'),
        },
    ]
})
```

```vue
// Calendar.vue (page component that actually needs the calendar)

<script>
import { DatePicker } from 'v-calendar'

export default {
    components: {
        DatePicker,
    },
}
</script>
<template>
<div>
    <date-picker
        mode="single"
        :available-dates="calendarAvailableDates"
        :from-date="calendarAvailableDates[0]"
        :to-date="calendarAvailableDates[calendarAvailableDates.length - 1]"
        :attributes="calendarAttributes"
        is-inline
        :value="null"
        v-model="selectedCalendarDay"
    />
</div>
</template>
```

However, after running `yarn run build` and inspecting the bundle sizes, I found that the entire plugin still gets added to my main entry point, and not to the calendar chunk.

This is strange, since I only imported the `setupCalendar` method in the `main.js` file.

What am I doing wrong here? I checked the source code, and the plugin is properly exporting different modules.

Is there a way to omit the `setupCalendar` call entirely, if you want to use defaults?

Relates to: #314

**Comment by georgeboot** [comment]
For now, I omitted this by creating a the following module myself:
```js
import Vue from 'vue'
import { DatePicker, setupCalendar } from 'v-calendar'

setupCalendar(Vue, {
    firstDayOfWeek: 2,
})

export default DatePicker
```

... and referencing that only on the page where I need it.

This allowed me to remove the import statement from my `main.js` that caused the entire plugin to be loaded in my entrypoint.

**Comment by georgeboot** [comment]
Is there a specific reason the `setupCalendar` always needs to be called, even if you stick to defaults?

**Comment by nathanreyes** [comment]
> Is there a specific reason the `setupCalendar` always needs to be called, even if you stick to defaults?

It also setups up a global component used for sharing reactive state (popovers, themes, locales).

**Comment by nathanreyes** [comment]
@georgeboot No need to call `setupCalendar` anymore unless custom defaults need to be provided. Further, you can import components individually as noted in the [updated documentation](https://vcalendar.io/guide#_2b-components-method).
