### ISSUE TITLE
Broken docs link

### ISSUE THREAD

**Issue by pongoman** [nathanreyes/v-calendar#4]
Hello, 

When clicking on the _Reference the styling page for more details_ link, the page is directing to:

http://vcalendar.netlify.com/styling

but instead, you get a page not found. When clicking go back to the site, the url changes back to:

http://vcalendar.netlify.com/api

but it still displays the not found page

I have to type the url to get back to the pages, just a head's up. 
Good work

**Comment by nathanreyes** [comment]
Thanks for the catch. Also, the styling page is being worked on so check back later for more complete documentation.
