### ISSUE TITLE
Input hidden when inline

### ISSUE THREAD

**Issue by kl3sk** [nathanreyes/v-calendar#40]
Hi and thanks for you great component !

I use you component in a Symfony application, i implement this as a **Type**.
But because it is an HTML form, i need an input to send my datas to the server.

If not in line not problem to add one, but when i set the **:is-inline** props to **true** i have no input left.

Is there a way to have one ?

Thanks

**Comment by kl3sk** [comment]
Hello,
That sound very well !
I forgot to mention, that was (obviously) on the `v-date-picker`.
To answer your other question, i am able to user every available modes.

In one word, i need an `<input type="hidden" />` when the `v-date-picker` is `inline`

Thank you again for your great work.

**Comment by nathanreyes** [comment]
I would recommend using the following approach. For **both** inline and non-inline date pickers I would use a hidden input to synchronize with a local date value.

HTML
```html
<form>
  <input
    type='hidden'
    :value='myDate' />
  <v-date-picker
    :mode='mode'
    v-model='myDate'
    is-inline>
  </v-date-picker>
</form>
```

Javascript
```javascript
export default({
  data() {
    return {
      myDate: null,
      mode: 'range'
    };
  }
})
```
When the form is submitted, the hidden input will get sent with the selected date, not just a user-friendly formatted string version of the date. This should work for all date picker modes.

**Comment by kl3sk** [comment]
Thank you for your feedback, i'll try and came back.

**Comment by nathanreyes** [comment]
Ok. I'll close the issue unless this solution does not work for you.

**Comment by kl3sk** [comment]
Hi,

ok it seems working, but a have to add a computed like this:

```javascript
computed: {
    formatedDate() {
        return this.selectedValue.toLocaleDateString()
    }
},
```

To get my input right formatted:
```html
<input type="text" :value="formatedDate" :id="id" :name="name">
```

Because on **non inline** i use slot:

```vue
<v-date-picker
            class='picker form-group'
.....
v-model='selectedValue'>
        <input type='text'
               class='form-control'
....
>
</v-date-picker>
``` 

why not have an attribute to make this hidden, rather than completly removed ?
