### ISSUE TITLE
Highlight attributes is not applied to the seleted date

### ISSUE THREAD

**Issue by aduckardt** [nathanreyes/v-calendar#41]
Hi,

I'd like to override css for selected date in v-date-picker component, so I added the following attributes as a computed properties:
```
<script>
  import dateUtils from '../utils/DateUtils'

  export default {
    name: 'elnlms-date-picker',
    props: {
      patterns: {
        type: Object,
        default: () => ({
          weekdays: [1, 7]
        })
      },
      value: [String, Number, Object]
    },
    data () {
      return {
        placeholder: 'Pick a date',
        selectedDate: this.value
      }
    },
    computed: {
      attributes () {
        return [{
          // highlight today
          highlight: {
            backgroundColor: '#FE8B2D',
            borderColor: '#D26F22',
            borderWidth: '2px',
            borderStyle: 'solid'
          },
          contentStyle: {
            color: '#4F6166'
          },
          dates: [ dateUtils.toDate(this) ]
        },
        {
          // highlight selected date
          highlight: {
            backgroundColor: '#08A14A', // green
            borderColor: '#067B39',
            borderWidth: '2px',
            borderStyle: 'solid'
          },
          contentStyle: {
            color: 'white'
          },
          dates: [ dateUtils.toDate(this, this.selectedDate) ]
        },
        {
          // highlight weekends
          highlight: {
            backgroundColor: 'transparent',
            borderColor: 'transparent',
            borderWidth: '0px',
            borderStyle: 'none'
          },
          contentStyle: {
            color: '#A31313'
          },
          dates: [
            {
              ...this.patterns
            }
          ]
        }]
      }
    },
    methods: {
      dateFormatter: function (date) {
        return dateUtils.toDateString(this, date)
      },
      updateValue: function (value) {
        this.$emit('input', dateUtils.toUtcMillis(this, value))
      }
    }
  }
</script>
```

but the default css is applied for selected date. How can I override this?

**Comment by nathanreyes** [comment]
You are close. There is a prop called `select-attribute` where you can specify this. You don't have to specify a date with it..it uses the assigned value. For your example, this would work
```html
<v-date-picker
  :attributes='attributes'
  :select-attribute='selectAttribute'>

</v-date-picker
```
```javascript
...
data() {
  return {
    selectAttribute: {
      highlight: {
        backgroundColor: '#08A14A', // green
        borderColor: '#067B39',
        borderWidth: '2px',
        borderStyle: 'solid'
      },
      contentStyle: {
        color: 'white'
      },
      // Don't need the date here
    },
  };
},
computed: {
  attributes() {
    // Insert today's attribute
    // Insert weekend attribute
  },
},
...
```
Note: there is also a `drag-attribute`. You may need to modify that.
Also, if all you need to modify are the colors, you can assign `select-color` and `drag-color` and they just use all the other defaults. Let me know if this works for you.

**Comment by aduckardt** [comment]
Thanks a lot! it works

**Comment by olasunkanmi04** [comment]
Does this still work? Because it doesn't work for me

> You are close. There is a prop called `select-attribute` where you can specify this. You don't have to specify a date with it..it uses the assigned value. For your example, this would work
> 
> ```
> <v-date-picker
>   :attributes='attributes'
>   :select-attribute='selectAttribute'>
> 
> </v-date-picker
> ```
> 
> ```js
> ...
> data() {
>   return {
>     selectAttribute: {
>       highlight: {
>         backgroundColor: '#08A14A', // green
>         borderColor: '#067B39',
>         borderWidth: '2px',
>         borderStyle: 'solid'
>       },
>       contentStyle: {
>         color: 'white'
>       },
>       // Don't need the date here
>     },
>   };
> },
> computed: {
>   attributes() {
>     // Insert today's attribute
>     // Insert weekend attribute
>   },
> },
> ...
> ```
> 
> Note: there is also a `drag-attribute`. You may need to modify that.
> Also, if all you need to modify are the colors, you can assign `select-color` and `drag-color` and they just use all the other defaults. Let me know if this works for you.

**Comment by hamid-rsh** [comment]
This is not working for me too

**Comment by tetsuwanadam** [comment]
Neither select-attribute nor select-color are working for me either. Has there been some change to the api?
