### ISSUE TITLE
ERROR: js was blocked due to mime type (“text/html”) mismatch after update to 1.0.0-beta.17 from 1.0.0-beta.16

### ISSUE THREAD

**Issue by solankivj94** [nathanreyes/v-calendar#413]

**Comment by solankivj94** [comment]
The resource from “http://demo/v-calendar.umd.min.v-calendar.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

[Vue warn]: Failed to resolve async component: function a() {
          return Promise.all([o.e(0), o.e(2)]).then(o.bind(null, "e94a"));
        }
Reason: Error: Loading chunk 0 failed.
(error: http://demo/v-calendar.umd.min.v-calendar.js)

**Comment by d-koppenhagen** [comment]
Same here

**Comment by ptdev** [comment]
Hi,

I have the same issue after upgrading to beta.17

```
error [Vue warn]: Failed to resolve async component: ()=>Promise.all([o.e(0),o.e(2)]).then(o.bind(null,"e94a"))
Reason: Error: Loading chunk 0 failed.
(error: http://localhost:3001/_nuxt/v-calendar.umd.min.v-calendar.js)
```

**Comment by nathanreyes** [comment]
You shouldn’t use this version as Webpack is unable to resolve dynamic import chunks from 3rd party packages. I thought I had removed the ‘next’ tag from it but it seems I may need to unpublish it from npm. Beta 18 will get released soon to address the latest updates but unfortunately won’t be able to have dynamic imports for the popover component.

**Comment by ikoukuhn** [comment]
So, which version should we use to avoid this issue?

**Comment by nathanreyes** [comment]
`1.0.0-beta.19`
