### ISSUE TITLE
Issue adding my stored dates back into the datepicker

### ISSUE THREAD

**Issue by chrisgrim** [nathanreyes/v-calendar#426]
Hi,
I love this plugin! It works and looks so great. I have the datepicker setup so users can select multiple dates
```
              <v-date-picker
                mode='multiple'
                is-inline
                v-model='selectedValue'>
                </v-date-picker>
...

data() {
        return {
            selectedValue: new Date(),
        }
    },
```
I am storing this with laravel into my mysql database. In order for it to store correctly I have to convert using carbon
```
foreach( $request->dates as $date) {
            $newDate = Carbon::parse($date)->format('Y-m-d H:i:s');
            Date::create([
                'date' => $newDate,
                'event_id' => $event->id
            ]);
        }
```
This works great but when I try to add the dates back to the date input like so 
```
    mounted() {
        this.selectedValue = this.event.dates.map(a => a.date);
    },
```
The input calendar shows the dates, but in my console I am getting the error
```
Invalid prop: type check failed for prop "value". Expected Array, got Date 
Error in nextTick: "Error: Invalid Date in fecha.format"
Invalid Date in fecha.format
```
If I try to add any more dates nothing happens and I get the error again. Is this the wrong way to go about this?

**Comment by codekipple** [comment]
@chrisgrim I am experiencing the same error, please let me know if you find a fix for this ✌️

**Comment by chrisgrim** [comment]
Hi @codekipple 
I finally got it working after a lot of trial and error. I ended up realizing that I could put my date inside the new date() and it would format to what I needed. Here is my final code
```
    mounted() {

        this.selectedValue = this.event.dates.map(a => new Date(a.date));
        
    },
```
In my laravel controller I have 
```
foreach( $request->dates as $date) {

            $newDate = Carbon::parse($date)->startOfDay()->format('Y-m-d H:i:s');

            Date::create([
                'date' => $newDate,
                'event_id' => $event->id
            ]);

        }
```
So basically I store it one way in my database then when I bring it back into Vue I am converting it with new date().

**Comment by tonexv** [comment]
Hi,

Where do you get the a.date from? I know it's from the database but I don't see any code assigning the date from the db into a.date. Thanks.

**Comment by chrisgrim** [comment]
Hi @tonexv 
I am passing a prop into my vue template called event. That prop is my event object with the parameters from my database... name, description etc. Using laravels eloquent I also passed along all the dates assigned to that event. 
So when you see this.event.dates, it is all the dates assigned to my event using eloquent. Then I am using the .map() to filter through them.
