### ISSUE TITLE
popoverVisibility set to hidden, still able to edit the text field in the date picker

### ISSUE THREAD

**Issue by ramanangru** [nathanreyes/v-calendar#428]
How can i prevent user directly typing the date in the input box inside the date picker, when the popoverVisibility is set to hidden

**Comment by nathanreyes** [comment]
```html
<v-date-picker :input-props="{ readonly: true }" />
```

Does this work?

**Comment by ramanangru** [comment]
Thanks Man, it really helped. You made my day
