### ISSUE TITLE
Disabled-attributes prop?

### ISSUE THREAD

**Issue by vinkodlak** [nathanreyes/v-calendar#43]
Hi Nathan, 

sorry if i'm asking obvious, i'm trying to change disabled-attributes in a way that can be done with select-attribute or drag-attribute, but it's not working for me. Is it even possible?

**Comment by nathanreyes** [comment]
Have you tried using `disabled-attribute`? (no 's' at the end)

**Comment by vinkodlak** [comment]
Oh, I am so ashamed, missed that 's',

but tried now without 's' and it still does not change, tried it with
`<template>
  <v-date-picker
    :disabled-dates='disabledDates'
    :disabled-attribute='disabledAttribute'
  </v-date-picker>
</template>`

`  data() {
    return {
      disabledDates: [
        {
          start: new Date(nextMonthYear, nextMonth, 4),
          end: new Date(nextMonthYear, nextMonth, 9)
        }
      ],
      disabledAttribute: {
        contentStyle: {
          color: 'blue'

        }
      }`

if i change prop to drag-attribute, it works like it should.

managed to hack it like this to make it work:

`Vue.use(VCalendar, {
  firstDayOfWeek: 2,
  datePickerDisabledAttribute: {
    key: 'disabled',
    order: 100,
    contentStyle: {
      color: '#d98c8c',
      fontWeight: 600,
      opacity: 0.6,
      borderRadius: '0',
    },
    contentHoverStyle: {
      cursor: 'not-allowed',
      backgroundColor: 'transparent',
    },
    bar: {
      height: '1px',
      backgroundColor: '#d98c8c',
      borderWidth: 0,
      opacity: 0.6,
      position: 'relative',
      top: '-14px'
    }
  }
});`

**Comment by nathanreyes** [comment]
Oh yes I forgot that `disabled-attribute` was not available as a prop like `select-attribute` or `drag-attribute`. As you mentioned, you need to assign it as a default when calling `Vue.use`. I may try and add it as a prop in the next revision.

**Comment by nathanreyes** [comment]
Just wanted to post an update here, as of `v0.6.0` you can supply `disabled-attribute` as a prop on `v-date-picker` now. You can still specify as a default, but this is just another way to specify it.
