### ISSUE TITLE
Cannot read property 'isComplex' of null when setting `end` to null (for infinite repetition intervals)

### ISSUE THREAD

**Issue by d-koppenhagen** [nathanreyes/v-calendar#431]
Hello, leaving the property `end` set to null causes an error and not the expected behaviour (infinitie / open end repition interval). In the manual it is described that it should work like that:

```js
  ...
  dates: {
    start: new Date() // From today
    end: null // Until end (infinite)
  }
  ...
```

This causes the following error in the console:

```console
index.js:49 TypeError: Cannot read property 'isComplex' of null
    at v-calendar.umd.min.js:1
    at v-calendar.umd.min.js:1
    at v-calendar.umd.min.js:1
    at c (v-calendar.umd.min.js:1)
    at v-calendar.umd.min.js:1
    at n (v-calendar.umd.min.js:1)
    at s (v-calendar.umd.min.js:1)
    at new i (v-calendar.umd.min.js:1)
    at v-calendar.umd.min.js:1
    at Array.forEach (<anonymous>)
```

After trying a bit around I could find out that the issue doesn't appear when leaving the property `end` completely:

```js
  ...
  dates: {
    start: new Date() // From today
  }
  ...
```

I am using the latest v-calender version (`1.0.0-beta.21`).

**Comment by nathanreyes** [comment]
Thanks for reporting. Turned out to be a super simple fix.

**Comment by d-koppenhagen** [comment]
Awesome. Great to hear that. Would you mind to link the fixing commit? I am interested in it :-)

**Comment by d-koppenhagen** [comment]
@nathanreyes I couldn't find any commit fixing this. I think it hasn't been fixed in the `next` branch yet right? Otherwise: can you tell me which version fixed that?

**Comment by d-koppenhagen** [comment]
Thanks for solving this. It has been implemented in [v1-0-0-beta-23](https://vcalendar.io/changelog/v1.0.html#v1-0-0-beta-23)
