### ISSUE TITLE
How to include only datepicker

### ISSUE THREAD

**Issue by bsienn** [nathanreyes/v-calendar#432]
Sorry if this is documented somewhere but I can't find it.

So I installed v-calander using npm `npm i --save v-calendar@next`
"v-calendar": "^1.0.0-beta.22"

This is my current code.

```
Template
<v-date-picker :mode="mode" v-model="selectedDate"></v-date-picker>

import Vue from 'vue'
import DatePicker from 'v-calendar'
import 'v-calendar/lib/v-calendar.min.css'

// Use v-calendar, v-date-picker & v-popover components
Vue.component('v-date-picker', DatePicker)

export default {
 ...
}
```

I followed  the main repo page [2b section](https://github.com/nathanreyes/v-calendar#2b-components-method). 

Here are 2 issue I get:
1) `v-calendar.min.css` is not found in lib folder. Datepicker works without it so I might not need it.
2) Error in render: "TypeError: e.component is not a function"

If I use the following code it works fine, but I think it includes whole package and I only want the datepicker.
```

import Vue from 'vue'
import VCalendar from 'v-calendar'
Vue.use(VCalendar)
```

P.S. I also tried the [2b section](https://vcalendar.io/guide/#_2b-components-method) on the [vcalendar.io/guide](https://vcalendar.io/guide) but I got the following error

This dependency was not found:
* v-calendar/components/date-picker.umd

**Comment by bsienn** [comment]
Okay Good news, I tried the following and it did work.

import DatePicker from 'v-calendar/**_lib_**/components/date-picker.umd'

I needed to use lib, maybe docs needs some updating? Please have a look.

**Comment by nathanreyes** [comment]
@bsienn Good catch. Updated the docs.
