### ISSUE TITLE
How can i open the date picker popover?

### ISSUE THREAD

**Issue by frndmr** [nathanreyes/v-calendar#436]

**Comment by arthuraulin** [comment]
If you need to open the popover programmatically, you can do it this way:

https://jsfiddle.net/2gmwayd5/

**Comment by kinolollipop** [comment]
> If you need to open the popover programmatically, you can do it this way:
> 
> https://jsfiddle.net/2gmwayd5/

Does this solution still works? since I still cannot open the popup programmatically in this way...

**Comment by arthuraulin** [comment]
Yes, it's still working with the latest 1.0.1 version:
https://jsfiddle.net/zf67qu3h/

**Comment by kinolollipop** [comment]
> Yes, it's still working with the latest 1.0.1 version:
> https://jsfiddle.net/zf67qu3h/

I edited the code by adding an end tag for `v-date-picker` and it fails to open the calendar:
https://jsfiddle.net/cu04t19b/
Is there a guide to use open the calendar properly?
