### ISSUE TITLE
Day numbers miscalculated when firstDayOfWeek is set to 2.

### ISSUE THREAD

**Issue by Gergelin** [nathanreyes/v-calendar#44]
Number of days displayed wrongly in previous months when the firstDayOfWeek property is set to a different value than 1.

![bug](https://user-images.githubusercontent.com/12331891/35333011-70b74bd0-010d-11e8-8148-2244e97dd4e0.jpg)

**Comment by milostimotic** [comment]
Updated to 0.55 but seems that still doesn't work.

I tried:
```
Vue.use(VCalendar, {
  firstDayOfWeek: 3
})
```

**Comment by nathanreyes** [comment]
Can you check to make sure that the package was in fact updated to v0.5.5? I think npm was taking a while to update the registry so I just want to make sure.

**Comment by milostimotic** [comment]
I have checked and it is 0.5.5 as you can see on the image below:

![selection_018](https://user-images.githubusercontent.com/15947126/35363631-32bbefee-016b-11e8-880f-2cb75e7ee936.png)

**Comment by milostimotic** [comment]
Sorry my bad. Yes it was updated to v0.5.5 but it seem that none of options from `Vue.use(VCalendar, options) ` was not working because Vue was declared globally like `window.Vue = Vue` in bootstrap.js.

**Comment by nathanreyes** [comment]
Oh interesting. If Vue is a global object when the plugin is loaded then it calls `Vue.use` automatically for convenience purposes. Are you trying to use the plugin in a node environment?

**Comment by milostimotic** [comment]
Yes I am using the plugin in a node environment.
