### ISSUE TITLE
Inconsistent number of days in October on public site?

### ISSUE THREAD

**Issue by nickforddesign** [nathanreyes/v-calendar#440]
![Screen Shot 2019-10-04 at 11 35 07 AM](https://user-images.githubusercontent.com/1086884/66220586-4563d280-e69b-11e9-85bf-f0e4e03fdc67.png)

The first time I loaded the site, one of the October calendars showed 30 days, with 29 missing. Upon refresh, many of them only showed 28 days for October, which for the record, definitely has 31 days.

Am I losing my mind or is this a bug?

**Comment by nathanreyes** [comment]
It is very strange and must be just a rendering bug because if you navigate forwards and backwards it clears itself up. Also, when I build and test in dev mode this doesn't occur...just on the public site. I'll check it out

**Comment by nathanreyes** [comment]
@nickforddesign Honestly I can say exactly what the issue was but I think the dates for the examples on the homepage were corrupting the page somehow in production (wasn't an issue with the component itself) Can you verify that the issue gone?

**Comment by nathanreyes** [comment]
Closing this unless further problems arise.
