### ISSUE TITLE
v-date-picker ignores default firstDayOfWeek, works on attribute

### ISSUE THREAD

**Issue by mariszin** [nathanreyes/v-calendar#441]
Hi!

If I setup VCalendar plugin with the default value:
```vue
Vue.use(VCalendar, {
  firstDayOfWeek: 2
});
```
I would expect to have Monday as the first day in datepicker. But this does not have effect on it.
If I set the attribute, it works as expected:
```pug
v-date-picker(
  v-model='r.deadline'
  :min-date='new Date()'
  :firstDayOfWeek="2"
)
```

Using:
*    "v-calendar": "^1.0.0-beta.22",
*    "vue": "2.6.10",

**Comment by ivan-dmvv** [comment]
works in versions: v-calendar 1.0.1 & vue 2.6.11

```
<v-date-picker 
        :firstDayOfWeek="2"
        :min-date="new Date()"
        v-model="r.deadline"
 />
```

use `npm update` & and try again

**Comment by mariszin** [comment]
Unable to reproduce now
