### ISSUE TITLE
Missing tag / release

### ISSUE THREAD

**Issue by DanielRuf** [nathanreyes/v-calendar#445]
0.9.7 is missing:

https://github.com/nathanreyes/v-calendar/compare/v0.9.6...master

https://github.com/nathanreyes/v-calendar/releases

**Comment by hackel** [comment]
@nathanreyes Please properly tag your releases.  It looks like this project hasn't released anything since 16 Apr 2018.  This makes it much easier to compare and evaluate upgrades prior to applying them to a project.

**Comment by nathanreyes** [comment]
Yeah good catch. They were just living locally. I just pushed them all up to `origin`.
