### ISSUE TITLE
Adding option for selectedDate not to be null.

### ISSUE THREAD

**Issue by milostimotic** [nathanreyes/v-calendar#45]
When date is selected, and when it is clicked again, selectedDate will be set to **null**. My suggestion is to add some option so users can choose if selectedDate can be null or can not.

**Comment by nathanreyes** [comment]
As of `v0.6.0`, you can use the `is-required` prop to prevent null selections by the user (via input element or selections).
> Note: You still need to provide it a non-null value on initialization. Also, you can still set the value to `null` via code.
