### ISSUE TITLE
Disabled dates not working or ?

### ISSUE THREAD

**Issue by jfustier-it** [nathanreyes/v-calendar#457]
Hello,

I try to set disabled-dates in my v-date-picker, but i've this error : *You may have an infinite update loop in watcher with expression "disabledAttribute"*

``` 
<v-date-picker mode='range'  v-model="rangeDate" :min-date='new Date()' :disabled-dates="disabledDates">
</v-date-picker>
```

The disabled dates are returned by a http request and stored in my component : 
```
[{start: xxxx, end: xxxx}, {start: xxxx, end: xxxx}]
```

The link of documentation: https://vcalendar.io/guide/#include-vs-exclude-dates

**Comment by alexmare93** [comment]
Same Problem, any further solution?

thank you

**Comment by jfustier-it** [comment]
I changed the module for : https://github.com/ManukMinasyan/vue-functional-calendar

You can pass disabled dates (no range dates)

**Comment by ilikerobots** [comment]
Disabled and available dates are working for me, but only after I read https://github.com/nathanreyes/v-calendar/issues/203 which describes some nuances in how you can use them and min-date together (or rather, how you can't).

**Comment by thomashdk** [comment]
@jfustier-it  Did you get it to work ??

**Comment by jfustier-it** [comment]
no, I just changed the module

**Comment by EVOSandru6** [comment]
Hello.
It`s problem when defined :min-date and :disabled-dates='ranges'.
Where ranges is property array.

If removed one of them, all be right.

FAIL:

<v-date-picker
                v-model="localDate.started_at"
                :mode="mode"
                :disabled-dates='ranges'
                :min-date='new Date()'
                is-inline
        />

NOT FAIL:

<v-date-picker
                v-model="localDate.started_at"
                :mode="mode"
                :disabled-dates='ranges'
                is-inline
        />


NOT FAIL:

<v-date-picker
                v-model="localDate.started_at"
                :mode="mode"
                :min-date='new Date()'
                is-inline
        />

min-date and disabled-dates are not friends ((((

**Comment by e-wag** [comment]
Hello there,
I was able to fix the problem for me. 
1. I am setting a computed value for the v-model with an empty setter method.
2. I am setting the desired disabled dates in a computed method as well and create a new array for them.
For whatever reason these two things in combination fix the infinite loop problem

This is how my v-calendar looks like
`<v-date-picker :min-date="new Date()" :disabled-dates="getDisabledDates" visibility="focus"
                                   id="zeitraumId" v-model.trim="parseZeitraum"
                                   :class="{'is-invalid': !isZeitraum && isZeitraumInitialized, 'is-valid': isZeitraum && isZeitraumInitialized}"
                                   mode="range" :popover="{visibility: 'focus', placement: 'auto'}">
                        <input slot-scope="{inputProps, inputEvents}" v-bind="inputProps" v-on="inputEvents"
                               @keydown="isZeitraumInitialized = true"
                               @focusout="onZeitraumFocusOut"
                               class="form-control" :placeholder="getDateFormat + ' - ' + getDateFormat"
                               :class="{'is-invalid': !validateZeitraum(inputProps) && isZeitraumInitialized, 'is-valid': validateZeitraum(inputProps) && isZeitraumInitialized}">
                    </v-date-picker>`

And these are my two computed methods I use:

`parseZeitraum: {
                get(){
                    return this.validatorObj.zeitraum.$model
                },
                set(){}`

`getDisabledDates: function () {
                let dates = [];
                for (let i = 0; i < this.disabledDates.length; i++)
                    dates.push(this.disabledDates[i])
                return dates;
            }`

Hope, it helps someone looking for a solution

**Comment by kostia7alania** [comment]
**RANGE DOESN'T WORK !!!!!!!!!!!!!!!!!!!!!**
`<v-date-picker mode="datetime" :value="form.dates" :is-range="true" />`

**Comment by kostia7alania** [comment]
sorry! its work after updating to 1.1.1
coz YARN installed by default old ver 1.0.8 (!

**Comment by nathanreyes** [comment]
Tested as of `2.2.1` but probably was fixed in an earlier version.

#### Example
```html
  <v-date-picker
    v-model="range"
    :min-date="new Date()"
    :disabled-dates="disabledDates"
    is-range
  />
```
```js
export default {
  data() {
    return {
      range: null,
      disabledDates: [
        { start: new Date(2021, 1, 9), end: new Date(2021, 1, 19) },
      ],
    };
  },
};
```

There has also been a new section added for clarifying how `disabled-dates` and `available-dates` work when used together.
https://vcalendar.io/disable-dates.html#simultaneous-use
