### ISSUE TITLE
Question: How to have calendar pop-up OVER Bootstrap static navbar?

### ISSUE THREAD

**Issue by gabriellyeung** [nathanreyes/v-calendar#467]
Hi,

VCalendar is looking great, however its popping under my static Bootstrap navbar.

Is there any way to have it pop-up over the navbar?
I have read about z-index but I don't know what the CSS target is.

Thanks!

<img width="268" alt="image" src="https://user-images.githubusercontent.com/46561637/69289459-b3b32300-0c50-11ea-9c2f-ffd855984a91.png">

**Comment by peter9teufel** [comment]
did you manage to get the popup OVER the navbar?

**Comment by nathanreyes** [comment]
You might try setting the `positionFixed` flag in the `popover` prop.
```html
<v-date-picker v-model="date" :popover="{ positionFixed: true }" />
```

**Comment by gabriellyeung** [comment]
Peter: I did, I was able to use z-index in the end but that is an inflexible solution.
Nathan: Thanks for the tip.

**Comment by kiralyta** [comment]
> Peter: I did, I was able to use z-index in the end but that is an inflexible solution.
> Nathan: Thanks for the tip.

How did you manage to use z-index at the end? I think it should be possible to set the z-index value of the popover.
