### ISSUE TITLE
this.$screens is not a function after v1.0.0-beta.16

### ISSUE THREAD

**Issue by eriese** [nathanreyes/v-calendar#468]
I recently accidentally updated from beta.16 to beta.22 and found that I was getting `TypeError: this.$screens is not a function`. Working backwards, I discovered that if I wanted to use $screens, I couldn't upgrade past 16, so I think you've likely broken it in somewhere along the way...

in case it matters, my setup is something like this:
```javascript
// vueSetup.js
import Vue from 'vue/dist/vue.esm';
import VCalendar from 'v-calendar';

Vue.use(VCalendar);
return new Vue(_root);
```

and then my I have the calendar in wrapper component:
```javascript
// calendarWrapper.js
export default {
  ...
  template: '<div><v-calendar v-bind="calendarProps"/></v-calendar><div>',
  computed: {
    calendarProps() {
      return {
        ...
        columns: this.$screens({md: 2, lg: 3}, 1),
      };
    },
  }
}
```

**Comment by eriese** [comment]
actually, hold the line.
this might be something up with me because now I'm having it just fine in .22... I updated npm the other day and it's messed with some stuff

**Comment by eriese** [comment]
sorry to be waffling, but it turns out I am still having this issue and going back to 16 always fixes it.

**Comment by nathanreyes** [comment]
So I just set up this [small example](https://codesandbox.io/s/jovial-night-x4qvo?file=/src/App.vue) and the it reports the function. Seems like it might be an issue in your setup. Going to close this issue for now, but let me know if you can re-create the issue.
