### ISSUE TITLE
how to use the monthNames in locale?

### ISSUE THREAD

**Issue by mrrs878** [nathanreyes/v-calendar#469]
``` vue
<v-calendar :attributes='attrs' :locale="calendarEnv">
```
``` javascript
const calendarEnv = {
  masks: {
    title: 'YYYY-MM'
  },
  monthNames: ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L']
}
```
This writing has no effect

**Comment by hipkiss91** [comment]
I'm having the same trouble - I don't know the format expected - it isn't documented anywhere.

**Comment by nathanreyes** [comment]
The [docs](https://vcalendar.io/i18n.html#object-locale) should help clear things up here. You can define your own `masks` and `firstDayOfWeek` parameters.

**Comment by swthate** [comment]
The above answer does nothing to address the original question. The documentation states we can define properties in addition to `masks` and `firstDayOfWeek`, such as `monthNames` and `dayNames`, but those do not work, nor does the documentation offer any clarification as far as how to _use_ these other params.

Only `masks` and `firstDayOfWeek` work...

Are the other "params" mentioned by the documentation supported at all? Currently the documentation is more misleading than clarifying.

**Comment by mcandylab** [comment]
@nathanreyes , sorry, but you stupid... problem NOT RESOLVED (next branch, vue 3). I wasted two hours reading that other people have the same problem and it has not been solved. It's 2022, and the problem is still relevant. That's fucked up.
