### ISSUE TITLE
Usage inside modals

### ISSUE THREAD

**Issue by nickforddesign** [nathanreyes/v-calendar#47]
Absolutely love this datepicker!

Do you have any suggestions on how to handle the date input inside modals? If a parent container has `overflow: hidden`, the calendar is obviously cut off. Another datepicker I've used in the past, [Kalendae](https://github.com/Twipped/Kalendae), addressed this problem by appending the calendar element to `<body>` and setting the position of the calendar.

I really wouldn't mind having to do that myself in my application, maybe using `vue-portal`, but I'm not sure that it's currently possible to access the calendar component for inputs in that way.

Any suggestions? 

![screen shot 2018-01-26 at 5 13 32 pm](https://user-images.githubusercontent.com/1086884/35463119-1b60374e-02bd-11e8-8eb7-8374cd6592d2.png)

**Comment by nathanreyes** [comment]
That is an interesting problem. Vue's component system does pose a little bit of a challenge. I may do some testing with `vue-portal` to see if I can get things working. If I can, and if it doesn't add too much to the overall size of the package, I may include it as a dependency and add the option to alter the DOM hierarchy to overcome this issue.

**Comment by nickforddesign** [comment]
Awesome, let me know if I can help in any way

**Comment by nathanreyes** [comment]
One solution might be to allow the developer to specify a clear margin to apply whenever the popover is open. Then, when the popover is opened by the user, the margin is applied (probably around 200 - 300px. This would effectively force the model to display empty space inline, leaving room for the popover to display. This would probably be a better user experience as well.

**Comment by nickforddesign** [comment]
I think I'm following what you're saying, do you mean that the height of the modal would change when the popover is open? One UX problem this poses for us is that the modal is vertically centered, so changing the modal height would make the inputs move up, potentially making the popover disappear again.

**Comment by nathanreyes** [comment]
I see. Perhaps `v-calendar` would force `popover-visibility` to `"focus"` instead of `"hover"`, which I believe would solve this, but it might still be a little jarring to the user.

**Comment by nickforddesign** [comment]
@nathanreyes Is that already an option? To control what event the popover responds to?

**Comment by nickforddesign** [comment]
It would be nice to be able to control what events trigger the popover to open, also it would be nice to be able to have an event listener for the popover opening/closing. I think that would be a pretty simple way to use the workaround you suggested.

**Comment by nathanreyes** [comment]
There is an existing prop on `v-date-picker` called `popoverVisibility` for just this purpose. It accepts `"hover"`, `"focus"`, `"visible"` and `"hidden"`.

There are no events emitted though when the popover appears/disappears. That would be easy to add though.

**Comment by algil** [comment]
Hi @nickforddesign!
Were you able to solve this?
I've got the same issue https://codesandbox.io/s/o5joqz51x5

**Comment by Ashkanph** [comment]
My modal had enough space on top of the datePicker; So I solved the problem temporarily by adding this line to the `v-date-picker`:

`popover-direction="top"`

**Comment by koyta** [comment]
@nathanreyes no plans about usage with portal-vue?

**Comment by DavidSprauel** [comment]
Sorry to dig that issue up, but anyone has found a solution ? `popover-direction="top"` doesn't wrk in my case.

**Comment by yumemi-omi** [comment]
> If a parent container has overflow: hidden, the calendar is obviously cut off.

Setting `overflow: visible;` to parent container became the solution in my case.

**Comment by naufalfarras** [comment]
i had this problem too, my modal need to scroll so i add overflow-y: auto to the parent container, but it seems not working when the parent container have overflow: hidden/auto as well, maybe we can conditinally overflow parent container when the v-calendar is open?

**Comment by avxkim** [comment]
@nathanreyes https://github.com/nathanreyes/v-calendar/commit/1646f74caf5dbf7a1e39c2f03c3678019c748790 there's prop: `popoverShowClearMargin` but seems it doesn't work.

**Comment by sfitzmaurice** [comment]
> > If a parent container has overflow: hidden, the calendar is obviously cut off.
> 
> Setting `overflow: visible;` to parent container became the solution in my case.

For me, the parent container was the .v-popper__inner class.

**Comment by andersonAlmeida** [comment]
I have fixed that issue changing the popper strategy to fixed. Accessing the popover ref we can change the `positionFixed` data to `true`.
Example:
```
onMounted(() => {
  datePickerRef.value.popoverRef.positionFixed = true
})
```

**Comment by kardeepak77** [comment]
andersonAlmeida solution worked for me!

BTW, popover supports strategy = fixed
https://popper.js.org/docs/v2/constructors/#strategy

If v-calendar's PopoverConfig starts supporting strategy=fixed and pass that to popover, we will have clean solution.

Current  PopoverConfig
type PopoverConfig = Partial<{
  label: string;
  customData: any;
  visibility: 'click' | 'hover' | 'hover-focus' | 'focus';
  placement: Placement;
  hideIndicator: boolean;
  isInteractive: boolean;
}>;

Future PopoverConfig
type PopoverConfig = Partial<{
  label: string;
  customData: any;
  visibility: 'click' | 'hover' | 'hover-focus' | 'focus';
  placement: Placement;
  hideIndicator: boolean;
  isInteractive: boolean;
strategy: 'fixed'|'';
}>;

If supported we can define 
const popover = ref({
  placement: 'top-start',
  strategy: 'fixed',
})

<DatePicker
              ...
              :popover="{
                placement: 'top-start',
                strategy: 'fixed',
              }"
              
            >
