### ISSUE TITLE
Weekday mask prevents deselection of day in datepicker in 'multiple' mode

### ISSUE THREAD

**Issue by sboboryk** [nathanreyes/v-calendar#475]
Putting a mask on weekday name in v-date-picker mode "multiple" makes deselection of selected days impossible.
E.g.
This is working (days can be selected and deselected): 

          <v-date-picker
            mode="multiple"
            v-model="employee.selectedDates"
            is-expanded
            locale="pl"
            is-inline
          />

This is not working (days can be selected only, clicking or using enter is not making blue circle of day selection disappear).

          <v-date-picker
            mode="multiple"
            v-model="employee.selectedDates"
            is-expanded
            locale="pl"
            is-inline
            :masks="{ weekdays: 'WW' }"
          />

Is it a bug or I missed something?

**Comment by NickVandenberghe** [comment]
use `masks="{ weekdays: 'WW'}"` then it works
thought it didn't work for single mode as well but you have to get rid of the ":"

**Comment by pixeldemon9** [comment]
Experiencing this too, but with the "input" mask.  Do all masks break de-selecting days in multiple mode?

**Comment by nathanreyes** [comment]
I know this is an old issue. Apologies for just getting to it. I just checked in `1.0.8` and this issue seems to not be present. Please feel free to re-open is this issue is still persisting.
