### ISSUE TITLE
December 2019 is broken

### ISSUE THREAD

**Issue by AbrahamBrookes** [nathanreyes/v-calendar#476]
Visiting the projects website - https://vcalendar.io - this month (Dec 2019) shows a broken December 2019 calendar display. The calendar only shows up to the 27th, and has 27, 28, 29 and 30 at the start of the month instead. 31 isn't even there. Clicking those dates at the start of the month makes them disappear and reappear at the end of the month where they should be, but doesn't add a 31. 

That's a broken calendar I must say.

**Comment by nathanreyes** [comment]
This happened once and it seemed to be a strange caching issue with just this page that would only happen when I deployed on Netlify.

Either way, I deployed the updated docs site tonight and naturally it goes away. Not seeing that behavior on any other pages but will keep investigating.

**Comment by AbrahamBrookes** [comment]
Ah no worries, great library!
