### ISSUE TITLE
 import { getExampleMonthComps } from '@/utils/helpers.js' not found

### ISSUE THREAD

**Issue by StanislavBerezin** [nathanreyes/v-calendar#48]
I'm trying to implement a popover example when you press on the date and u can set something up. But by some weird reason it gives me errors 

 This dependency was not found:

            This dependency was not found:

               * @/utils/helpers.js in ./node_modules/babel-loader/lib!./node_modules/vue-
               loader/lib/selector.js?
 type=script&index=0&bustCache!./src/components/profile/creator/components/MyCreator/SetSessions.v
              ue

             To install it, you can run: npm install --save @/utils/helpers.js

not sure what i'm doing wrong i've followed all the steps that u said in your setup. 

These are my dependencies for webpack project
      
           "dependencies": {
    "axios": "^0.17.1",
    "babel-runtime": "^6.26.0",
    "v-calendar": "^0.5.5",
    "vue": "^2.5.2",
     }

      "devDependencies": {
    "autoprefixer": "^7.1.2",
    "babel-core": "^6.22.1",
    "babel-helper-vue-jsx-merge-props": "^2.0.3",
    "babel-loader": "^7.1.1",
    "babel-plugin-syntax-jsx": "^6.18.0",
    "babel-plugin-transform-runtime": "^6.22.0",
    "babel-plugin-transform-vue-jsx": "^3.5.0",
    "babel-preset-env": "^1.3.2",
    "babel-preset-stage-2": "^6.22.0",
    "chalk": "^2.0.1",
    "copy-webpack-plugin": "^4.0.1",
    "css-loader": "^0.28.0",
    "extract-text-webpack-plugin": "^3.0.0",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.6.1",
    "html-webpack-plugin": "^2.30.1",
    "node-notifier": "^5.1.2",
    "node-sass": "^4.7.2",
    "optimize-css-assets-webpack-plugin": "^3.2.0",
    "ora": "^1.2.0",
    "portfinder": "^1.0.13",
    "postcss-import": "^11.0.0",
    "postcss-loader": "^2.0.8",
    "rimraf": "^2.6.0",
    "sass-loader": "^6.0.6",
    "semver": "^5.3.0",
    "shelljs": "^0.7.6",
    "uglifyjs-webpack-plugin": "^1.1.1",
    "url-loader": "^0.5.8",
    "vue-loader": "^13.3.0",
    "vue-style-loader": "^3.0.1",
    "vue-template-compiler": "^2.5.2",
    "webpack": "^3.10.0",
    "webpack-bundle-analyzer": "^2.9.0",
    "webpack-dev-server": "^2.9.1",
    "webpack-merge": "^4.1.0"
      },
     "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
      },
      "browserslist": [
        "> 1%",
        "last 2 versions",
       "not ie <= 8"
       ]
    }   

Whats wrong with this?

**Comment by StanislavBerezin** [comment]
Hmm, as far as i can its simply mockup things that are not meant to be used but rather just for illustration purposes. However it would really nice if u can show a good way to make it work rather than dummy data

**Comment by nathanreyes** [comment]
Are you trying the use a popover with `v-calendar` or `v-date-picker`? Everything should work, they are not just mockups, if you are referring to the demos on the website.

**Comment by StanislavBerezin** [comment]
I was trying to use v-calendar with pop-over. As i can see u r using b-icon so i'm assuming its buefy, i'm using the exact same UI framework for my project. 
Basically the problem is that everytime when i write
 
      import { getExampleMonthComps } from '@/utils/helpers';

In my components it tells me that it cant find it. I tried to manually go to node_modules like "../../../so on.."
But it didnt work neither. So not sure how can i import and use it

**Comment by nathanreyes** [comment]
Oh I understand now. You need to remove that statement from your own code and replace all the dates using `thisMonth` and `thisMonthYear` with hard coded numbers (`1` and `2018`).

The only reason I was using  `getExampleMonthComps` is because I didn't want to include all of the code to get the current month and year for the current month, so I used a function declared in an external file to do this for me. That file doesn't exist in your build environment so it doesn't work. 

I think I will change this as to not confuse people in the future.

**Comment by nathanreyes** [comment]
If you still have problems getting it to work I can provide a code snippet. I'm going to go ahead and close this issue.
