### ISSUE TITLE
update:page emitted twice on is-double-paned date-picker

### ISSUE THREAD

**Issue by Moonbird-IT** [nathanreyes/v-calendar#480]
I have a double-paned date-picker on which I want to track month changes. Problem is that the `@update:page` event is emitted twice, once for each month. The event order seems to be random. Any idea how to properly check which month the user navigated to?

**Configuration of date picker**

    <v-date-picker :is-inline="true"
                                   :is-expanded="true"
                                   :is-double-paned="true"
                                   :is-linked="true"
                                   :attributes="store.getters.reports"
                                   v-model="store.state.selectedDate"
                                   @update:page="pageChange"
                    ></v-date-picker>

**Comment by nathanreyes** [comment]
Yeah I wouldn't use `update:page`, but rather try using `update:frompage` or `update:topage` to get the first and last pages. Let me know if that works.

**Comment by nathanreyes** [comment]
@Moonbird-IT I'm sorry, I didn't realize you weren't on the `next` version. Do you need to stay on the pre-v1.0 version?

**Comment by Moonbird-IT** [comment]
@nathanreyes I hadn't seen that there were different branches, I always checked out the master branch. I'll see if I can switch our current applications to the most recent version.

Just out of curiosity, why has the master branch not been updated for so long?
