### ISSUE TITLE
Add Placeholder for the field.

### ISSUE THREAD

**Issue by NikoGrano** [nathanreyes/v-calendar#493]
Is it possible to have placeholder for the field? Example:
![image](https://user-images.githubusercontent.com/4658966/71804545-7671eb80-306c-11ea-8d9a-08b561e4fef3.png)

In this example, Best Before is using v-calendar and doesnt have placeholder due of that.

**Comment by NikoGrano** [comment]
Project seems to be unmaintained, closing.

**Comment by djurovicigoor** [comment]
@NikoGrano You can do something like 

`:input-props="{placeholder : placeholder}"`

**Comment by TheMangoTrain** [comment]
> :input-props

This is deprecated in v2.0
