### ISSUE TITLE
Safari display bug when using date picker with range

### ISSUE THREAD

**Issue by derekpitt** [nathanreyes/v-calendar#496]
Hi!

It looks like in Safari (13.0.4), when I select the first date, the height of the popover contents increases and causes this:

<img width="441" alt="image" src="https://user-images.githubusercontent.com/551020/71996594-1f058400-3202-11ea-8a0d-be22e185687d.png">

In chrome, it seems to be ok:
<img width="422" alt="image" src="https://user-images.githubusercontent.com/551020/71996552-0ac18700-3202-11ea-821b-0735f0c940e5.png">

It seems to only happen after I select a date and move the mouse a little.

Thanks for the great lib!!!

**Comment by nathanreyes** [comment]
Hi @derekpitt. I created a simple date picker [here](https://codesandbox.io/s/clever-field-y30lu) and viewed in Safari and can't seem to recreate the issue. What version of `v-calendar` are you currently running?

**Comment by derekpitt** [comment]
Hey @nathanreyes!

I'm running 1.0.1. But I cannot reproduce either, so it must be something else going on with my app that is causing this. I'll poke around and see if I can get a minimum reproduction codepen.

But for now, I'll close this issue out. Thanks!

**Comment by piotrga** [comment]
Please reopen - this issue can be reproduced with the example from the main website.

**Comment by roarkmccolgan** [comment]
> Hi @derekpitt. I created a simple date picker [here](https://codesandbox.io/s/clever-field-y30lu) and viewed in Safari and can't seem to recreate the issue. What version of `v-calendar` are you currently running?

Hi,

Safari 14 macOS Catalina 10.15.6 v-calendar 1.0.1 - 1.0.8
I am having the same issue as everyone here

What is really strange is that your code sandbox post in comment above is working just fine
