### ISSUE TITLE
contentStyle not working since 1.0.x

### ISSUE THREAD

**Issue by pmochine** [nathanreyes/v-calendar#499]
Hey, I just upgraded the package from ^0.9.7 to 1.0.1. However, I noticed that the font of the date of "today" is not bold anymore.

"Today" is added to the attributes array by this method:

```
today() {
     return {
          contentStyle: {
               fontWeight: '700',
               fontSize: '.9rem',
          },
          dates: new Date(),
          popover: {
              label: trans('Today'),
          }
      };
 },
```

However, contentStyle is completely ignored. Is it deprecated? I don't find it in changelogs and it's still there in the API section (however not in the guide section).

**Comment by itdzuj1** [comment]
Have the same problem. Can't style weekends for example.

**Comment by unikitty37** [comment]
This is not working for me either. It seemed to be a workaround for #644, but it apparently hasn't worked for **ten months**, with no response to this ticket.

Is this project actually abandoned now?
