### ISSUE TITLE
Wrong day

### ISSUE THREAD

**Issue by jonagoldman** [nathanreyes/v-calendar#50]
![datepicker](https://user-images.githubusercontent.com/1297559/35824449-867bdff2-0a78-11e8-8396-af6cf76866ad.png)

This is taken from the example in https://vcalendar.netlify.com/datepicker.
As you can see the popover says "Sun, Oct 13, 1968" but the calendar shows "Mon, Oct 14, 1968".
This seems to happen only when you go back a few decades, let say to the 60s or 20s...

**Comment by nathanreyes** [comment]
Interesting, I'm not able to duplicate. Can you provide the following?

Browser:
`v-calendar` version # (from `package.json`):

Also, what time zone are you located? I'm wondering if this is a bug when parsing dates into certain time zones.

**Comment by jonagoldman** [comment]
Browsers:

- Chrome Version 64.0.3282.140 (Official Build) (64-bit)
- Firefox Quantum Version 58.0.1 (64-bit)

OS: Linux (Antergos)
Time Zone: EST (Eastern Standard Time)

I am testing this directly from the example in https://vcalendar.netlify.com/datepicker so I don't have access to the package.json file.
Same result in Chrome and Firefox.

**Important:** This happens only for specific dates, for example in 2018 it works fine, also in 1884 works fine, but in 1968 it fails.

**Comment by nathanreyes** [comment]
Do you have vue-devtools installed for Chrome? If so, can you inspect `VDatePicker` to see what is actually assigned for the `value` prop?

**Comment by jonagoldman** [comment]
I have vue-devtools installed, I will try to test it in a few days..

**Comment by jgandt** [comment]
I have seen a similar issue (I think it's the same issue) and it is related to timezones.

I instantiate a <v-calendar> with a set of strings in the `dates` array:
`<v-calendar :attributes="[{ key: 'today', highlight: { backgroundColor: '#ff8866' }, dates: ['2018-02-23'] }]" />`

Then in the [dateInfo utility](https://github.com/nathanreyes/v-calendar/blob/master/src/utils/dateInfo.js#L236) it calls `setHours(0, 0, 0, 0)` which effectively changes the time to the preceding day (EST). I'll see if I can come up with a viable solution.

**Comment by nathanreyes** [comment]
Ah that is a good catch and may be the culprit. I was basically using `setHours` to normalize the date value.

**Comment by anselmobattisti** [comment]
Im facing the same problem, im in Brazil and here is GMT+3 the data saved in mongodb was in UTC and , in order to solve it i add 3 hours, tnkx @nathanreyes for your suggestion

```
            let dt = new Date(element.date)
            dt.setHours(dt.getHours() + 3)
            this.attrs[0].dates.push(dt)
```

**Comment by jgandt** [comment]
PR open. I'm worried about the impact this will have on anyone who already assumes they are using a local date time. However the `new Date()` syntax always assumes UTC from what I can see so I think it would be a problem for them one way or the other.

**Comment by nathanreyes** [comment]
@jgandt Thanks for the contribution. Before I accept though, I think there is a separate issue here. Before you were entering the date in the ISO8601 YYYY-MM-DD format, which browsers now implicitly parse in UTC (for some strange reason). Case in point, if you were to use slashes instead of dashes, I believe your date should parse correctly.

Let me do some more investigation though.

**Comment by jgandt** [comment]
Ok cool. How can solve this? Is there a different code change I should make? Should I be converting all of my Dates to a local DateTime before passing them into the plugin as @anselmobattisti  has basically done?

In my testing, I agree that `new Date()` assumes/parses it into UTC/GMT/Zulu. However I think the `new Date()` parsing in combination with the `setHours` is what causes the problem. `setHours` assumes the time is in local time and then it converts it to UTC time. This behavior of `setHours()` is extremely surprising to me. I think it's just a bit idiosyncratic javascript cruft.

However, I do understand that if someone passes in a local date time, unexpected things may happen.

Thoughts?

**Comment by sempixel** [comment]
Firefox@58.0.2
v-calendar@0.7.5

Just my two cents. Timezone changes when selecting these days. It also occurs with anothers.

![capture d ecran 2018-03-07 a 15 45 06](https://user-images.githubusercontent.com/1658628/37098801-1191a01e-221f-11e8-9499-be9a37792659.png)
![capture d ecran 2018-03-07 a 15 45 18](https://user-images.githubusercontent.com/1658628/37098802-11a894f4-221f-11e8-9f8c-6c6ac8f0a69f.png)

**Comment by nathanreyes** [comment]
Looking to get this fixed ASAP.

**Comment by nathanreyes** [comment]
@jgandt I think I will parse using a custom parser as to avoid the UTC conversion problem. Then we can re-assess to see what issues are still existing.

**Comment by nathanreyes** [comment]
@jgandt Did `v0.8.0` fix your parsing issues?

**Comment by jgandt** [comment]
Yup it did! Thanks so much!

**Comment by nathanreyes** [comment]
@jonagoldman Ok I know it has been a while. Would just like to confirm to see if you are still experiencing your original bug as of `v0.8.0`.

**Comment by jonagoldman** [comment]
@nathanreyes seems fixed now! I can't reproduce the wrong day anymore. Thanks!

**Comment by nathanreyes** [comment]
Thanks. Closing this, hopefully for good.

**Comment by Earn717** [comment]
"Closing this, hopefully for good."
I'm seeing this behavior again with v2.3.4
dates: ('2022/01/18'),  // Jan 18, 2022
dates: ('2022-01-18'),  // Jan 17, 2022

**Comment by Byloor** [comment]
This behavior exists also in 1.0.8.
<img width="1084" alt="Screenshot 2022-03-07 at 10 48 58" src="https://user-images.githubusercontent.com/24357941/157007673-8c6a5a99-2745-4812-9ac8-2f11e93de823.png">

**Comment by dillingham** [comment]
@nathanreyes I think im seeing this too. Its showing a day before for day weeek and month startOf 8am EST currently

```html
<DatePicker
    v-model="range"
    :attributes="attributes"
    :timezone="timezone"
    is-expanded
    is-range
/>

 <p class="text-sm text-right py-2">
    <button @click="viewCalendar('day')">Day</button> -
    <button @click="viewCalendar('week')">Week</button> -
    <button @click="viewCalendar('month')">Month</button>
</p>
```
```js
viewCalendar(period) {
    this.range = {
        start: dayjs().tz(this.timezone).startOf(period).format('YYYY-MM-DD'),
        end: dayjs().tz(this.timezone).endOf(period).format('YYYY-MM-DD'),
    }
},
```

**Comment by waseem786** [comment]
@Byloor agree with you. 
I am also using v1.0.8 and facing the same issue. 
This not happening for all the regions. 
As I saw, if the device's local time was US time, I am getting this bug. But I am not getting this issue, if the time was set to Netherlands.
Any way to fix it without upgrading the version?
