### ISSUE TITLE
v-calendar-min.js load fails in IE11

### ISSUE THREAD

**Issue by VeenaRengarajan** [nathanreyes/v-calendar#500]
Hi Team,

Vue JS application load fails in IE 11 browser. The error in the console is at the line below (issue gets highlighted at final return n.format(t)). PFA screenshots of the error.

It is also observed that on removing the timeZone in Intl.DateTimeFormat the issue gets resolved (this was done from local for testing purposes). Request you to please take a look into the issue, and let us know the updates.

Issue causing code piece:
var s=function(t,e){var n=new Intl.DateTimeFormat(t,{month:e,timezome:"UTC"});return Object(a.j)().map(function(t){return n.format(t)})},u=function(t,e){var n=new Intl.DateTimeFormat(t,{weekday:e,timeZone:"UTC"});return Object(a.q)({utc:!0}).map(function(t){return n.format(t)})},

![v-calendar-min_Issue1](https://user-images.githubusercontent.com/44096400/72272976-87d07000-35f7-11ea-9307-6441a2d48f8c.JPG)
![v-calendar-min_Issue2](https://user-images.githubusercontent.com/44096400/72272977-87d07000-35f7-11ea-9dbc-4f6da3f615ac.JPG)

**Comment by Rickkorsten** [comment]
I have the same problemen, quick fix would be nice!

**Comment by VeenaRengarajan** [comment]
Thanks @tplesnar 
I Tried with "v-calendar": "1.0.0-beta.22" in packge.json as suggested in #487, but still the same issue is occurring.
The version we are using currently is "0.9.7". Hope that information helps further!

**Comment by esparkman** [comment]
This still seems to be an issue on the 1.0.1 release as well

**Comment by XLearner** [comment]
I got the same problem too. And I used the version of 1.0.0-beta.23. So has this problem been solved?

**Comment by nathanreyes** [comment]
Closing this issue as IE11 is not officially supported.

**Comment by XLearner** [comment]
您好，你发送的信息我已成功接收，我会尽快回复您。Lambert Yim
