### ISSUE TITLE
Selected day looses focus/style when clicking out of the calendar

### ISSUE THREAD

**Issue by benams** [nathanreyes/v-calendar#515]
When I click anywhere in the page, after selecting a date, the day number looses the circular silver background it got when selected. Am I missing a required property or style to mark the selected date? 
![image](https://user-images.githubusercontent.com/1768652/73358265-e7d93e80-42a6-11ea-9968-875345221a77.png)

As you can see in the photo, the calendar looks like nothing is selected, although: 
![image](https://user-images.githubusercontent.com/1768652/73358347-1525ec80-42a7-11ea-8de2-a83a808c3a29.png)

**Comment by woodytang** [comment]
same here

**Comment by shaks786** [comment]
anyone figured this out?

**Comment by shaks786** [comment]
I worked around it by setting a "highlight" attribute on the selected day (using the dayclick event)

**Comment by nathanreyes** [comment]
The silver/gray background is just a focus indicator. It is used for navigation and temporary listening via the `dayfocusin` event.

As @shaks786 mentioned, the appropriate thing for you to do is manually assigned attributes via the `dayclick` event. Here is an example of how this event is used with attributes to highlight multiple days as the user clicks them. 

https://vcalendar.io/examples/datepickers.html#legacy-multiple-mode
