### ISSUE TITLE
update:frompage and update:topage events does not work

### ISSUE THREAD

**Issue by mdaffan** [nathanreyes/v-calendar#520]
<vc-calendar
      :attributes="attributes"
      @update:frompage="test"
      @update:topage="test"
      is-expanded
      class="calendar"
    />
test is never getting triggered

**Comment by mdaffan** [comment]
@update:from-page="test"
@update:to-page="test"
this did work for me but it is getting emitted twice

**Comment by DonxDaniyar** [comment]
> @update:from-page="test"
> @update:to-page="test"
> this did work for me but it is getting emitted twice
> "v-calendar": "^1.0.1"

thanks! This work! For resolve emit twice you could use only from-page. It works to from and to as well

**Comment by nathanreyes** [comment]
Docs have been updated to reflect the proper use of `@update:from-page` and `@update:to-page`.
