### ISSUE TITLE
how to update inputValue?

### ISSUE THREAD

**Issue by leepro225** [nathanreyes/v-calendar#521]
![git](https://user-images.githubusercontent.com/48417191/73923182-c531d000-490d-11ea-8c17-4f466c364dd1.PNG)

Hi, I'm using range mode of v-calendar.
This is wonderful, but I found a bug.

I created a button to initialize date, and when I press that button the date's value is null.
I could see that the date value of my component has changed to null, 
but the inputValue of <vDatePicker> has not changed like the picture.
so, Placeholder' date doesn't change to 'YYYY-MM-DD'.

I really want my buttons to work. Can someone please tell me how to fix this?

**Comment by leepro225** [comment]
I found a solution

my code(it doesn't work)
range.start = null;
range.end = null;

solution(it works)
range = null;

**Comment by emad-sure** [comment]
@leepro225  Cau you help me with that , i didn't understand your solution

**Comment by BEIIKS** [comment]
Hi, i having the same issue, this one is close althrough there is no soultion for this one
