### ISSUE TITLE
popper.js 2

### ISSUE THREAD

**Issue by aparajita** [nathanreyes/v-calendar#529]
Love v-calendar, any plans to upgrade popper.js to v2? v1 is officially deprecated.

**Comment by aparajita** [comment]
This is something we'd be willing to work on, if you're interested.

**Comment by nathanreyes** [comment]
@aparajita Oh I didn't know that they had updated it. The update looks great and should really help decrease the size of v-calendar as well. Thanks for the heads up.

Let me take a deeper look at it and I'll let you know if it's something I could use some help with.

**Comment by lllopo** [comment]
This is also important by another reason, as many others are switching to 2.x and so - different versions of popper are imported, which makes the end result bigger in physical size.

**Comment by hmaesta** [comment]
Should be closed. v-calendar is using Popper.js 2.4.0 now.

https://github.com/nathanreyes/v-calendar/blob/f26fe840317b97e9196cb5dfc6d5eff6897e407c/package.json#L34

**Comment by aparajita** [comment]
@hmaesta You are correct. But it should be a dependency, not a devDependency!
