### ISSUE TITLE
Question: Is it posible to use availableDates and disableDates at the same Time?

### ISSUE THREAD

**Issue by dacxjo** [nathanreyes/v-calendar#542]
I need to use this features at the same time because my app requires dynamic date ranges and i need to disable some dates and enable between the dates ranges

**Comment by KhuramQadeer** [comment]
I also require answer for this

**Comment by KhuramQadeer** [comment]
You can use this 2 method for this, i have resolved this issue by custom solution, i am using only available-dates property in which i can get by our filter dates by step 1 and convert into again object that's i need :)

**Step 1)**
**// this fun give you single dates array like ['07/10/2020','07/11/2020','07/12/2020','07/13/2020',]**
function getAllDatesBetween($startDate, $endDate, $format = 'm-d-Y')
{
    $dates = [];
    $current = strtotime($startDate);
    $date2 = strtotime($endDate);
    $stepVal = '+1 day';
    while ($current <= $date2) {
        $dates[] = date($format, $current);
        $current = strtotime($stepVal, $current);
    }
    return $dates;
}

**Step 2)**
**// this function is most important it will convert dates into start date and end date by month like {start: '07/10/2020',end:'07/13/2020}**

function convertDatesArrayToStartEndObject($allDates, $explodeBy = '-')
{
    $res = [];
    $prevIndex = null;
    $start = $end = $current_day = $current_month = $prev_month = $nextDay = '';
    if ($allDates) {
        foreach ($allDates as $i => $allDate) {
            $current_month = (int)explode($explodeBy, $allDate)[0];
            $current_day = (int)explode($explodeBy, $allDate)[1];
            if ($i == 0) {
                $start = str_replace($explodeBy, '/', $allDate);
                $end = str_replace($explodeBy, '/', $allDate);
                $prevIndex = $i;
                $res[$prevIndex] = ['start' => $start, 'end' => $end];
            } else {
                $end = str_replace($explodeBy, '/', $allDate);
                if ($current_month == $prev_month && $current_day == $nextDay) {
                    $res[$prevIndex] = ['start' => $start, 'end' => $end];
                } else {
                    $prevIndex = $i;
                    $start = str_replace($explodeBy, '/', $allDate);
                }
            }
            $nextDay = $current_day + 1;
            $prev_month = $current_month;
        }

        //        index sorting
        $datesIndexSorted = [];
        if ($res) {
            foreach ($res as $item) {
                if ($item['start'] && $item['end'])
                    array_push($datesIndexSorted, ['start' => $item['start'], 'end' => $item['end']]);
            }
        }
        $res = $datesIndexSorted;
    }
    return $res;
}
