### ISSUE TITLE
Popover does not work

### ISSUE THREAD

**Issue by paulk4633** [nathanreyes/v-calendar#544]
Hello,

I am trying to build a form and need a Datepicker the problem is that the v-calendar date picker is always expanded. I was trying to collapse it with the popover attribute but it completely ignores it.

Config:
![Code_dXq7bvHjN3](https://user-images.githubusercontent.com/36262086/77914108-b3c5ce00-7295-11ea-8318-1b8c625c8f17.png)
Code:
![Code_m9bM5qGbUg](https://user-images.githubusercontent.com/36262086/77914161-c9d38e80-7295-11ea-8c8b-0d27ed7acecc.png)
Result:
![msedge_vu8rf5Fl9Q](https://user-images.githubusercontent.com/36262086/77914275-f38cb580-7295-11ea-821f-3d9bee745212.png)

**Comment by webcoderkz** [comment]
How do you fixed this? I just face the same issue, calendar is always shown.

**Comment by paulk4633** [comment]
I used the date-picker instead

**Comment by webcoderkz** [comment]
This you mean?

```
<v-date-picker
  mode="range"
  v-model="date"
  :popover="{ placement: 'bottom', visibility: 'click' }"
/>
```

It's always expanded for me.

**Comment by paulk4633** [comment]
`<vc-date-picker v-model="editedItem.date" :popover="{ placement: 'bottom', visibility: 'click' }" id="datePicker" label="Datum"></vc-date-picker>`

**Comment by webcoderkz** [comment]
In an entry file:

```
import VCalendar from 'v-calendar'
Vue.use(VCalendar)
```

is it correct?

**Comment by paulk4633** [comment]
```
Vue.use(VCalendar, {
  componentPrefix: 'vc',
  titlePosition: 'left'
});
```
I have it like that to ensure that the right date picker gets used
