### ISSUE TITLE
Does not update range deletion

### ISSUE THREAD

**Issue by FrediChegne** [nathanreyes/v-calendar#546]
When I delete a range this is not reflected in the v-date-picker until another date is clicked, this doesn't happen in version 0.9.7 but that version doesn't have many features.

Please appreciate if anyone could help me.

**Comment by nathanreyes** [comment]
Could you provide an example of how you are doing this? Maybe I can see why it is not working for you.

**Comment by FrediChegne** [comment]
Of course: 

https://jsfiddle.net/fredichegne/0azhw59u/2/

The same code with using version 0.9.7 works correctly.

**Comment by DonxDaniyar** [comment]
> Of course:
> 
> https://jsfiddle.net/fredichegne/0azhw59u/2/
> 
> The same code with using version 0.9.7 works correctly.

+1 to this issue. When i dynamically add range to date-picker this not show before i click date. When i click all shows correctly. Thanks!

**Comment by nathanreyes** [comment]
Ah, I see. Modifying just the `dates` doesn't trigger a change detection in Vue. You need to do something like like to basically say "this is the new set of attributes to use".
```js
onUpdateClick() {
      // this.attributes[0].dates.pop(); This won't trigger change detection
      const attributes = [...this.attributes];
      attributes[0].dates.pop();
      this.attributes = attributes;
}
```

**Comment by DonxDaniyar** [comment]
> Ah, I see. Modifying just the `dates` doesn't trigger a change detection in Vue. You need to do something like like to basically say "this is the new set of attributes to use".
> 
> ```js
> onUpdateClick() {
>       // this.attributes[0].dates.pop(); This won't trigger change detection
>       const attributes = [...this.attributes];
>       attributes[0].dates.pop();
>       this.attributes = attributes;
> }
> ```

I use v-if to retrieve data and enable view. Everything works! Hope fix this in next versions! Thanks!

**Comment by FrediChegne** [comment]
Thanks for your support, probe indicates it and I solve my problem.
