### ISSUE TITLE
Change color of days during dragging in Date Picker

### ISSUE THREAD

**Issue by wotaen** [nathanreyes/v-calendar#55]
My default "selected" stage has deep blue background color with white foreground color. I'd like to keep it the same for days during drag...but it's not possible at the moment:

![vyber_074](https://user-images.githubusercontent.com/715052/35915313-a487fff0-0c06-11e8-88d3-c1af4f01060d.png)

**Comment by nathanreyes** [comment]
If you would like to customize more than just the `select-color` or `drag-color`, you can customize the drag and select attributes like so:

```html
  <v-date-picker
    mode='range'
    v-model='myDate'
    :drag-attribute='dragAttr'
    :select-attribute='selectAttr'
    is-inline> 
  </v-date-picker>
```
```javascript
export default {
  data() {
    return {
      myDate: null,
      dragAttr: {
        contentStyle: {
          color: 'white',
        },
        highlight: {
          height: '26px',
      	  backgroundColor: 'blue',
          opacity: 0.6
        }
      },
      selectAttr: {
        contentStyle: {
    	  color: 'white',
        },
        highlight: {
      	  backgroundColor: 'blue'
        }
      }
    }
  }
}
```

Here is a [fiddle] that might help you out. Apologies, this will be more documented when the new docs site rolls out in a few days.

**Comment by fgzetech** [comment]
I have a similar problem with datepicker styles and @nathanreyes code didn't work.
