### ISSUE TITLE
cancel drag

### ISSUE THREAD

**Issue by peachykeeen** [nathanreyes/v-calendar#550]
Hi,
when using the datepicker in the mode='range', is there a way how to programatically unselect (or cancel) dragged range? What I am trying to achieve is the same as clicking 'esc' button after starting a drag, but programatically

I know I can cancel the range of selected dates by setting the :value=null, but how can I cancel the drag before actually selecting the dates?

thanks for any advice

Jan

**Comment by nathanreyes** [comment]
Sure. This is a rather contrived example but it clears the `dragValue` on the datepicker component 3 seconds after you start dragging.

```html
<v-date-picker mode="range" is-inline :value="value" @drag="onDrag" ref="picker"/>
```

```js
export default {
  name: "App",
  data() {
    return {
      value: null
    };
  },
  methods: {
    onDrag(dragValue) {
      if (dragValue) {
        setTimeout(() => {
          this.$refs.picker.dragValue = null;
        }, 3000);
      }
    }
  }
};
```

**Comment by nathanreyes** [comment]
Closing but let me know if this doesn't work for you.
