### ISSUE TITLE
How to: DatePicker Move Method

### ISSUE THREAD

**Issue by rebz** [nathanreyes/v-calendar#552]
Is it possible to use the Calendar `.move` method on the DatePicker? Can't find any documentation or issues related.

**Comment by nathanreyes** [comment]
Yes you'll need to access the calendar ref inside it though.
```html
<v-date-picker v-model="date" ref="picker" />
```
```js
/// Somewhere in your methods, move to the next month
this.$refs.picker.$refs.calendar.move(1)
```
I'll probably add some transparent wrapper calls to remove the extra layer calls.

**Comment by rebz** [comment]
@nathanreyes - This works. Thank you!

**Comment by tchret** [comment]
@nathanreyes what about the `focusDate` method?

**Comment by nathanreyes** [comment]
You can access it the same way.
