### ISSUE TITLE
Masks do not work

### ISSUE THREAD

**Issue by rebz** [nathanreyes/v-calendar#555]
Having tried both mask types below:
```
:masks="{
    input: 'YYYY-MM-DD',
    L: 'YYYY-MM-DD',
}"
```

Clicking on Jan 1, 2020 in the DatePicker produces:
`Wed Jan 01 2020 00:00:00 GMT-0500 (Eastern Standard Time)`

The output of dates continues to come back in its default format.

I see there are other issues on this repo discussing the same.

**Comment by nathanreyes** [comment]
So currently the date picker just emits Javascript dates in the `input` event. The masks are merely for formatting and parsing via the input control element.

See [this reply](https://github.com/nathanreyes/v-calendar/issues/269#issuecomment-615956728). I think it can help you accomplish what you need.

**Comment by EnzoBatista** [comment]
@rebz I GOT IT!!

Just use moment js

1- In your template you should use v-model to save the date from v-date-picker component

2- Import moment js to give the format that you want:
import moment from 'moment'

3- Define a filter like this:

filters: {
    date_format (date) {
      return moment(String(date)).format('DD-MM-YYYY')
    }
  },

3- Print your date:
yourDate | date_format

Let me know if works for you

**Comment by nathanreyes** [comment]
As of `2.0`, you can use the [`model-config`](https://vcalendar.io/datepicker.html#strings) prop to bind to a string with a given mask.

**Comment by markadrake** [comment]
Apologize for commenting on this closed issue. I came here when searching for a way to set this as a default, so all date pickers on the site use the same `model-config` as you pointed out @nathanreyes. 

So this gets the job done:

```
<v-date-picker v-model="fromDate"
	:model-config="{type: 'string', mask: 'MM/DD/YYYY'}">
```

But I'd very much like to do this instead:

```
import VCalendar from "v-calendar";
Vue.use(VCalendar, {
	modelConfig: {
		type: 'string', 
		mask: 'MM/DD/YYYY'
	}
});
```

I suppose either it's not possible to set this default, or I've butchered the config / setup option here.

**Comment by laurensiusadi** [comment]
This does not work: `:model-config="{ mask: 'MM-YYYY' }"`
This what works: `:locale="{ masks: { input: 'MM-YYYY' } }"`
Based on this computed https://github.com/nathanreyes/v-calendar/blob/a4e9bceb168aa302eeff5143d41d057c1c5ee547/src/components/DatePicker.vue#L204-L212
