### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by Wilson-Lim** [nathanreyes/v-calendar#559]
When i try to use Component methods, receive the following error : 

![image](https://user-images.githubusercontent.com/15623614/79202055-971bbf80-7e6b-11ea-8e9b-6eb4ddf46d68.png)

usage : 
![image](https://user-images.githubusercontent.com/15623614/79202088-a69b0880-7e6b-11ea-877f-5a936f096c92.png)

**Comment by rlfrahm** [comment]
I just ran into this issue. The problem is that this library doesn't support SSR and so you have to add the plugin as a client side only plugin. For Nuxt this looks like: https://nuxtjs.org/guide/plugins#client-side-only

First, create a plugin file in the plugins folder, call it something like `plugins/client-only-plugin.js`:

```javascript
import Vue from 'vue'
import DatePicker from 'v-calendar/lib/components/date-picker.umd'

Vue.component('DatePicker', DatePicker)
```

Then, add this plugin to Nuxt via the `plugins` array in `nuxt.config.js`:

```javascript
plugins: [
    { src: '~/plugins/client-only-plugin.js', mode: 'client' }
]
```

And it should work as expected!

**Comment by Shuky** [comment]
> I just ran into this issue. The problem is that this library doesn't support SSR and so you have to add the plugin as a client side only plugin. For Nuxt this looks like: https://nuxtjs.org/guide/plugins#client-side-only
> 
> First, create a plugin file in the plugins folder, call it something like `plugins/client-only-plugin.js`:
> 
> ```js
> import Vue from 'vue'
> import DatePicker from 'v-calendar/lib/components/date-picker.umd'
> 
> Vue.component('DatePicker', DatePicker)
> ```
> 
> Then, add this plugin to Nuxt via the `plugins` array in `nuxt.config.js`:
> 
> ```js
> plugins: [
>     { src: '~/plugins/client-only-plugin.js', mode: 'client' }
> ]
> ```
> 
> And it should work as expected!

True, but this prevents code splitting the v-calendar components out of the main bundle.
Since the current size is substantial fixing the bug would help splitting it from the vendors.js file and lazy load it when needed (nuxt client plugins are currently bundled to the main bundle)

**Comment by Wilson-Lim** [comment]
i use AsyncComponent to solve the problem

```
export default {
  components: {
    DatepickerC: () => import("v-calendar/lib/components/date-picker.umd")
  },
}
```

```
 <datepicker-c v-if="mounted" />
```

mounted will only be true on window loaded event or referer url is not null ( this is to make sure redirection taken place at client side )

**Comment by tillsanders** [comment]
I noticed that this is probably related to #823.
