### ISSUE TITLE
auto/default popover from date selection breaks site layout

### ISSUE THREAD

**Issue by huenisys** [nathanreyes/v-calendar#56]
How can I disable this [popover](https://www.screencast.com/t/IAOlBVTa)?

When it's shown, it breaks the bootstrap 4 layout, affecting the fixed-top and fixed-footer elements. It seems to add extra elements in the body that affects viewport sizing.

**Comment by nathanreyes** [comment]
I'm not sure I understand what issues you are having with layout, but you can disable the popover by setting the `show-popover` to false.

**Comment by huenisys** [comment]
Thank you.

**Comment by nathanreyes** [comment]
If you have any other issues, feel free to reopen.
