### ISSUE TITLE
Passing Data into the DatePicker

### ISSUE THREAD

**Issue by tonexv** [nathanreyes/v-calendar#564]
How do I pass a date from a database or a Laravel variable as the default value date? I'm using the datepicker as a picker of birthdate (single date). Thanks.

**Comment by tonexv** [comment]
I tried this but the props just return undefined:

customer.blade.php
`<date-component :nathan="hahay" terran="naku"></date-component>`

DateComponent.vue
`<template>
    <datepicker v-model="date" color="yellow" :input-props='{name: "birthdate", class: "form-control"}'></datepicker>
</template>
<script type="application/javascript">
//import DatePicker from 'vuejs-datepicker'; //This also works but v-calender is more elegant.
import DatePicker from 'v-calendar/lib/components/date-picker.umd';

    export default {
        props: ['nathan', 'terran'],
        data() {
            return {
                // date: new Date(2020, 0, 25) //this works but i need the value to come from the blade file
            }
        },
        components: {
            datepicker:DatePicker
        },
        mounted() {
            console.log(this.nathan); // undefined
            console.log(this.terran); // undefined
        }
    }
</script>
`

**Comment by vasilestefirta** [comment]
See this comment https://github.com/nathanreyes/v-calendar/issues/345#issuecomment-646336009
