### ISSUE TITLE
Error: Invalid Date in fecha.format

### ISSUE THREAD

**Issue by JoseIPacheco** [nathanreyes/v-calendar#565]
After updating to version 1.0.4, the error was presented (**Error: Error: Invalid Date in fecha.format**)

**Comment by nathanreyes** [comment]
How are you using the plugin that is prompting this? Are you using custom masks? Just the date picker?

**Comment by JoseIPacheco** [comment]
I share a screenshot
<img width="693" alt="Captura de Pantalla 2020-04-18 a la(s) 5 52 34 p m" src="https://user-images.githubusercontent.com/60112755/79673173-85a12300-819d-11ea-8d31-5840b0c8952d.png">

and the code snippet

<div v-bind:class="{'hidden':visible, 'my-posicion-absoluta calendario my-index-1':true}">
            <Calendar></Calendar>
        </div>
    </div>
</template>

<script>
import EventBus from './../../bus'

import Calendar from 'v-calendar/lib/components/calendar.umd'

export default {
    components: {
        Calendar
    },

and I'm not using any kind of customization.
in fact he noticed the same problem on his official site

https://vcalendar.io/

**Comment by nathanreyes** [comment]
What locale is configured in your browser? chrome://settings/languages at the top of the list.

**Comment by nathanreyes** [comment]
Ah found it. There is a missing 'first day of week' setting for the Spanish (Mexican) locale.

**Comment by nathanreyes** [comment]
@JoseIPacheco Before I patch this can you verify that the home page is working now?

**Comment by JoseIPacheco** [comment]
Verified Chrome browser from Mexico
<img width="1437" alt="Captura de Pantalla 2020-04-22 a la(s) 12 27 44 a m" src="https://user-images.githubusercontent.com/60112755/79944079-49d1bc00-8430-11ea-9a1d-a567ff8906d5.png">
