### ISSUE TITLE
this happend only in mobile Error: Invalid Date in fecha.format

### ISSUE THREAD

**Issue by Jackermaster** [nathanreyes/v-calendar#566]
im use vcalendar, in web mode its fine, but in device mobile i have this error. Somebody know happens. Support me please :D

**Comment by nathanreyes** [comment]
Possible dupe of #565. Does this continue as of `v1.0.6`?

**Comment by Jackermaster** [comment]
> Possible dupe of #565. Was it for Spanish (Mexican) locale? If so, it should be fixed as of `v1.0.6`?

Yes. Thank you. im a fool, i thought this was a default setting in my cell phone
