### ISSUE TITLE
Multiple date ranges in datepicker

### ISSUE THREAD

**Issue by aXent** [nathanreyes/v-calendar#57]
Hi,

I got a feature request. Maybe it's already possible but I don't seem to get it working. 

Is there a way to allow multiple date range selections on the date picker? Now if you pick multiple you can pick multiple days, but if you choose range, you can't select multiple ranges.

**Comment by nathanreyes** [comment]
You are correct, there is no way to currently do what you are asking.

There are some concerns for me about implementing this feature. For one, how would you know if the user would like to pick another range or simply modify the current selection. There would need to be a way of 'grabbing' the existing selection and deleting it.

Not saying it couldn't be done, but not sure if it could be done well without making it more complicated for the common use case (single range selections).

I'm open to suggestions though.

**Comment by nathanreyes** [comment]
I'm going to shelf this for now, at least until I can settle on a way to easily remove selections using the picker. Feel free to continue to contribute with your own ideas if you would like.

**Comment by milkabe** [comment]
Very looking forward to have this ^^
