### ISSUE TITLE
The year will be disabled when the min date is set to June or later

### ISSUE THREAD

**Issue by cycadas** [nathanreyes/v-calendar#578]
When using single date picker and the min date is set to June onward, the year for that period will not be able to select on year selection menu.

E.g.: Min date is 1st of June 2018, the year 2018 will be disabled on the year selection menu. Even though the second half of 2018 is valid date. Workaround is to select 2019, and then click on the previous year arrow to go to 2018. 

User might not know this workaround and therefore won't be able to select their desired date.

![disabled 2018](https://user-images.githubusercontent.com/16488642/81467617-721d3100-920c-11ea-8973-abf6ca315548.PNG)
![workaround 2018](https://user-images.githubusercontent.com/16488642/81467622-7a756c00-920c-11ea-85ea-071cf7226ff1.PNG)

**Comment by nathanreyes** [comment]
This bug should be fixed as of 2.2.1
