### ISSUE TITLE
Changing month changes day and vice versa

### ISSUE THREAD

**Issue by IsmailMouh** [nathanreyes/v-calendar#58]
When i change the month or the day in the input of the datepicker it changes the inverse of it

**Comment by nathanreyes** [comment]
Date.parse favors US (MM/DD/YYYY) format over non-US (DD/MM/YYYY) forms. Are you expecting it to be in DD/MM/YYYY format?

**Comment by IsmailMouh** [comment]
Exactly what shoud i do to keep it in  (DD/MM/YYYY) format?

**Comment by nathanreyes** [comment]
You can provide your own `dateFormatter` and `dateParser` functions to do as you would like. For example, you could import momentjs into your project and use it for parsing and formatting.

I could probably add an example to the docs site if you think that would help.

**Comment by IsmailMouh** [comment]
I would love an example with moment , thank you

**Comment by IsmailMouh** [comment]
I tried everything the dateParser attribut is not changing. but the dateFormatter is working with : 
dateFormatter: d => moment(d).format('DD-MM-YYYY'),

**Comment by nathanreyes** [comment]
Here is a [jsfiddle](https://jsfiddle.net/nathanreyes/9s099kd5/) that might help for now.

**Comment by IsmailMouh** [comment]
Thank you so much, it worked fine in my test project, but when i tried to do the same in a bigger project i work on it did not ( we are currently using this : charliekassel/vuejs-datepicker , but we can't change dates with keyboard like your plugin).

**Comment by nathanreyes** [comment]
So was my proposed fix sufficient for your bigger project?

I'm curious, is editing the dates via the keyboard an important feature for you? I ask because I have considered making input controls readonly (removing parsing feature).

**Comment by IsmailMouh** [comment]
no it wasn't sufficient , i really dont know why maybe because we have tons of other libraries.

For editing dates with keyboard. the client asked for it ( he wants to both pick a date or changing it with his keyboard like in the input type="date" ).

**Comment by nathanreyes** [comment]
Ok. I would say keep an eye on future releases. I'm looking into including parsing and formatting functionality out-of-the-box. It would make the package size larger, but it may be worth it if you can just supply a *DD/MM/YYYY* format and everything is taken care of.

Until then, I'll close this issue. If you find another problem with the plugin that is causing issues with your larger project, feel free to open another issue.

**Comment by nathanreyes** [comment]
@IsmailMouth `v-calendar` should now detect your locale and use the appropriate format for date formatting and parsing. However, you can also manually specify your own format if you wish. Reference the [docs](https://docs.vcalendar.io#formatting--parsing) for details.

**Comment by IsmailMouh** [comment]
Hi, what should i do to test this? just npm update?

**Comment by nathanreyes** [comment]
Yes you can run `npm update`. Just make sure that `v-calendar` displays `0.7.1` or `v0.7.1` as the installed version. Might be good to take a look at the [breaking changes](https://github.com/nathanreyes/v-calendar/blob/master/CHANGELOG.md) first. For example, `month-labels`, `weekday-labels`, `dateFormatter` and `dateParser` are deprecated in favor of the new `format` rules.

**Comment by IsmailMouh** [comment]
npm install v-calendar installs the 0.6.3 version.

**Comment by nathanreyes** [comment]
Type in the version manually in `package.json` to `0.7.1` and run `npm install`

**Comment by IsmailMouh** [comment]
you know what brother, the parser did not work in my bigger app because i were using the 0.5.5. when i changed to the 0.6.3 everything is working fine, the datepicker is just perfect. I m gonna using now in every pages and show it tommorow to the client.
can't thank you enough
