### ISSUE TITLE
Docs issue: no mention of the fact that Attributes need Popover attrs in order to use scoped slot

### ISSUE THREAD

**Issue by sethjamesofficial** [nathanreyes/v-calendar#588]
In the documentation concerning the scoped slot usecase for popovers on the calander, there is no mention of the fact that an Attribute needs to have a Popover declared with at least one option declared in order for the scoped slot to function for that given Attribute.

Example:

If the v-calendar were included as such:
```javascript
<v-calendar
  :attributes="attributes"
  >
  <div slot="day-popover" slot-scope="">
    Using my own content now
  </div>
</v-calendar>
```

then the attributes declared like so:

```javascript
export default {
  data() {
    return {
      attrs: [
        {
          key: 'today',
          highlight: true,
          dates: new Date(),
        },
      ],
    };
  },
};
```

would not show the popover declared in the scoped slot. Instead, something like this would be needed in order to show the scoped slot:

```javascript
export default {
  data() {
    return {
      attrs: [
        {
          key: 'today',
          highlight: true,
          popover: {
            visibility: hover,
          },
          dates: new Date(),
        },
      ],
    };
  },
};
```

This is not made clear in the documentation. I hope my example was clear enough

**Comment by nathanreyes** [comment]
Very clear. Hope the [updated example](https://vcalendar.io/attributes.html#_2-scoped-slot) helps.
