### ISSUE TITLE
Select days of current month

### ISSUE THREAD

**Issue by olasunkanmi04** [nathanreyes/v-calendar#595]
Using v-date-picker, is there a way I can select all the days in a month at once when a boolean is true? Something similar to weekday:[1, 7] but for a month and just the current month.

**Comment by tafelnl** [comment]
I am not 100% certain what you mean by this. But if you mean that you can programmatically check all the dates of a month. As in for example when the current month is June: a range from 1st of June until the 30th of June. Yes that is possible.

You can make this yourself. For example using the` mode='range'` in combination with` v-model` Just calculate the first and last day of the current month.

According to [this stackoverflow answer](https://stackoverflow.com/a/13572682/8634342) you can do that as follows:

```
var date = new Date();
var firstDay = new Date(date.getFullYear(), date.getMonth(), 1);
var lastDay = new Date(date.getFullYear(), date.getMonth() + 1, 0);
```

This can result in the following code:

```
<v-date-picker
  mode='range'
  v-model='range'
  />
```

```
export default {
  computed: {
    range() {
      return {
        start: this.firstday,
        end: this.lastday
      };
    },
    firstday() {
      var date = new Date();
      var firstDay = new Date(date.getFullYear(), date.getMonth(), 1);
      return firstDay;
    },
    lastday() {
      var date = new Date();
      var lastDay = new Date(date.getFullYear(), date.getMonth() + 1, 0);
      return lastDay;
    },
  }
}
```
