### ISSUE TITLE
Problem with highlighting

### ISSUE THREAD

**Issue by bobsutton** [nathanreyes/v-calendar#596]
Hi - great work - my first project with this component.  I am a very experienced developer but this is driving me crazy!

Whenever I pass highlights to the calendar as an array of attribute objects, the background styling is simply ignored!  Curiously, the highlights appear in the right places and I can apply custom popovers without a problem - but no matter what I do I can't change the colour. I thought maybe it was a name clash, so used a different prefix.  I have tried inspecting the style which always appears as :
.vc-bg-blue-600

I have even tried overriding this color with an !important tag but nothing works.

I have tried using "highlight : 'some-class'" and then defining some-class directly in my component, but that just results in the same old blue highlight.

If I take the attribute array away and then use, per your example 
        {
          key: 'today',
          highlight: 'red',
          dates: new Date(),
        },
The highlight changes just fine
If I change to 
        {
          key: 'today',
          highlight: '#000000',
          dates: new Date(),
        },
The highlight vanishes completely!!

Clearly this is one of the most excellent features of this component which I would not hesitate to recommend just because it is so flexible and well conceived.  Except right now I can't make it work!!

Any pointers would be appreciated.  Meantime I will continue scratching my head and if all else fails I will have to resort to using something else, or rolling my own.

All best!!

**Comment by bobsutton** [comment]
So instead of rolling my own colours, which would have been great, I have stuck with the out of the box standards.  Great.  I now have a calendar displaying highlighted dates - not the colours I would like, but nonetheless great.  Only trouble is???  I can't find any way of trapping the event when the user clicks a date. @click - nothing.  v-model - nothing.  If I use the date picker, the events I expect are trapped, but this is not what I want.  I want to display a calendar and have something happen when I click on a date - which should be really easy...

I suspect this is a brilliant piece of kit - and I would never mean to denigrate all this hard work.  But what it lacks is in-depth documentation.  Being able to access the events when someone clicks on the calendar dates has surely to be a very basic function - it's just that there are no code examples or documentation to explain how it is done and I am still drawing a blank.

Once again - your help would be hugely appreciated.

**Comment by aziev** [comment]
@bobsutton
I also wanted to have `v-model` on `<v-calendar/>`, but as you said it doesn't work. So I just used
```vue
<v-date-picker
    is-inline
    v-model="selectedDate"
/>
```

This package really needs better documentation

**Comment by nathanreyes** [comment]
@bobsutton You can use the `dayclick` event. https://vcalendar.io/api/calendar.html#dayclick

**Comment by nathanreyes** [comment]
Also, you can apply your own `class` and `contentClass` if you provide an object as the `highlight` property of the attribute. The `class` gets applied to the background and the `contentClass` gets applied to the content (day number). https://vcalendar.io/attributes.html#highlights

**Comment by nathanreyes** [comment]
If you handle the `dayclick` event and provide your own modified attributes you can effectively just use the calendar and treat it as a your own picker.
