### ISSUE TITLE
How to disable today's date?

### ISSUE THREAD

**Issue by FreddyCrugger** [nathanreyes/v-calendar#599]
Hello,

Based on your doc I am a bit confused on how to disable any dates until tomorrow, ie: my users should only be able to choose tomorrow(and any days after tomorrow.
How to combine this with "disabled-dates=" please?

Thank you.

**Comment by tafelnl** [comment]
```
<v-date-picker
  v-model='date'
  :min-date='new Date()'
  is-inline
  />
```

docs: https://vcalendar.io/dates.html#_1-explicitly-via-min-date

**Comment by FreddyCrugger** [comment]
Thank you so much! It is working perfectly, I spend to much time looking for this....
