### ISSUE TITLE
DatePicker closes on any click

### ISSUE THREAD

**Issue by leeniu** [nathanreyes/v-calendar#602]
Greetings and thanks for the work on this plugin.

In my application I noticed some unwanted behavior. In short: The date picker closes instantly on any click. I am not able to navigate through months or open the year navigation.

I made a small gif to illustrate the issue:

![v-calendar-instant-close](https://user-images.githubusercontent.com/15927396/83115273-6c5b9280-a0ca-11ea-8ec4-64fcfe7cc8cb.gif)

I use the component like this:

```
                    <v-date-picker
                        locale="de"
                        titlePosition="left"
                        v-model="form.dueDate"
                        :first-day-of-week="2"
                        :popover="{
                            visibility: 'click',
                            keepVisibleOnInput: true
                        }"
                        :input-props="{
                            class: 'form-input block w-full rounded-none mt-1',
                            placeholder: '00/00/2019'
                        }"
                    />
```

Please let me know what more information I can provide.

Thank you for taking the time.

**Comment by yofret** [comment]
I'm having the same issue with the `:popover` prop, it makes the calendar wildly inconsistent

**Comment by nathanreyes** [comment]
Sorry for late reply but this should be fixed as of latest versions. Please advise of any other issues seen.
