### ISSUE TITLE
Broke date-picker after last update

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#61]
Inline date-picker range mode isn't working. After selecting the first day, the entire site freezes. Can you check this @nathanreyes?

**Comment by nathanreyes** [comment]
Are you referring to the [new site](https://vcalendar.io)?

**Comment by luiztsmelo** [comment]
No, my site

**Comment by nathanreyes** [comment]
Would you mind posting the configuration for your `v-date-picker`? There were some [breaking changes](https://github.com/nathanreyes/v-calendar/blob/master/CHANGELOG.md) made in the latest update.

**Comment by luiztsmelo** [comment]
```
<v-date-picker
    is-inline
    mode='range'
    v-model='dataReservaAcomod'
    :drag-attribute='myAttribute'
    :select-attribute='myAttribute'
    :disabled-attribute='myAttribute'
    :available-dates='{start: new Date(), end: null}'
    :month-labels='monthLabels'
    :weekday-labels='weekdayLabels'
    :theme-styles='themeStyles'
    select-color='#00D8C7'
    show-caps
    drag-color='#00D8C7'>
</v-date-picker>
```

```
data() {
    return {
      dataReservaAcomod: null,
      myAttribute: {
        popover: {
          hideIndicator: true,
          component: PopoverReservaAcomod
        },
      },
      monthLabels: ['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'],
      weekdayLabels: ['D', 'S', 'T', 'Q', 'Q', 'S', 'S'],
      themeStyles: {
        wrapper: {
          color: 'rgb(62, 62, 62)',
          border: '0',
          padding: '6px 9px 0 9px',
          background: 'white',
          width: '100%',
          minHeight: '300px'
        },
        header: {
          padding: '0 9px',
        },
        headerArrows: {
          fontSize: '1.4rem',
        },
        headerTitle: {
          fontSize: '16px',
          fontWeight: '400'
        },
        weekdays: {
          color: 'rgb(62, 62, 62)',
          fontWeight: '700',
          padding: '15px 5px 8px 5px',
        },
        dayCell: {
          height: '30px'
        },
        dayContent: {
          fontWeight: '400',
          fontSize: '15px',
        },
        dayPopoverContent: {
          background: '#00D8C7',
          color: 'white',
          border: 'none'
        },
      } 
    }
  },
```

**Comment by XristMisyris** [comment]
i have the same problem with the new version on desktop win10, chrome 64.0.3282.140. After selecting the end date on rangepicker my site freezes

**Comment by nathanreyes** [comment]
I believe it may be a problem with using `available-dates`. A new prop `min-date` was added...can you try using it until I can track the issue down?
```html
<v-date-picker
  ...
  :min-date='new Date()'>
</v-date-picker>
```

**Comment by nathanreyes** [comment]
Ok, I think the problem is rooted in assigning the dates in the template. I think you need to create a new data variable called `availableDates` (or whatever you want) and bind to the prop via
```html
<v-date-picker
  :availableDates='availableDates'>
</v-date-picker>

Vue may not like creating dates in templates. I'll investigate, but see if that works for you.

**Comment by luiztsmelo** [comment]
Worked!

**Comment by nathanreyes** [comment]
It turns out there is a bug though that this has uncovered. Declaring dates within the template (your old code) should work after I issue this hotfix. Until then, just use the method we discussed.

**Comment by luiztsmelo** [comment]
Ok. Thanks

**Comment by nathanreyes** [comment]
Please advise if latest patch allows you to use your original code.

**Comment by luiztsmelo** [comment]
Continued the same behavior @nathanreyes, but now I can see the loop on console.

**Comment by luiztsmelo** [comment]
![bug](https://user-images.githubusercontent.com/11582056/36064354-f2c20ce4-0e70-11e8-99bf-d5712935d963.jpg)

**Comment by haringsrob** [comment]
> Ok, I think the problem is rooted in assigning the dates in the template. I think you need to create a new data variable called `availableDates` (or whatever you want) and bind to the prop via
> 
> ```
> <v-date-picker
>   :availableDates='availableDates'>
> </v-date-picker>
> ```
> 
> Vue may not like creating dates in templates. I'll investigate, but see if that works for you.

This should be documented somewhere or be put as a disclaimer. Took me quite some time to figure this out (find this issue).
