### ISSUE TITLE
Pick the same day

### ISSUE THREAD

**Issue by raop155** [nathanreyes/v-calendar#611]
I have this issue, i read the docs and didnt find any solution.
I pick a day (ok), then i pick the same day again and it deselect, i think its a default behavior, but i dont want to "deselect" the day if it its the current select date.

Its there any solution to this?

Thanks

**Comment by SimonFricker** [comment]
+1

**Comment by n1k1t0ss** [comment]
I found that if you use `:is-required="true"` property, than current day wouldn't be deselected. By I faced with another problem - when clicking on date, calendar won't hide - so you have to click outside to close it or select another date. This seems to be calendar thinks that you want to deselect the last day and prevents it. Its ok for multiple mode, but for a 'single' mode, I think that this is a bug, and calendar should be close after clicking on that date.

**Comment by raop155** [comment]
thanks @n1k1t0ss .
It works for what i want.
