### ISSUE TITLE
date range 2 hours the day before

### ISSUE THREAD

**Issue by gweit** [nathanreyes/v-calendar#617]
Hi,

when i use the date picker the result of the output range is 2 hours before the selected one:

**I select:**

2020-06-04 - 2020-06-06

**i get:**

"range": { "start": "2020-06-03T22:00:00.000Z", "end": "2020-06-05T22:00:00.000Z" }

is this a known bug or am i mistaking somewhere?

I use "v-calendar": "^1.0.0-beta.23"

```
              <vc-date-picker
                :columns="$screens({ default: 1, lg: 2 })"
                :is-expanded="$screens({ default: false, lg: true })"
                mode='range'
                v-model="range"
              />
```

**Comment by henriquecm** [comment]
This is probably due to timezones

**Comment by BJ4K3** [comment]
> Hi,
> 
> when i use the date picker the result of the output range is 2 hours before the selected one:
> 
> **I select:**
> 
> 2020-06-04 - 2020-06-06
> 
> **i get:**
> 
> "range": { "start": "2020-06-03T22:00:00.000Z", "end": "2020-06-05T22:00:00.000Z" }
> 
> is this a known bug or am i mistaking somewhere?
> 
> I use "v-calendar": "^1.0.0-beta.23"
> 
> ```
>               <vc-date-picker
>                 :columns="$screens({ default: 1, lg: 2 })"
>                 :is-expanded="$screens({ default: false, lg: true })"
>                 mode='range'
>                 v-model="range"
>               />
> ```

Hi @gweit , I've resolved in this way, as @henriquecm said is a timezone problem:

- installed moment.js library
- added the following strings to the code, the output format here is in unix timestamp (seconds), obviously you can change it:

```
var date_start = moment(this.selectedDate.start).add(moment(this.selectedDate.start).utcOffset(), 'm').utc().format("X")
var date_end = moment(this.selectedDate.end).add(moment(this.selectedDate.end).utcOffset(), 'm').utc().format("X")
```

Source: https://stackoverflow.com/a/47048543/9252232

**Comment by nathanreyes** [comment]
Good to know you were able to figure out a solution.

For future lurkers, the `modelConfig.timeAdjust` setting might help.
http://vcalendar.io/datepicker.html#time-adjust
