### ISSUE TITLE
Customize header

### ISSUE THREAD

**Issue by phonginx** [nathanreyes/v-calendar#620]
Hello, I want to add some custom buttons like "next year", "previous year", "next month", "previous month". 
Is there any way to implement it?
(I have tried to hide the header and create some outside buttons)

**Comment by wonny-log** [comment]
Why did you close this issue? I want to add some custom buttons too!  @phonginx

**Comment by phonginx** [comment]
> @phonginx Why did you close this issue? Did you solve this issue? I want to add some custom buttons too.

Yeah, I did it by adding some css.

**Comment by wonny-log** [comment]
@phonginx Oh, can you share a part of your code? I wonder which options(or anything..) you use.
