### ISSUE TITLE
Add an option to show a today button

### ISSUE THREAD

**Issue by mika76** [nathanreyes/v-calendar#627]
I think the one thing missing from this is a button to go back to today. There are lots of use cases where you would like to change the currently selected date back to today...

**Comment by codewithmartin** [comment]
Same wish from me..

**Comment by mrjackphil** [comment]
Tried to find a solution and figure out what there is a footer slot that can be used for those purposes. See #682. 

So something like should do the trick:
```
<v-date-picker>
    <template scope="footer">
        <button @click="resetDate">Today</button>
    </template>
</v-date-picker>
```
