### ISSUE TITLE
Can't change colors of disabled dates

### ISSUE THREAD

**Issue by laurenswarson** [nathanreyes/v-calendar#63]
Hi

Colors of disabled dates are by default red (color: rgb(217, 140, 140)).

Is it possible to change these?

Greetings

**Comment by nathanreyes** [comment]
[Here](http://docs.vcalendar.io/datepicker.html#customize-attributes) is the section in the docs related to customizing the `disabled-attribute` prop.

Please update if you have any issues.

**Comment by laurenswarson** [comment]
Perfect!

**Comment by amadeann** [comment]
@nathanreyes 

I think the section title `Customize Attributes` does not convey very well what it is about. I couldn't find the information in the docs when I browsed through them. Only got there from the link you shared.

From what I understand the section is really about styling the `CalendarDay` component. Maybe it could be renamed to something like: "Customizing Calendar Day Styles"?
