### ISSUE TITLE
When using v-model and @input on v-datepicker and making changes to value in input method you fall in unbreakable loop

### ISSUE THREAD

**Issue by VladymyrKarpov** [nathanreyes/v-calendar#634]
<template>

<v-date-picker
                                :popover="{visibility: !compareTo? 'hidden' : 'hover-focus'}"
                                :disabled="!compareTo"
                                @input="dateRangePrevious = dateRangePrevious || {}"
v-model = "dateRangePrevious"/>
</template>
<script>
export default {
    data(){
        return {
            dateRangeCurrent: {
            },
            dateRangePrevious: {
            }
        };
    }
</script

Reproducing on 1.07 and 1.08 versions but not on @next version (1.0.0-beta23 something like that)

**Comment by nathanreyes** [comment]
Will this work?

```html
<v-date-picker
  :popover="{ visibility: !compareTo ? 'hidden' : 'hover-focus' }"
  :disabled="!compareTo"
  :value="dateRangePrevious"
  @input="updateDateRange"
  />
```
```js
methods: {
  updateDateRange(range) {
    this.dateRangePrevious = range;
  },
}
```
