### ISSUE TITLE
@change event not working

### ISSUE THREAD

**Issue by AwaishK** [nathanreyes/v-calendar#636]
I want to get selected date from fronted end and call a function to backend API but @change event does not trigger and does not call any function?
```
         <DatePicker
            mode="single"
            v-model="date"
            :max-date='new Date()'
            @change="getData"
         />
```

**Comment by giulianimartini** [comment]
Hi @AwaishK,

I was trying to use `@change` also, but seems it does not work.

Accordingly to the documentation, the `@input` is the right event.
But even on a variable assignment, it will call the `@input`. So if you do something like `this.date = someDate`, being `date` the `v-model` variable, it will call the `@input` event.

Hope it helps.

**Comment by nathanreyes** [comment]
Yes, if you need to do any side-effects when the date is updated, you can do the following

```html
<v-date-picker mode="single" :value="date" :max-date="new Date()" @input="updateDate" />
```
```js
...
data() {
  return {
    date: new Date(),
  }
},
methods: {
  updateDate(date) {
    this.date = date;
    // Do whatever else you need to do here
  }
}
```
