### ISSUE TITLE
max-page - Bug

### ISSUE THREAD

**Issue by matrixOnline** [nathanreyes/v-calendar#64]
Hi,

first - great job, I'm loving v-calendar.

I have a bug with the max-page setting:

:max-page="{month: 6, year: 2019}"

![image](https://user-images.githubusercontent.com/29035126/36096901-9e95c71c-0ff8-11e8-872d-d85998c3bd09.png)

The last month is not displayed. (in this example, 06.2019)

**Comment by nathanreyes** [comment]
For others who may be referencing, this is a bug for `v-date-picker`...`v-calendar` does not have this issue.
