### ISSUE TITLE
Need to change a color for weekend days

### ISSUE THREAD

**Issue by hardzeichyksiarhei** [nathanreyes/v-calendar#641]
Is it possible to change somewhere in the settings /parameters to change a color of weekend (Sa+Su)?

**Comment by rapolaskutka** [comment]
Use attributes and date patterns 
https://vcalendar.io/dates.html#date-patterns
https://vcalendar.io/attributes.html

**Comment by hardzeichyksiarhei** [comment]
Thanks, but we need to change a color of the weekdays letter - mark Saturday and Sunday as pink color. How to do this?

![Аннотация 2020-08-20 162617](https://user-images.githubusercontent.com/11542402/90775864-087beb00-e302-11ea-9d54-98b12c2b6135.jpg)

**Comment by krispekla** [comment]
Use css selector:
`.vc-grid-cell:nth-of-type(6) > .vc-weekday,
.vc-grid-cell:nth-of-type(7) > .vc-weekday {
  color: pink;
}`

**Comment by nathanreyes** [comment]
Excellent solution provided by @krispekla

**Comment by hardzeichyksiarhei** [comment]
Thanks

> Use css selector:
> `.vc-grid-cell:nth-of-type(6) > .vc-weekday, .vc-grid-cell:nth-of-type(7) > .vc-weekday { color: pink; }`

Thanks!
