### ISSUE TITLE
Can not change atribute dates dynamically 

### ISSUE THREAD

**Issue by rapolaskutka** [nathanreyes/v-calendar#642]
I am using firebase to get date ranges. But then I set  attributes calendar does not highlight dates.
Code for getting attribute array:
```
datesToReturn() {
      
      var databaseRef = firebase.database();
      var ref = databaseRef.ref("datos/");
      var dateArray = new Array();
      ref.once(
        "value",
        (snap) => gotData(snap),
        (snap) => gotERROR(snap)
      );

       function gotData(data) {
        var dates = data.val();
        var keys = Object.keys(dates);
        for (let i = 0; i < keys.length; i++) {
          var k = keys[i];
          var end = dates[k].end;
          const string = { start: new Date(k), end: new Date(end) };
          dateArray.push(string);
        }
      }

      function gotERROR(data) {
        console.log("ERRORAS");
        console.log(data);
      }
      const atributeArray = this.attributes.slice();
      atributeArray[0].dates = dateArray; 

      this.attributes = atributeArray;
```

HTML:
```
<v-calendar
                id="full"
                is-inline
                is-dark
                color="teal"
                :attributes="attributes"
              />
```
And data:
```
computed: {
  },
  data() {
    return {
      form: {
        number: 0,
        inputValue: "",
      },
      error: null,
      comp: 0,
      range: {
        start: null,
        end: null,
      },
      attributes: [
        {
          highlight: true,
          dates: new Date(),
        },
      ],
    };
```

**Comment by survolt214** [comment]
I think  `this.attributes = atributeArray;` is NOT reactive
maybe you can try to using Vue.set methods to change the attrs
like  `this.$set(this.attributes, 0, atributeArray)`
or refresh the DOM by  `this.attributes.__ob__.dep.notify()`

you can read about [Reactivity in Depth](https://vuejs.org/v2/guide/reactivity.html)

**Comment by Lacroute** [comment]
Hi,

Thanks for this great library.

I experienced some troubles with api calls and reactivity.
I found that v-calendar behave normally only when I tried to update / delete the last attributes item, otherwise it wasn' properly re-rendered. Even after a` $forceUpdate()` call.
If I used the arrow navigation I got the updated data.

[reproduction link](https://codesandbox.io/s/hopeful-rhodes-y0pjx?file=/src/App.vue)

Solution was to provide a **unique key identifier for attributes items**. I was grouping them under a same name for data processing purpose like `"period"` or `"selection"`.
So keep it unique and it will work!

**Comment by InnovaIT-Albert** [comment]
> Hi,
> 
> Thanks for this great library.
> 
> I experienced some troubles with api calls and reactivity.
> I found that v-calendar behave normally only when I tried to update / delete the last attributes item, otherwise it wasn' properly re-rendered. Even after a` $forceUpdate()` call.
> If I used the arrow navigation I got the updated data.
> 
> [reproduction link](https://codesandbox.io/s/hopeful-rhodes-y0pjx?file=/src/App.vue)
> 
> Solution was to provide a **unique key identifier for attributes items**. I was grouping them under a same name for data processing purpose like `"period"` or `"selection"`.
> So keep it unique and it will work!

This! Removing the "key" attribute solved the problem.

Thank you @Lacroute , you saved my day.
