### ISSUE TITLE
dayclick how it works ?

### ISSUE THREAD

**Issue by Renato-Garbim** [nathanreyes/v-calendar#643]
```
  new Vue({
            el: '#app',
            data() {
                return {
                    attributes: [
                        {
                            key: 'today',
                            highlight: true,
                            dates: new Date()
                        }
                    ]
                }
            },
            events: [
                {
                    dayclick:alert('click!')
                }

            ]
            
        });

```

What i want to do is pretty simple, everytime my user click on a day via front-end, i want to trigger a method with the DateTime of the day that was clicked.

**Comment by anisbouziane** [comment]
Maybe you should use _@input_ in html

<vc-date-picker
          mode="date"
          v-model='selectedDate'
          :attributes="attributes"
          @input="yourFunctionHere()"
          is-inline
      />

**Comment by mckrava** [comment]
Super documented stuff ( 

For me works this implementation:

```
<v-calendar
        :attributes="calendarAttrs"
        @dayclick="onDayClickHandler"
 />
```

**Comment by nathanreyes** [comment]
Please use the [`dayclick`](http://localhost:8080/api/v2.0/calendar.html#dayclick) event as mentioned by @mckrava

**Comment by Sovai** [comment]
Hi, on dayclick is there a way to know if the clicked day is start or end? I'm having this trouble for validating
