### ISSUE TITLE
Trigger popover programmatically in datepicker?

### ISSUE THREAD

**Issue by rmedcalf** [nathanreyes/v-calendar#65]
Is there a way to trigger the popover through a custom event rather than hover or input?

I see in the source you have an isManual property on POPOVER_VISIBILITIES but I can't tell how to manually trigger it

I'd like to add a calendar icon next to the input field. When that's clicked, then open the popover

For now I'll use hover, but most of my users are used to clicking an icon.

**Comment by nathanreyes** [comment]
You can set `popover-visibility` to `"visible"` or `"hidden"` for manual control.

**Comment by rmedcalf** [comment]
thanks, but do you have an example on how to make it visible on an event if i have popover-visibility set to hidden?

here is what i'm working with so far
><template slot-scope="props">
        <input type="text" v-model="props.inputValue" :placeholder="inputState.message" @change="event => { props.updateValue(event.target.value) }"/>
        <span>
            <button class="date-icon" @click="() => { $emit('hover') }">
                <i class="fa fa-calendar"></i>
            </button>
        </span>
        <span v-if="selectedValue"><button v-on:click.prevent="selectedValue = null">Clear</button></span>
    </template>   >

**Comment by nathanreyes** [comment]
Would you mind putting the example into a fiddle? I [started one](https://jsfiddle.net/nathanreyes/0uo1zbvt/) with `vue`, `v-calendar` and `font-awesome` already included. 

That is probably the best way I can probably help you find a solution.

**Comment by rmedcalf** [comment]
oh dear... as I was writing out the fiddle, I figured it out.. it was so easy

This is what I was trying to do
https://jsfiddle.net/bwjunf5q/

If there's a different solution please let me know.
Thanks for looking. And this is one of the best calendar/datepicker plugins I've seen :)

**Comment by StevenInc** [comment]
Your example of the changing the key/value of visibility to hidden doesn't work in your fiddle.
