### ISSUE TITLE
Don't show a row with empty cells

### ISSUE THREAD

**Issue by Catedratico** [nathanreyes/v-calendar#650]
The design is getting worse because of these empty lines.

![Empty Line](https://downloader.disk.yandex.ru/preview/29a7017e5c24d52445c23f92da26b804c51f41c57c4cd9cb0904464591d6e197/5f4efc7c/GzPSXASTFInAV2xfYD3panECXJfgGXnBGx7PRKPfDEHfKoePUvTO0SQhpyNxk8GXr-LX6ETZaJhvwpdlrfmZxA==?uid=24303160&filename=Снимок+экрана+2020-09-02+в+00.54.18.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&tknv=v2&owner_uid=24303160&size=2048x2048 "Empty Line")

**Comment by cdavanos** [comment]
```

    .in-next-month.week-2 {
      display: none;
    }
```

**Comment by nathanreyes** [comment]
I believe the `trim-weeks` prop is what you are after.
