### ISSUE TITLE
masks data format

### ISSUE THREAD

**Issue by nickerloke** [nathanreyes/v-calendar#651]
Hi, I am encountering this issue when I am entering the date format in 'MM/DD/YYYY' and they are not parsing into the format I want. I am using mask to achieve this. 
`:masks="{
     input: ['DD-MMM-YYYY'],
     data: ['DD-MM-YYYY', 'DD/MM/YYYY', 'MM-DD-YYYY', 'MM/DD/YYYY', 'DD-MMM-YYYY', 'DD/MMM/YYYY']
}"`
![image](https://user-images.githubusercontent.com/65850011/92374006-c17b5b80-f131-11ea-8aae-56cc82d257a1.png)
![image](https://user-images.githubusercontent.com/65850011/92374047-d0faa480-f131-11ea-95f1-34ca559ef118.png)

From this screenshot above, you can see that I enter the date format '12/25/1988' which is 'MM/DD/YYYY' but they somehow converted it to 12-Jan-1990 which makes no sense.

**Comment by nathanreyes** [comment]
12-Jan-1990 is the format you have specified for the input masks (`DD-MMM-YYYY`). 
I think what you want is `:masks="{ input: ['MM/DD/YYYY'] }"`.

Please feel free to re-open if this doesn't fix your issue.
