### ISSUE TITLE
How to add custom button in calendar content

### ISSUE THREAD

**Issue by taeyeon-Kim** [nathanreyes/v-calendar#657]
Hello, Is there a way to add a button like the screenshot ?
![image](https://user-images.githubusercontent.com/27491403/93288543-029cfb00-f817-11ea-836b-bf5124c4877c.png)
![image](https://user-images.githubusercontent.com/27491403/93289493-6de7cc80-f819-11ea-9f99-3fbfc173d813.png)

**Comment by nathanreyes** [comment]
The `footer` scoped slot is provided for this reason in `v2.0.0`. Please be sure to read the [guide](https://vcalendar.io/changelog/v2.0.html#_2-use-footer-scoped-slot) for an example on how to do just this.

Does this work for you?

**Comment by taeyeon-Kim** [comment]
@nathanreyes thanks 🙏
