### ISSUE TITLE
It is not working properly

### ISSUE THREAD

**Issue by TheAndroidGuy** [nathanreyes/v-calendar#66]
Very often it closes the popup without saving the clicked date. That should never happen.
Here is [jsfiddle](https://jsfiddle.net/rvkq66h4/) for the example in the documentation.

**Comment by nathanreyes** [comment]
By default, the popup displays with `popover-visibility` set to `"hover"`, which means it hides when a date is clicked or the mouse stops hovering the input. You can also experiment with `"focus"`, `"visible"` or `"hidden"`. You can set `popover-keep-visible-on-input` to `true` to keep the popover from hiding after a new selection is made.

I'm not sure if that addresses your problem. Any time a new date is clicked it always updates the date  for my test cases. I may not be understanding your root issue here...

**Comment by milostimotic** [comment]
Same issue when `popover-visibility` set to `"focus"`. On this JSFiddle this issue is happening rarely. Maybe in 1/10 times when I click on the date. In my application it is happening 9/10 times. It is working always when `popover-visibility` set to `"visible"`. Event that I am using is `@dayclick`.

**Comment by TheAndroidGuy** [comment]
@nathanreyes try the jsfiddle couple times.

Here is [gif ](https://media.giphy.com/media/3ohs4hu4PLhlNjfJcc/giphy.gif)of the issue. (on the first try it does not select the date)

Like @milostimotic said, in the jsfiddle it is not working properly 1/10 times, but in my application its not working 9/10 also.

**Comment by shrpne** [comment]
I have the same issue with `popover-visibility` set to `focus`, but it occurs rarely, mostly when I click near months. 
I guess there is problem with losing focus after click

**Comment by nathanreyes** [comment]
Ok. Will definitely look into it. Are you seeing any errors in the console when this happens?

**Comment by TheAndroidGuy** [comment]
I don't get any errors in the console.
I also happens in other browser (chrome, edge, opera, firefox).

**Comment by nathanreyes** [comment]
Ok. I see where it is now.

**Comment by nathanreyes** [comment]
Please advise if the latest patch correctly addresses the issue for you.

**Comment by TheAndroidGuy** [comment]
Looks like its fixed.
