### ISSUE TITLE
[question] How to disable animation for Popover appearance and fade-out

### ISSUE THREAD

**Issue by frolovdev** [nathanreyes/v-calendar#661]
Hi, sorry for bothering you, first of all, thanks for the great work and awesome package.

I'm not a pro in vue framework, but I walk through source codes and related issues and I can't find any related info to my problem.

Problem: I try to figure out, how to disable popover animation fade-in and fade-out in the DatePicker component.

Additional info:
I guess source code related to my problem stores here
https://github.com/nathanreyes/v-calendar/blob/2b6bdc6cfe7d2317eef075b60be177b615ee56de/src/components/Popover.vue

At glance view, I don't know how to disable the standard behavior of a popover, could you provide some examples, after that I can help with doc if we can figure out how to deal with it.

Thanks for your time and consideration.

**Comment by vylmen** [comment]
Add `:popover="{ visibility: 'focus' }"` (or 'click') to `v-date-picker` attributes. In v2 this gets more options.
