### ISSUE TITLE
Month or Year Change Monitoring

### ISSUE THREAD

**Issue by jinsontech** [nathanreyes/v-calendar#664]
How to Monitor Month or Year Change 

is it that any event for that??

**Comment by trenzasoft** [comment]
I also need to know how I can get the month change happen.  Can;t find any event for that.

**Comment by nathanreyes** [comment]
Please add `update:from-page` to listen for page changes. If using multi-paned calendars, you can also use `update:to-page`.

```html
<v-calendar @update:from-page="moved" />
```
```js
...
methods: {
  moved(page) {
    console.log(`moved to month: ${page.month}, year: ${page.year}`)
  }
}
```
