### ISSUE TITLE
Semantic Version bump

### ISSUE THREAD

**Issue by d-koppenhagen** [nathanreyes/v-calendar#671]
Version 1.1.1 has been released recently and introduces lots of breaking changes:
https://github.com/nathanreyes/v-calendar/releases

As this breaking changes will cause code breaks for all dependent projects that are defined with a caret in the `package.json` file, it would be better to bump the major version part and unrelease `1.1.1` In favor of `2.0.0`:

```json
{
  // ...
  "dependencies": {
    "v-calendar": "^1.0.0" // will introduce unwanted breaking changes on npm install
  }
}
```

Suggestion:

1. bump version to 2.0.0
2. Release version 2.0.0
3. `npm unpublish 1.1.1`

With this changes most developers will be aware of the breaking change and they can migrate their code safely when updating by intention to `2.0.0`.

**Comment by nathanreyes** [comment]
Agreed. `1.1.1` has been deprecated and has gone to `2.0.0-beta.0` under the `next` tag.
#672

**Comment by d-koppenhagen** [comment]
Awesome, thanks 🙏
