### ISSUE TITLE
2.0?

### ISSUE THREAD

**Issue by jackmcdade** [nathanreyes/v-calendar#672]
Love all the new updates! I’m just curious why you introduced huge breaking changes on a patch release though? I need to peg our version on Statamic to keep it from breaking until we have a chance to work through the changes. 🤔

**Comment by maximilianschmid** [comment]
Good to see major progress on the project. But breaking changes should be communicated via the 2.x version bump to ensure everyone can adapt to the changes. thanks!

**Comment by nathanreyes** [comment]
@jackmcdade There seems to be some other issues so I've tagged `latest` back to `1.0.8`.
