### ISSUE TITLE
Unable to view selected time

### ISSUE THREAD

**Issue by nolikob** [nathanreyes/v-calendar#673]
When I tried working with __dateTime__ I have encountered an issue when using ```template v-slot="{inputValue, inputEvents}".
The inputValue returns to the input only date without time but the date is stored in the data correctly.

Using
```
"v-calendar": "^1.1.1",
"vue": "^2.6.11",
```

![obrazek](https://user-images.githubusercontent.com/16704046/96368659-5ae85500-1155-11eb-9cd3-f8d1c505c091.png)

```
<v-date-picker
    v-model="date"
    mode="dateTime"
    :model-config="modelConfig"
    :is24hr="true"
>
    <template v-slot="{ inputValue, inputEvents }">
        <input
            class="input"
            type="text"
            :value="inputValue"
            v-on="inputEvents"
        />
    </template>
</v-date-picker>
```

I had also notices in the TimePicker code that there is an option for 24hr time format but I do not know and was not able to find a way to use it and omit displaying the AM/PM since there is no use for it when having 24hr time format.

**Comment by nathanreyes** [comment]
Sure good catch. There is a new `is24hr` prop available to use in `2.0.0`. Also, the input should display the time when `mode` is `datetime` or `time`. It will display differently depending if `is24hr` is set or not.
