### ISSUE TITLE
Certain dates can't be highlighted in v.1.1.1

### ISSUE THREAD

**Issue by jaden** [nathanreyes/v-calendar#676]
I've discovered an issue that only seems to happen in October. Whatever date is located on the bottom left corner of the calendar can't be highlighted from Oct 30th, 1955 to Oct 29, 2006 with v1.1.1. Version 1.0.8 highlights the date as expected.

[This app](https://nj6wf.csb.app/) illustrates the issue. Switching between v1.0.8 and v1.1.1 will show the date as highlighted or not highlighted, respectively.

Here's the source code I used to demo the issue:

```
<html>
  <head>
    <meta charset='utf-8'>
    <meta name='viewport' content='width=device-width, initial-scale=1, shrink-to-fit=no'>
    <meta http-equiv='x-ua-compatible' content='ie=edge'>
  </head>
  <body>
    <div id='app'>
      <v-calendar :attributes="attrs" :from-page="fromPage"></v-calendar>
      <input type="number" v-model="year">
      <input type="number" v-model="month">
    </div>

    <script src='https://unpkg.com/vue/dist/vue.js'></script>
    <!-- <script src='https://unpkg.com/v-calendar@1.0.8/lib/v-calendar.umd.min.js'></script> -->
    <script src='https://unpkg.com/v-calendar@1.1.1/lib/v-calendar.umd.min.js'></script>

    <script>
      new Vue({
        el: '#app',
        data: {
          year: 1988,
          month: 10,
        },
        computed: {
          attrs: function () {
            return [{
              dates: this.dates,
              highlight: true
            }]
          },
          fromPage: function () {
            return {
              year: this.year,
              month: this.month
            }
          },
          dates: function () {
            let dates = []

            for (let i = 1; i < 32; i++) {
              dates.push(new Date(this.year, this.month - 1, i))
            }

            return dates;
          }
        }
      })
    </script>
  </body>
</html>
```

**Comment by nathanreyes** [comment]
I believe this is an issue with Daylight Savings and how the day boundary times are calculated. Since `1.1.1` has been deprecated and moved to `2.0.0-beta.0`, this issue will be fixed in the next beta.

**Comment by Christopher-Hayes** [comment]
@nathanreyes what is the state of date-picker? I'm a little confused with the versioning and docs pointing v2.0, but v2.0 all seem to be dead links. It looks like the latest release is v1.1.1, but that's deprecated?

**Comment by Christopher-Hayes** [comment]
@nathanreyes thanks for the reply. Your work on this project is appreciated. Breaking changes aren't an issue for me, so based on that information I'll plan to use v2.0 in a future production release. This is useful information, this might be something that could be added to the README for other new users that aren't aware of the status of the project.

**Comment by nathanreyes** [comment]
Sure thing. `v2.0` is now live along with the fix for this issue. You can test it [here](https://vcalendar.io/github/) by selecting issue 676.
