### ISSUE TITLE
request for "footer scoped slot" support for date pickers 

### ISSUE THREAD

**Issue by tbl0605** [nathanreyes/v-calendar#682]
Hi,
first of all, thank you @nathanreyes for your great and truly impressive v-calendar plugin! :)
I had a little request (if it's possible, of course) : 
would it be possible to also add "footer scoped slot" support to date pickers like you did for calendars?

Actually my idea was simply to add some "Today" button inside date pickers like you did in some of your calendar demos.
Thank you! :)

**Comment by nathanreyes** [comment]
Just curious..are you thinking of using the slot in addition to a time picker…or just the calendar day picker. Currently the time picker uses the footer slot, but I could consider finding a way to provide a custom one as well.

**Comment by doutatsu** [comment]
Would be nice, so you could do something like this:
![image](https://user-images.githubusercontent.com/4270980/97498030-60b71500-1963-11eb-99c2-b79e37bef0ae.png)

**Comment by nathanreyes** [comment]
@doutatsu For date time selectors, should this appear below the time selector portion? Or replace it?

**Comment by doutatsu** [comment]
@nathanreyes Good question. I imagine it would be useful to have the slot replace time selector, but it might also be useful to provide an additional slot, that goes underneath the time selector. So in this case, you'd have the custom slot at the bottom, with the time selector above it

**Comment by doutatsu** [comment]
I don't think many people would want to replace the existing time selector, so I bet just providing an extra footer slot would be the best way to go for now

**Comment by nathanreyes** [comment]
I think you are probably right. I'll give it a shot.

**Comment by tbl0605** [comment]
> 
> Just curious..are you thinking of using the slot in addition to a time picker…or just the calendar day picker. Currently the time picker uses the footer slot, but I could consider finding a way to provide a custom one as well.

Sorry @nathanreyes, I haven't seen your comment earlier, it was indeed mainly for the calendar day picker (like @doutatsu showed in his screenshot).
Thank you again for having considered my request, I'll give it a try soon :)
