### ISSUE TITLE
custom slot no longer working as of 1.1.0/v2, works on 1.0.8

### ISSUE THREAD

**Issue by vesper8** [nathanreyes/v-calendar#684]
This is what my custom calendar input looks like

```
        <v-date-picker
          v-model="form.dateOut"
          :popover="{ placement: 'bottom', visibility: 'click' }"
          :masks="{L: 'YYYY-MM-DD'}"
        >
          <div class="tw-flex tw-items-center">
            <input
              :value="form.dateOut ? dayjs(form.dateOut).format('YYYY-MM-DD') : ''"
              class="tw-placeholder-white tw-bg-transparent tw-px-6 tw-outline-none tw-py-3 tw-w-full md:tw-text-tiny md:tw-px-2 md:tw-outline-none md:tw-py-2 lg:tw-px-6 lg:tw-outline-none lg:tw-py-3"
              type="text"
              placeholder="Leaving"
            >
            <div class="tw-h-full tw-px-6 tw-flex tw-justify-center tw-items-center">
              <i class="far fa-calendar-alt" />
            </div>
          </div>
        </v-date-picker>
```

On 1.0.8 it works perfect, when you click the input it shows the calendar.

As of 1.1.0, and I also tried the newly released v2, when you click the input nothing happens

@nathanreyes Any chance you could tell me what changed and how to fix it? Many thanks

**Comment by nathanreyes** [comment]
Yes this is probably b/c as of v2, you need to add `@popperjs/core` as a dependency to your project. Let me know if that fixes your issue.

This is in the [changelog](https://vcalendar.io/changelog/v2.0.html), but I still should probably add it to other sections in the docs.

**Comment by nathanreyes** [comment]
Closing for now until further feedback on if this is not fixed by adding the dependency.

**Comment by vesper8** [comment]
@nathanreyes I just tried it again, this time I added `@popperjs/core` to my dependencies first.. and it still wasn't working

So I did more digging and found https://github.com/nathanreyes/v-calendar/issues/763

And that made it work. Essentially, it seems the `v-date-picker` only works with custom inputs if you add `v-slot="{ inputEvents }"` on the `v-date-picker` component and if you add `v-on="inputEvents"` on the custom input

So this does nothing when you click :

```
        <v-date-picker
          v-model="test"
        >
          <div>test</div>
        </v-date-picker>
```

But this works:

```
        <v-date-picker
          v-model="test"
          v-slot="{ inputEvents }"
        >
          <div v-on="inputEvents">test</div>
        </v-date-picker>
```

I think you should have a look at the PR suggested in https://github.com/nathanreyes/v-calendar/issues/763

Or at least improve the documentation

Also, at this point I am unsure if adding `@popperjs/core` was actually necessary
