### ISSUE TITLE
multiple date selection

### ISSUE THREAD

**Issue by MartinP7r** [nathanreyes/v-calendar#691]
I saw that you removed `multiple` date selection in 2.0 ( https://vcalendar.io/changelog/v2.0.html#_3-multiple-dates-deprecated ), however I would like to implement a selection where I can just select multiple dates in the same picker and get them as an array value. E.g. like the first examples on the top website ( https://vcalendar.io/ e.g. under "Highlights")  This doesn't seem possible anymore?

**Comment by MartinP7r** [comment]
nevermind. I implemented something similar with `v-calendar` by itself.

**Comment by nathanreyes** [comment]
Yes I was going to say you could use the `dayclick` events and add the dates manually to an array of attributes. Not sure if that was how you did it.

**Comment by MartinP7r** [comment]
Thank you. Yes, that's exactly how I did it.  
Sorry for the trouble.
