### ISSUE TITLE
"Delay" when opening/closing

### ISSUE THREAD

**Issue by micdobro** [nathanreyes/v-calendar#692]
Using: 
- `v-calendar 2.0.2`
- `Vue 2.6.11`

I would love to use your picker in my projects, although I am experiencing something weird. I am basing my testing off the example where the picker (`v-date-picker`) is triggered via a button (no input required in many of my use cases). After a click there is almost a one second delay before the picker shows up. 

At first I thought it had something to do with CSS transitions - but no change after disabling them. Then I thought - OK - the project I am throwing the picker in is quite huge and has all forms of pasta CSS in it. A test in a Vue HelloWorld with i18n installed results in the same behavior. Tested in both FF and Chrome. 

Can this delay be magically turned off? Did I miss something very simple?

**Comment by fmcdigital** [comment]
I want to disable this opening delay and changing months delay also..

**Comment by nathanreyes** [comment]
@micdobro Have you tried using the new `popover.transition` property?

```html
<v-date-picker v-model="date" :popover="popover" />
```
```js
data() {
  return {
    date: new Date(),
    popover: {
      transition: 'fade', // or 'none'
    },
  }
}
```
Other than the default transition, there is only a 10ms delay introduced for timing reasons, so I'm assuming the delay you refer to is the transition?

@fmcdigital There is also a [`transition`](http://localhost:8080/api/v2.0/calendar.html#transition) property that you can set to 'fade' or 'none' if you wish for the month animation.

**Comment by fmcdigital** [comment]
Still getting the delay using `popover transition:none`, maybe it's caused by those errors:

![Screen Shot 2020-11-03 at 18 35 29](https://user-images.githubusercontent.com/12851638/98043171-90eb3180-1e03-11eb-977c-39cd1e9ce1c1.png)

**Comment by micdobro** [comment]
My code: 
```
         <v-date-picker class="" v-model="date" :popover="popover">
            <template v-slot="{ togglePopover }">
                <div>
                    <button @click="togglePopover({ placement: 'auto-start' })">
                        Open
                    </button>
                </div>
            </template>
        </v-date-picker>
```

```
data() {
        return {
            date: new Date(),
            popover: {
                transition: "none", // or 'none'
            },
        };
    },
```
The delay is still on. The console is silent - I get no errors.

**Comment by micdobro** [comment]
@nathanreyes If you need anything else from me - don't hesitate to ask - I will try to help you as much as I can.

**Comment by coDavidHarnig** [comment]
Maybe try setting `delay` and `hideDelay` properties in the popover object. It looks like you will have to set them to a minimum value of 1 because there is a falsey test and 0 would trigger it as false and then use the fallback delay value which we don't want.

`<v-date-picker v-model="dateValue"
                    :popover="{ 
                      positionFixed: true, 
                      visibility: 'focus', 
                      keepVisibleOnInput: false,
                      delay: 1,
                      hideDelay: 1
                    }"`

**Comment by nathanreyes** [comment]
@coDavidHarnig You are correct. The falsey test should really be a test for a number.
