### ISSUE TITLE
unselect previously selected date 

### ISSUE THREAD

**Issue by tbl0605** [nathanreyes/v-calendar#694]
Hi,
I've seen a "feature" that was removed in latest v-calendar version (v2.0.2) that I found very useful in the v1 releases.
In older versions, when I used a single-date picker as "Button Dropdown":
- first time I clicked on a date in the date picker, it did set it in the input element (and of course in the date picker)
- second time I clicked on same date in the date picker, it cleared the input element (and also cleared the date picker)

Now with version v2.0.2, I'm no more able to "unselect" a date through the date picker, my users found it very useful (because some of ours forms have optional date fields).
Of course, I can now add a footer to the date picker with a "reset" button, but I would like to keep the date picker as "compact" as possible on the screen.

Could you bring this feature back (maybe through an option)?
Or could you give me an advice to achieve this without adding footers?

Thank you!

**Comment by nathanreyes** [comment]
Yes, if `is-required` isn't set then the default behavior was to clear the value. Until the bug is fixed, you might consider using a dedicated Clear button like in this [form example](https://vcalendar.io/datepicker.html#form-example).

**Comment by tbl0605** [comment]
@nathanreyes, thank you for the bug fix ! :)

**Comment by huynamboz** [comment]
@nathanreyes thanks
