### ISSUE TITLE
v-calendar v1.1.1 - no longer showing input or dates on my web page

### ISSUE THREAD

**Issue by MarcusIsh** [nathanreyes/v-calendar#698]
a few weeks ago, I was using v-calendar on my web page and I did not have  a set version when 1.1.1 was released, so my cdn picked up the new changes and I decided to upgrade how I was using my date time pickers for my form to the new way with the template, and it worked up until this week.

example:
`<v-date-picker v-model="date" mode="dateTime" />
                            <div class="input-group date">
                                <v-date-picker v-model="payrollData.formData.detailsTemplate.initialSendTimesheetDate"
                                               :min-date="new Date()"
                                               id="initialSendTimesheetDate"
                                               mode="dateTime"
                                               :masks="masks">
                                    <template v-slot="{ inputValue, inputEvents }">
                                        <input class="form-control"
                                               :value="inputValue"
                                               v-on="inputEvents" />
                                    </template>
                                </v-date-picker>`

the above code was working, I went to write a test for it today, and now my input is not showing up, no error, no input, no date picker at all for any on that page. 

![image](https://user-images.githubusercontent.com/5758946/98164871-f2b6a480-1eb2-11eb-86c0-bb7820067027.png)

no changes have been made to my code since I got it working when upgrading to v1.1.1 and i have used that page up until friday 10/30/2020 and everything was in working order then.

I noticed that v1.1.1 is no long listed on the site, but is listed on openbase https://openbase.io/js/v-calendar/versions#1.1.1

was v1.1.1 removed, if so how do I fix it? the way that it is done in the guide is how i have it now, and I have tried to move to the newer version of v-calendar in hopes it would fix it.

I hope this makes sense and  I hope you can help me figure this out.

**Comment by speyou** [comment]
Same problem, I decided to no longer trust this lib and fix the version as 1.0.8 for now. 
I'll be back in a few weeks to see if things are better respecting SEMVER and breaking changes. :)

Good lib but please don't introduce breaking changes in an undocumenter minor version bump!

**Comment by nathanreyes** [comment]
Yes. 1.1.1 was deprecated b/c of the reasons you mentioned and all breaking changes were re-introduced into 2.0. Reference the [changelog](https://vcalendar.io/changelog/v2.0.html) for detailed steps on updating your package. It should answer all the questions you have

**Comment by nathanreyes** [comment]
@MarcusIsh Sorry for your troubles. While some versions had been deprecated, it looks as if 1.1.1 was missed. NPM [correctly displays it as deprecated now](https://www.npmjs.com/package/v-calendar), so hopefully that will fix your issues.

1.0.8 should be treated as the latest 1.x version. 2.x picks up on future versions with the breaking changes.
