### ISSUE TITLE
Is there a way to apply a specific style to weekends?

### ISSUE THREAD

**Issue by surfer190** [nathanreyes/v-calendar#7]
[NotaBug]
I want to fade out and make weekends less prominent, how can you apply a style just to weekends?

**Comment by nathanreyes** [comment]
This kind of feature is currently in the works. I'll see about fitting it into the next release.

**Comment by nathanreyes** [comment]
Please refer to the [README](https://github.com/nathanreyes/v-calendar/blob/master/README.md) on using date patterns with attributes. I know it took a while but I wanted to make sure the feature was complete.
