### ISSUE TITLE
event for previous and next header button

### ISSUE THREAD

**Issue by edsel77** [nathanreyes/v-calendar#700]
Is there a way to get the event when clicking previous and next button using v-calendar datepicker?

Stackoverflow reference: https://stackoverflow.com/questions/64696514/v-calendar-event-for-previous-and-next-header-button

![image](https://user-images.githubusercontent.com/50189767/98239583-22dd7080-1fa3-11eb-85c3-7e2a90d170d7.png)

**Comment by nathanreyes** [comment]
Pasted from StackOverflow:
I would use the `update:from-page` event. The page parameter is passed that allows you to get meaningful data about what month was navigated to.

https://vcalendar.io/api/v2.0/calendar.html#update-from-page
