### ISSUE TITLE
highlight style rectangles with v2?

### ISSUE THREAD

**Issue by AndreKelling** [nathanreyes/v-calendar#709]
hi,

since Version 2 the highlights are in rectangles and not circles anymore?

https://codesandbox.io/s/v-calendar-forked-czpsx

**Comment by nathanreyes** [comment]
There is a bug when providing your own style and not providing a valid `fillMode`. 

Until it is patched, you will need to set a valid `fillMode: String` for the highlight as well when providing your own style. This can be `none`, `light`, `solid`.

**Comment by nathanreyes** [comment]
Fixed in `2.0.2`
