### ISSUE TITLE
Click function inside popover

### ISSUE THREAD

**Issue by nivv** [nathanreyes/v-calendar#710]
I have a use case where I need to click a link inside the popover. But the popover is not clickable. Is there a way around this?

What I got so far:
```vue
<v-calendar
    :attributes="calendarAttributes"
    :columns="$screens({ default: 1, lg: 2 })"
    color="green"
    is-expanded
    is-inline
    mode="range"
    ref="calendar"
>
    <div slot="day-popover" slot-scope="{ day, dayTitle, attributes }">
        <div class="text-xs text-gray-300 font-semibold text-center">
            <!-- {{ dayTitle }} -->
            <span :attribute="attr" :key="attr.key" v-for="attr in attributes">
                {{ attr.customData.description }}
                <button @click="goToEvent(customData)">Go to project</button>
            </span>
        </div>
    </div>
</v-calendar>
```

**Comment by nathanreyes** [comment]
In your `calendarAttributes.popover` object, is the [`isInteractive`](http://vcalendar.io/api/v2.0/attribute.html#popover-isinteractive) property set to `true`? It *should* default to true when using a custom slot like this, but I'm wondering if it is explicitly set to `false` for some reason?

**Comment by nivv** [comment]
@nathanreyes thanks for your help!`isInteractive` was not set at all.  Setting `isInteractive` to `true` fixed it.
