### ISSUE TITLE
Add interval time

### ISSUE THREAD

**Issue by 4KDA** [nathanreyes/v-calendar#714]
Please add the functionality of the available time interval. So that when choosing a time, you can adjust the selection, for example, values ​​with a difference of 15 minutes (00:00, 00:15, 00:30, 00:45, 01:00 ...)

**Comment by nathanreyes** [comment]
There is a [`minute-increment`](https://vcalendar.io/datepicker.html#minute-increments) prop you can use.

**Comment by 4KDA** [comment]
> There is a [`minute-increment`](https://vcalendar.io/datepicker.html#minute-increments) prop you can use.

Thanks! I didn't notice this possibility right away

**Comment by nathanreyes** [comment]
That's ok. I just added it a few weeks ago.
