### ISSUE TITLE
@next: [Vue warn]: Component is missing template or render function. 

### ISSUE THREAD

**Issue by Civer** [nathanreyes/v-calendar#720]
#633 

Hey together,

maybe i'm a bit to early for opening this, but as the v-calender@next release README includes a usage section already I gave it a try and get an error.

I've installed v-calendar@next using npm (also used yarn to crosscheck, no changes).

main.js:

```
import` { createApp } from 'vue'
import App from './App.vue'
import VCalendar from 'v-calendar';

...

const defaults = {
    componentPrefix: '',
    titlePosition: 'left',
};

createApp(App).use(VCalendar, defaults).use(store).use(router).mount('#app')
```

Then I'm using it the following way in another template:

```
<template>
  <div>
    <Calendar />
    <DatePicker v-model="date" />
  </div>
</template>

<script>
import { Calendar, DatePicker } from "v-calendar";

export default {
  components: { Calendar, DatePicker },
  data() {
    return {
      date: new Date(),
    };
  },
};
</script>
```

If I open the page it shows nothing. When I check the console I get the following warning:

```
Vue warn]: Component is missing template or render function. 
  at <Calendar>
```

The same is true for DatePicker Component.

I'm not sure right now if this is user error or an actual issue.
I've tried a lot of things today to fix it, but nothing seems to be working.

Thanks a lot for your service to the VueJS community and for your help!

With pleasure
Peter

**Comment by nathanreyes** [comment]
Yep, working through some issues right now with component registration. Hopeful to have an alpha 2 soon to remedy the issue.

**Comment by Civer** [comment]
Looking forward to it :)
Keep up the great work!
Feel free to close it whenever you're ready with Alpha 2.

**Comment by nathanreyes** [comment]
Thanks @Civer. Alpha 2 is out and should correct this...although there may be other issues at this time. Please direct any quirks or findings to the discord channel at this time since it is a little fluid at the moment.

https://discord.gg/QrsUn4seXM

**Comment by adamdehaven** [comment]
@nathanreyes I'm having the same issue in my open-source Vue 3 plugin. 

If a user installs in `main.ts` the component works with no issues; however, if they try importing in a single component (instead of using `Vue.use()` in `main.ts`) the component throws the same `missing template or render function` warning.

Would you mind sharing how you resolved this so that the plugin can be imported directly within a single component?
