### ISSUE TITLE
v2.0.0 v-date-picker has mode but v-calendar has no mode

### ISSUE THREAD

**Issue by aromage** [nathanreyes/v-calendar#725]
set time attribute with v-date-picker is successful but

i can't see time mode on v-calendar component 

is there a way?

**Comment by nathanreyes** [comment]
The `mode` prop is only for the date picker. It doesn't really have an application for just the calendar.

The idea with the `v-calendar` is to provide your own attributes via the `attributes` prop. You can also listen to the `dayclick` event if you need to allow the user to interact with it.

Can you elaborate on what you are trying to achieve with the calendar?

**Comment by aromage** [comment]
thank you for your answer. i contemplate more about what i want to do. ty
