### ISSUE TITLE
Quick migration guide for range date picker

### ISSUE THREAD

**Issue by MrOnlineCoder** [nathanreyes/v-calendar#726]
So I've been using v-calendar for most of my projects where a quick but functional date-picker must be used for viewing report or statistical data. Only a day ago I've discovered a breaking update in v-calendar, so old my code stopped working with new installations of v-calendar. However, the default single input with popover for selecting two dates in range was really useful in previous version, and now I can't reproduce it in new version.

So far I've come with this code:
```html
<v-date-picker v-model="range" is-range>
            <template v-slot="{ inputValue, inputEvents }">
              <div class="flex justify-center items-center">
                <input
                  :value="`${inputValue.start} - ${inputValue.end}`"
                  v-on="inputEvents.end"
                />
              </div>
            </template>
          </v-date-picker>
```

And the date selection works, but surely,you can't edit in the input field by modifying the formatted dates. How can I fix it? What should I do with inputEvents? Should I override them and do parsing manually or there is another way? Anyway, it could be very useful if there was a code snippet for quick migration of such cases, where you just need the widget right now and right there, with minimal time spent on reading docs and experimenting in code.

Thanks for any help in advance.

**Comment by nathanreyes** [comment]
This example might help. http://localhost:8080/examples/datepickers.html#date-range
Also, there is a `Date picker conversion guide` section in the changelog guide for binding the value and events to inputs. http://localhost:8080/changelog/v2.0.html
