### ISSUE TITLE
Template or render function not defined - Quasar/TypeScript

### ISSUE THREAD

**Issue by ewarth** [nathanreyes/v-calendar#73]
Hello,

I wanted to add v-calendar to my app built with the Quasar framework using TypeScript and Vue 2.5.12. I can't get the component to ever load and have tried a few variations for importing it with no luck, the most common error I get is :
`[Vue warn]: Failed to mount component: template or render function not defined.` 

Anyone have experience using v-calendar with typescript/quasar?

**Comment by nathanreyes** [comment]
Sorry I haven't had the chance to check out Quasar yet. Is it pretty easy to use other components in? Is there some kind of setup required to using Vue plugins?

**Comment by ewarth** [comment]
Typically its pretty straightforward and you just import components in the normal vue fashion. Our issue I think was using typescript; with a separate .ts and .vue file for each component. What I ended up doing was creating base .vue component in our project without typescript, that only loaded the calendar and it's attributes. This worked out fine and the calendar works perfectly, so it must be a typescript specific issue.

**Comment by nathanreyes** [comment]
Ok. I'll close for now until I can add typescript support at a later time. Thanks for the follow up.

**Comment by risafj** [comment]
@nathanreyes Hi, just making sure, is there still no Typescript support so far? Your module looked awesome but our project uses Typescript so I'm wondering if I can't use it...

**Comment by KaanYilmazz** [comment]
https://gist.github.com/Nicklas2751/da1fbe81878df7bb531fa4978c0ce7a8
