### ISSUE TITLE
First day of week does not work properly

### ISSUE THREAD

**Issue by octaviangrozman** [nathanreyes/v-calendar#74]
Setting firstDayOfWeek as Monday (firstDayOfWeek = 2) breaks other dates
![image](https://user-images.githubusercontent.com/33148154/36645386-2bd46042-1a68-11e8-8e29-6de11b6c6f98.png)

**Comment by nathanreyes** [comment]
Are you using the latest version (v0.6.3)? This was discussed in a [prior issue](https://github.com/nathanreyes/v-calendar/issues/44) that I thought was fixed. I may need to revisit though.

**Comment by nathanreyes** [comment]
Closing until further verification is received that this issue still exists for the latest release (`v0.7.5`).
