### ISSUE TITLE
popover.js not imported

### ISSUE THREAD

**Issue by basarozcan** [nathanreyes/v-calendar#742]
When I try to use v-calendar with global import:

my main.js
```
import './index.css'

import { createApp } from "vue/dist/vue.esm-browser";
import { SetupCalendar, Calendar, DatePicker } from 'v-calendar';

const app = createApp({})
// app.use(VCalendar)
// do some necessary preparations
app.use(SetupCalendar, {})
    // Use the components
    .component('Calendar', Calendar)
    .component('DatePicker', DatePicker)
app.mount('#app')
```

error on console
![image](https://user-images.githubusercontent.com/2423158/102694082-cde27a80-422f-11eb-91e4-6f4c92a2f598.png)

Did anyone struggle with that problem?

**Comment by nathanreyes** [comment]
Are you using one of the alphas for Vue 3 support? `npm i -S v-calendar@next`?

Popper also needs to be installed since it is a core dependency.

`npm i -S @popperjs/core`

**Comment by basarozcan** [comment]
Yes, my problem solved after adding popperjs/core to dependencies.. Thank you @nathanreyes

**Comment by d2718nis** [comment]
How about adding it as a dependency for it to be installed automatically by npm / yarn?
