### ISSUE TITLE
Support input mask for dateTime mode

### ISSUE THREAD

**Issue by frankspin89** [nathanreyes/v-calendar#746]
Currently dateTime mode doesn't seems to respect input mask configuration.  When using date mode mask configuration is working as expected. 

Date input mask Working - Mode date, custom mask, and is24hr false
![image](https://user-images.githubusercontent.com/4480104/102896661-091abe80-4467-11eb-863b-3e8b13d65b67.png)

Date input mask Working - Mode date, custom mask, and is24hr true
![image](https://user-images.githubusercontent.com/4480104/102896800-3f583e00-4467-11eb-80a4-bcadb3f0a441.png)

Date input mask Not Working - Mode dateTime, custom mask, and is24hr true
![image](https://user-images.githubusercontent.com/4480104/102896870-60b92a00-4467-11eb-99ce-a9b82625ef54.png)

Date input mask Not Working - Mode dateTime, custom mask, and is24hr false
![image](https://user-images.githubusercontent.com/4480104/102896967-965e1300-4467-11eb-99b1-dff75d8f9d3c.png)

**Comment by SzaboL** [comment]
Hi, I had the same problem.

You can set input mask if is24hr is true with inputDateTime24hr
masks: {
            inputDateTime24hr: "YYYY-MM-DD HH:mm:ss",
}
If is24hr is false, use inputDateTime

This works for me.

**Comment by nathanreyes** [comment]
The docs were a little behind so I added a dedicated page for this. 
https://vcalendar.io/format-parse-dates.html

In short, you can provide `inputDateTime` (is24Hr false) and `inputDateTime24hr` (is24Hr true) masks to target these modes.
