### ISSUE TITLE
Timezones do not work correctly with ISO-8601 dates passed as a string value

### ISSUE THREAD

**Issue by MrOnlineCoder** [nathanreyes/v-calendar#747]
Hi. I am receiving an entity from server, which uses MongoDB as a database, which stores dates as UTC ISO-8601 dates. I am using vc-datepicker to allow user to change that date, but it does not work correctly with timezone specified.

Code:
```html
<vc-datepicker v-model="date_from_server" mode="dateTime" timezone="Europe/Kiev"/>
```

Suppose `date_from_server` = `2020-12-22T07:20:00.000Z`. While Europe/Kiev timezone is GMT+2, the correct time displayed should be '09:20', however, vc-date-picker displays it as '07:20', though the timezone is specified.

Current workaround: use some library like `moment()` to convert ISO date to javascript Date object and pass it as a value to v-calendar.

Thanks in advance.

**Comment by nathanreyes** [comment]
Currently it seems to be the milliseconds portion that is the hiccup. 

Tip: Until it is patched, if you remove the milliseconds then it should work properly.
