### ISSUE TITLE
how to reset the style when the html base font size is 10px or other value

### ISSUE THREAD

**Issue by qunying-kooboo** [nathanreyes/v-calendar#75]
![image](https://user-images.githubusercontent.com/4383012/36651820-c0563b82-1ae5-11e8-80df-8a819dc3a423.png)

**Comment by qunying-kooboo** [comment]
for range 
drag:
![image](https://user-images.githubusercontent.com/4383012/36652254-9cd6fb76-1ae8-11e8-9718-312f0e5301c2.png)
select
![image](https://user-images.githubusercontent.com/4383012/36652271-b0420174-1ae8-11e8-8747-47aeabf1a980.png)

**Comment by Teknologica** [comment]
I had the same issue and fixed most of it by overriding all the styles manually to define a new `fontSize`.

**Comment by nathanreyes** [comment]
It looks like the height for `drag-attribute` is overwritten by a hard coded value of 25px. Will modify to 
1. Use a more sensible height based on font size
2. Respect user provided height for `drag-attribute`
