### ISSUE TITLE
VuePress documentation is broken

### ISSUE THREAD

**Issue by mdunbavan** [nathanreyes/v-calendar#750]
Hi,

I am trying to access the docs but they are broken.

This is a heads up @nathanreyes your last commit was 11 days ago I think?

Cheers,
Mark

**Comment by nathanreyes** [comment]
Referring to https://vcalendar.io? Seems to be loading just fine for me?

**Comment by mdunbavan** [comment]
@nathanreyes I swear it was broken a few days ago. I couldn't open some pages or get to certain parts of the api docs...ahhhh I'm so glad it is back now. Sorry for the alarm about that.

**Comment by nathanreyes** [comment]
Ah interesting. I'll keep an eye out for it.
