### ISSUE TITLE
Safari AddEventListener is not a function error

### ISSUE THREAD

**Issue by alig1882** [nathanreyes/v-calendar#751]
Hi @nathanreyes! First I want to say thank you so much for creating such a beautiful calendar. I am currently using it for a personal project and I am very much indebted to you. So once again, thank you <3. 

Everything works great with the calendar and loads fine in all browsers, except Safari (version 13.1.3). There when the VCalendar component is imported or is used, for example,
```
import VCalendar from 'v-calendar';

Vue.use(VCalendar);
```

then the following error results,

```
TypeError: query.addEventListener is not a function. (In 'query.addEventListener('change', _this.refreshMatches)', 'query.addEventListener' is undefined)
```

This is what it looks like in the browser,

<img width="723" alt="Screen Shot 2020-12-29 at 10 30 00 AM" src="https://user-images.githubusercontent.com/30926326/103294916-d02b9e00-49c0-11eb-9162-117dbe45dbe9.png">,

and the below is a not very helpful call stack,
<img width="704" alt="Screen Shot 2020-12-29 at 10 30 52 AM" src="https://user-images.githubusercontent.com/30926326/103294965-ef2a3000-49c0-11eb-86e7-a365063441e3.png">.

I am also getting the same error in all mobile browsers (Safari, Chrome, Firefox) on an iPhone (I assume it's because on iPhone, the browsers are all using Webkit).

I have been trying to debug this for a few days but I can't think of a course of action. Are you aware of this issue or have you run into it before? If so, how did you resolve it? Thank you so much Nathan! I truly appreciate it.

**Comment by nathanreyes** [comment]
I think this was recently patched in [2.1.4](https://github.com/nathanreyes/v-calendar/releases/tag/v2.1.4).

**Comment by alig1882** [comment]
You're the best it worked! Thank you so much! I upgraded to 2.1.5 just to get any other fixes.

I hate to be a bother but if I may get your help with two more issues related to this. I just tested it and though now things load fine, in Safari, 
1. attributes are not showing up on the calendar and,
2. date selection is not working with the date picker. 
 
I also verified that these features work as expected in Chrome and Firefox. 

Sorry to bother you again and I really appreciate how responsive you are @nathanreyes!

**Comment by nathanreyes** [comment]
Just curious...what version are you upgrading from?

**Comment by alig1882** [comment]
I was in version 2.1.3. I started playing around with the calendar about a week or two ago.

**Comment by alig1882** [comment]
I also tried a clean install just to be sure (npm uninstall v-calendar then npm install with version 2.1.5 in package.json) and can confirm the stuff I mentioned isn't working correctly in Safari.
