### ISSUE TITLE
Bring back deprecated multiple dates selection

### ISSUE THREAD

**Issue by DamianGlowala** [nathanreyes/v-calendar#753]
I have a use case that really needs this feature to be back, when the user is selecting dates in 2 steps:
1. They pick an initial range of dates
2. They proceed to step 2 with a separate calendar. This time they can deselect any single dates to shape the final date selection (conversion between a range in step 1 and an array of all particular dates in step 2 happens in the background).

So I did try a deprecated, and yet supported feature but there is an issue:
`[Vue warn]: Missing required prop: "value"`.
Is there a way to overcome this minor error or see the overall feature back and fully supported in the near future? The date buttons are much less readable and more confusing given the scenario above.

**Comment by DamianGlowala** [comment]
Issue has been resolved.

**Comment by LucaRed** [comment]
How was it resolved?
