### ISSUE TITLE
cannot find the style sheet

### ISSUE THREAD

**Issue by johnantoni** [nathanreyes/v-calendar#758]
Hi, any idea where to load the style sheet from?

I saw a similar issue pointing to 

`import 'v-calendar/lib/v-calendar.min.css';`

But nothings there, any ideas?

**Comment by hmaesta** [comment]
Style is included in js.

Please read: https://github.com/nathanreyes/v-calendar/issues/756

**Comment by johnantoni** [comment]
thanks
