### ISSUE TITLE
Help customizing the input element of v-date-picker

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#76]
![improve-2](https://user-images.githubusercontent.com/11582056/36708870-f23ad108-1b53-11e8-997b-7d06b75e09c7.jpg)
How could I build an input element like this? 

I saw the example in the docs, but I still didn't understand how to display the selected date in this format, and getting the day span.

**Comment by rudeks** [comment]
Revision 0.6.3 (Commit 82b4c7322f34aee0cacea9420b63f956d01a5595) allowed it to style the input using slots.

**Comment by nathanreyes** [comment]
This would require the combination of using a custom slot with a custom input format.

I'm working on a [CodeSandbox](https://codesandbox.io/s/8mwqw5ok2) to help people experiment. There is a section for *Input Formats* and *Custom Input Slot* that might help with this.

For the day span, that would be a different element within your custom slot.

**Comment by luiztsmelo** [comment]
Great. I'll wait for it.

**Comment by nathanreyes** [comment]
This might get you started. Reference [#76](https://codesandbox.io/s/8mwqw5ok2).

**Comment by luiztsmelo** [comment]
Thanks @nathanreyes. Worked here.
