### ISSUE TITLE
Dates in attributes array not updating reactively

### ISSUE THREAD

**Issue by iiRobin** [nathanreyes/v-calendar#761]
People are able to select dates in a datepicker and I'm pushing the new dates into the **attributes** array to display them in a `v-calendar`. 
In v0.9.7 this worked perfectly fine, but I updated the package in my application to v2.2.0 and this doesn't seem to work anymore. 

Does anyone know a fix for this?

**Comment by nathanreyes** [comment]
Here is a simple example:
```html
<v-calendar :attributes="attributes" @dayclick="addDayAttribute" />
```
```js
export default {
  data() {
    return {
      attributes: [
        {
          dates: new Date(2021, 0, 14),
          highlight: true,
        },
      ],
    };
  },
  methods: {
    addDayAttribute(day) {
      this.attributes.push({
        dates: day.date,
        highlight: true,
      });
    },
  },
};
```

Here is another example that might get you going. https://vcalendar.io/examples/datepickers.html#multiple-dates

Hope that helps.

**Comment by iiRobin** [comment]
> Here is a simple example:
> 
> ```
> <v-calendar :attributes="attributes" @dayclick="addDayAttribute" />
> ```
> 
> ```js
> export default {
>   data() {
>     return {
>       attributes: [
>         {
>           dates: new Date(2021, 0, 14),
>           highlight: true,
>         },
>       ],
>     };
>   },
>   methods: {
>     addDayAttribute(day) {
>       this.attributes.push({
>         dates: day.date,
>         highlight: true,
>       });
>     },
>   },
> };
> ```
> 
> Here is another example that might get you going. https://vcalendar.io/examples/datepickers.html#multiple-dates
> 
> Hope that helps.

This is not exactly gonna work because I have a different setup. People can select dates in a `vue-hotel-datepicker` component in a range depending on how long their stay at the place is. The dates that are selected and the ones in between need to be displayed in a `v-calendar` for visual purposes. The `v-calendar` is not getting clicked on or anything, all I'm doing is pushing new data into the `attributes` array to display in the `v-calendar`

**Comment by renielDev** [comment]
I have

> Here is a simple example:
> 
> ```
> <v-calendar :attributes="attributes" @dayclick="addDayAttribute" />
> ```
> 
> ```js
> export default {
>   data() {
>     return {
>       attributes: [
>         {
>           dates: new Date(2021, 0, 14),
>           highlight: true,
>         },
>       ],
>     };
>   },
>   methods: {
>     addDayAttribute(day) {
>       this.attributes.push({
>         dates: day.date,
>         highlight: true,
>       });
>     },
>   },
> };
> ```
> 
> Here is another example that might get you going. https://vcalendar.io/examples/datepickers.html#multiple-dates
> 
> Hope that helps.

Im experiencing the same issue. I am using the code that you provided.

**Comment by dshastry** [comment]
+1 on this. I'm trying to dynamically add tasks to the calendar and doesn't seem to be reactive.

getTasks() {
      this.$api({
        url: "/task/tasks",
        method: "get",
        responseType: "json",
      }).then((response) => {
        this.taskList = response.data.tasks;
        this.taskList.forEach((task) => {
          this.attributes[0].dates.push(
            DateTime.fromSeconds(parseFloat(task.due_date)).toJSDate()
          );
        });
      });
    },

**Comment by chriship** [comment]
I'm also facing this issue with the next branch and vue 3. I think it's because the attributes need to be flagged as 'deep' when they are being watched in Calander.vue on line 361 like so:

```
attributes: {
    handler(val) {
        const { adds, deletes } = this.store.refresh(val);
        this.refreshAttrs(this.pages, adds, deletes);
    },
    deep: true,
},
```
