### ISSUE TITLE
How to disable the days that has already passed?

### ISSUE THREAD

**Issue by lmatab** [nathanreyes/v-calendar#77]
Hello All.

Have you figured out how to disabled the days that have already passed?

Thanks

**Comment by luiztsmelo** [comment]
```
<v-date-picker
  :min-date='new Date().getTime()'>
</v-date-picker>
```

**Comment by lmatab** [comment]
Hello luiztsmel, Thanks for the feedback.

I need to use it with the v-calendar component instead the v-date-picker.

it looks like :min-date='new Date().getTime()' only works for the v-date-picker

Thanks

**Comment by luiztsmelo** [comment]
I don't know it's the best way, but you can try thinking like this:

```
<v-calendar
  :attributes='attributes'>
</v-calendar>
```
```
attributes: [
        {
          key: 'disabledDates',
          contentStyle: {
            textDecoration: 'line-through',
            opacity: .3
          },
          dates: {
            start: null, // From the beginning of time
            end: new Date().setDate(new Date().getDate() - 1) // Until yesterday
          }
        }
      ],
```

**Comment by nathanreyes** [comment]
@lmatab The concept of a `min-date` doesn't really exist for `v-calendar`, so I would try @luiztsmelo suggestion by using your own custom attribute.

**Comment by lmatab** [comment]
Thanks a lot @luiztsmelo , thanks a lot @nathanreyes , that worked  nicely.

Thanks a lot for your time to answer this question.
