### ISSUE TITLE
Time cannot be null

### ISSUE THREAD

**Issue by jannescb** [nathanreyes/v-calendar#772]
If the initial value of a date-picker in time mode is `null`, or if I delete the value from the input slot it is not possible anymore to select a time. I can cheat by adding any number to the input but thats not user friendly at all…

Before deleting:
<img width="264" alt="Bildschirmfoto 2021-01-29 um 17 45 12" src="https://user-images.githubusercontent.com/17292622/106302903-d039ea80-6259-11eb-9eef-0b65dc700d3c.png">

After deleting selects are disabled:
<img width="262" alt="Bildschirmfoto 2021-01-29 um 17 44 01" src="https://user-images.githubusercontent.com/17292622/106302790-b0a2c200-6259-11eb-92f3-c6bb0dc0e2b5.png">

```js
<v-date-picker v-model="time" mode="time">
    <template v-slot="{ inputValue, inputEvents }">
        <input :value="inputValue" v-on="inputEvents" />
    </template>
</v-date-picker>
```

**Comment by jannescb** [comment]
much appreciated 👍

**Comment by Pinnokkio** [comment]
If the initial value is null, it's still impossible to select a time. What's `fillDate` exactly for? I couldn't find any docs on this.
