### ISSUE TITLE
Date View is having extra row

### ISSUE THREAD

**Issue by alfligno** [nathanreyes/v-calendar#774]
![image](https://user-images.githubusercontent.com/69491106/106408750-05248800-647a-11eb-9831-aa9e7be86384.png)

**Comment by nathanreyes** [comment]
By default, all calendars display the max weeks of the calendar. If you wish to only display the number of weeks in the calendar, you need to set the `trim-weeks` prop.

It's a tradeoff. If it was always hidden, then sometimes elements below the calendar would be shifting up and down as the user was navigating months, which I personally do not prefer. 

Per the [example](https://github.com/nathanreyes/v-calendar/blob/master/docs/.vuepress/components/homepage/custom-calendar.vue) you reference above, that prop isn't set, but if it was then that last week would not appear.
