### ISSUE TITLE
popover.placement doesn't work

### ISSUE THREAD

**Issue by anandsiddharth** [nathanreyes/v-calendar#777]
Hi,
Datepicker's popover placement doesn't work as expected.

https://stackblitz.com/edit/vuejs-starter-tmvbaq?file=app.js

```html
<vc-date-picker :popover="{ placement : 'left' }"> </vc-date-picker>

```

v-calendar version : 2.2.3

**Comment by nathanreyes** [comment]
Ya when you call `togglePopover` it doesn't pick up the `popover` settings prop. It currently only applies those setting if you are binding `inputEvents` to an input element. I'll fix it.

For now you can provide the options object manually.

```html
  <v-date-picker v-model="date">
    <template v-slot="{ togglePopover }">
      <button @click="togglePopover({ placement: 'left' })">Click to open calendar</button>
    </template>
  </v-date-picker>
```

**Comment by anandsiddharth** [comment]
Thanks! @nathanreyes!
It's working as expected. ✌️✌️✌️✌️✌️
