### ISSUE TITLE
Datepicker not initialized correctly

### ISSUE THREAD

**Issue by sourivore** [nathanreyes/v-calendar#78]
Hello,

Today is the 2018-02-28 but when I use the datepicker where min-date is set to 2018-03-01, it opens on the February month instead of the minDate (if minDate is > today)
This behavior is undesirable and requires us to scroll to the correct month each time we use the datepicker

Thanks a lot

**Comment by nathanreyes** [comment]
Until this feature is implemented you can assign the `from-page` prop the manually to the min date. For example:
```html
<v-date-picker
  :min-date='minDate'
  :from-page='fromPage'
  v-model='date'>
</v-date-picker>
```
```javascript
const minDate = new Date(2018, 2, 1);

export default {
  data() {
    date: null,
    minDate,
    fromPage: { month: minDate.getMonth() + 1, year: minDate.getFullYear() }
  }
}
```
You can reference Issue 78 [here](https://codesandbox.io/s/8mwqw5ok2). Source code is in the 'src/components/github' directory. Hopefully it works this is the first time I've tried sharing via CodeSandbox.
