### ISSUE TITLE
hightlight daterange endpoint and startpoint in v2

### ISSUE THREAD

**Issue by AndreKelling** [nathanreyes/v-calendar#782]
i do look for a way to style the highlight of end- and startpoints of a daterange differently.

in the following example, using v 2.2.3

https://codesandbox.io/s/v-calendar-forked-w9dw7

i would like to get the 12. and 17., lets say in a different color white.

i can't find a special CSS class for end- or startpoints.

----

### background

It was kind a default with the v1 of v-calender but now seems not possible anymore.

![Introduction___V-Calendar](https://user-images.githubusercontent.com/15000189/107391865-6b07b400-6af9-11eb-9954-e1c20154fd8e.jpg)

i did a switch to v2, because it works better with updates of attributes. while v1 made me troubles.

thanks so far. 
keep up the good work!

**Comment by nathanreyes** [comment]
There are `start`, `end`, `startEnd` and `base` sub-configurations that you can use for these sections. I updated your attribute to this..
```js
        {
          key: 'anotherday',
          highlight: {
            startEnd: {
              style: {
                backgroundColor: '#009080',
              },
              contentStyle: {
                color: 'white',
              }
            },
            base: {
              style: {
                backgroundColor: '#009080',
              }, 
            }
          },
          dates: [{start: new Date(2018, 0, 12), end: new Date(2018, 0, 17)}],
          popover: {
            label: 'hi'
          }
        }
```
