### ISSUE TITLE
how to hide v-date-picker in dateTime mode when clicking on button from footer ?

### ISSUE THREAD

**Issue by vesper8** [nathanreyes/v-calendar#786]
I have just been trying to get this to work for an hour and just can't get it to work.. I tried so many things

This is my date-picker (using latest version 2.2.3)

```
        <v-date-picker
          ref="startAt"
          v-model="form.dateIn"
          mode="dateTime"
          :popover="popover"
        >
          <template #default="slotProps">
            <div
              class="tw-flex tw-items-center"
              v-on="slotProps.inputEvents"
            >
              <input
                :value="form.dateIn ? dayjs(form.dateIn).format('YYYY-MM-DD HH:mm') : ''"
                class="tw-w-full tw-px-6 tw-py-3 tw-placeholder-white tw-bg-transparent tw-border-0 tw-outline-none md:tw-text-tiny md:tw-px-2 md:tw-outline-none md:tw-py-2 lg:tw-px-6 lg:tw-outline-none lg:tw-py-3 tw-ring-0"
                type="text"
                :readOnly="true"
                placeholder="Meetup Starts At"
              >
              <div class="tw-flex tw-items-center tw-justify-center tw-h-full tw-px-6">
                <i class="far fa-calendar-alt" />
              </div>
            </div>
          </template>

          <template #footer>
            <div class="tw-p-2 tw-text-center tw-bg-gray-100 tw-border-t tw-rounded-b-lg">
              <button
                class="tw-px-2 tw-py-1 tw-font-medium tw-text-white tw-bg-blue-500 tw-rounded hover:tw-bg-blue-600"
                @click="hideAllCalendars"
              >
                Close
              </button>
            </div>
          </template>
        </v-date-picker>
```

I tried a gazillion things inside `hideAllCalendars` and nothing works :( This should be easy... what am I missing?

**Comment by vesper8** [comment]
Ooof... pretty sure it's not supposed to be this difficult.. but after 2 hours of trial and error I finally found something that works

```
this.$refs.startAt.$children[0].hide()
```

or simply add to the `@click` -> `@click="$refs.startAt.$children[0].hide()"`

I think there should be an option added to add some kind of close button when using the `dateTime` mode because it's quite unintuitive currently that the calendar does not close on its own at any point.. there is no X to close it and the only way to close it when in `dateTime` mode is to basically click outside which is bad design IMO

I would also like to mention that the example mentioned here https://vcalendar.io/changelog/v2.0.html#_2-use-footer-scoped-slot does not work at all for me on `2.2.3` when added to a button inside the footer slot of `v-date-picker`. I realize the example in this link is for `v-calendar` but I figured it should also work on `v-date-picker`

**Comment by nathanreyes** [comment]
I put a modified version of your example [here](https://github.com/nathanreyes/v-calendar/blob/master/docs/.vuepress/components/github/786.vue).

You can see it in action [here](https://vcalendar.io/github/).

v2.2.0 added support for the `footer` slot in datepicker. Normally you'd be able to get the `hidePopover` function in the `slotProps`, but because you want to call it from the footer slot...it falls outside the scope of the default template.

You could probably find a hacky way of calling it, but in this case you can just call the `hidePopover` function on the date picker itself.

Also notice that I used the `inputDateTime` mask so you don't have to do your own formatting.

**Comment by nathanreyes** [comment]
```html
<template>
  <v-date-picker
    ref="startAt"
    v-model="date"
    mode="dateTime"
    :popover="popover"
    :masks="masks"
  >
    <template #default="{ inputValue, inputEvents }">
      <div class="flex items-center" v-on="inputEvents">
        <input
          :value="inputValue"
          class="w-full px-6 py-3 placeholder-white bg-transparent border-0 outline-none md:text-tiny md:px-2 md:outline-none md:py-2 lg:px-6 lg:outline-none lg:py-3 ring-0"
          type="text"
          :readOnly="true"
          placeholder="Meetup Starts At"
        />
        <div class="flex items-center justify-center h-full px-6">
          <i class="far fa-calendar-alt" />
        </div>
      </div>
    </template>

    <template #footer>
      <div class="p-2 text-center bg-gray-100 border-t rounded-b-lg">
        <button
          class="px-2 py-1 font-medium text-white bg-blue-500 rounded hover:bg-blue-600"
          @click="hideAllCalendars"
        >
          Close
        </button>
      </div>
    </template>
  </v-date-picker>
</template>
```
```js
<script>
export default {
  data() {
    return {
      date: new Date(),
      popover: {},
      masks: {
        inputDateTime: 'YYYY-MM-DD HH:mm',
      },
    };
  },
  methods: {
    hideAllCalendars() {
      this.$refs.startAt.hidePopover();
    },
  },
};
</script>
```

**Comment by vesper8** [comment]
@nathanreyes thank you for the reply and the example. I guess all I needed was `hidePopover()`. Please document this method so the next guy doesn't lose as much time as I did...
