### ISSUE TITLE
Date picker double paned exceeding the browser right edge

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#79]
Look this behavior @nathanreyes:

![bug](https://user-images.githubusercontent.com/11582056/36804516-96578042-1c99-11e8-884c-bc6ae9ae787d.jpg)

Is there a way to open it to the left in this case?

**Comment by nathanreyes** [comment]
There is a `popover-align` prop that can be set to `“right”`. Think that should work.

**Comment by luiztsmelo** [comment]
Worked. Thanks!
