### ISSUE TITLE
is-expanded prop doesn't seem to fill the width of the container

### ISSUE THREAD

**Issue by kreierson** [nathanreyes/v-calendar#8]
First off, this is one of the best pickers I've worked with! Thanks a ton! I am having an issue with the is-expanded prop. It doesn't seem to fill the full width of the container.
Below is how I am using it:
```
<div class="col-sm-3" style="background-color: red;">
     <v-date-picker
           mode="range"
           select-color="#5c852c"
           drag-color="#5c852c"
           :is-inline="true"
           @input="getTrips"
           v-model="range"
           :is-expanded="true">
     </v-date-picker>
</div>
```

![screenclip000131](https://user-images.githubusercontent.com/11322709/32908762-c9a50854-cac1-11e7-94b5-d9006aec95dc.jpg)

**Comment by nathanreyes** [comment]
Hope this fixes your issue. Thanks for the contribution.

**Comment by kreierson** [comment]
Wow, thanks for the quick response. I pulled in the most recent commit and it still doesn't seem to work. However when I apply the is-expanded class manually in chrome dev-tools it allows the calendar to fill the container.

![screenclip000132](https://user-images.githubusercontent.com/11322709/32913486-adc2feee-cacf-11e7-9e12-20e8da7a58c0.jpg)

**Comment by nathanreyes** [comment]
You are correct. I found a different bug fixed with the calendar with the earlier commit, but your issue was specific to inline date pickers, which I just now discovered. Hopefully, the next revision will fix this once and for all.
