### ISSUE TITLE
Suggestion: using just two arrows in case of double-paned 

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#80]
I think changing the month of each panel separately is a bit strange in case of double-paned. When you change a month, you usually want the other month to follow this change. What do you think about it @nathanreyes?

**Comment by nathanreyes** [comment]
Not sure about making it the default behavior, but it would not be hard to introduce a `sync-panes` prop to do that. I would be curious to see if by default more devs would want them to be synchronized or not. If more would like them to be synchronized, then that could be the default and there could be a `separate-panes` prop or something like that to revert to the old way.

**Comment by luiztsmelo** [comment]
Yeah, would be nice if github had a questionnaire. How come they didn't think about it before? Anyways, I think separate panes would only be needed if the user wants to compare distant months, which is not the case most of the time. When not the case, this only complicates the user experience. When in doubt, simplify. But it's just my opinion. A `sync-panes` prop would be great too.

**Comment by ggirodda** [comment]
Hi,
I put in a forked repo this property:
:monthInterval
you can specify the number of month between the first and the second pane. If you put 1, the months will always be consecutive.
Maybe this can do the job. I added other things too, but not they're not necessarily useful for every one, you can pick what you want.
https://github.com/ggirodda/v-calendar

**Comment by nathanreyes** [comment]
@ggirodda Yes I must have missed that specific part. I just noticed the rate and rate style additions. I will definitely take a look. I'm curious thought, would there really be a need to any interval other than 1 or none? Would someone want some other value?

**Comment by nathanreyes** [comment]
Not sure what would look best when `sync-panes` is true.

## Hidden
<img width="529" alt="screenshot 2018-03-21 15 40 23" src="https://user-images.githubusercontent.com/2107487/37736226-5e2f002e-2d1e-11e8-99b1-e68ca01c21a7.png">

## Disabled
<img width="526" alt="screenshot 2018-03-21 15 44 07" src="https://user-images.githubusercontent.com/2107487/37736402-d073c7aa-2d1e-11e8-8617-c8b73008c889.png">

**Comment by luiztsmelo** [comment]
Hidden is better. But we need to get rid of the vertical divider for better looking, like this:

![calendar](https://user-images.githubusercontent.com/11582056/37743202-bddf5c20-2d47-11e8-8b2c-f99ee1b956ca.jpg)

**Comment by Alendorff** [comment]
Hidden is better, but dividers still could be customized. I don't think they should be removed by default.

**Comment by nathanreyes** [comment]
The arrows will be hidden, except when in vertical orientation (which is also coming in next revision). Also, the dividers will still appear by default, but can also be easily hidden via `themeStyles`.
