### ISSUE TITLE
When will v-calendar support Vue 3?

### ISSUE THREAD

**Issue by deporter** [nathanreyes/v-calendar#804]
I'm hoping to use v-calendar with Vue 3 in a new project, is there a rough timeline for when this will be available?

P.S. Thanks so much for building such a great date picker library.

**Comment by nathanreyes** [comment]
@deporter Please reference this page for latest info on Vue 3 support. There are still planned breaking changes, so that is why it is currently in alpha stage. Otherwise it is pretty stable.

https://vcalendar.io/vue-3.html
