### ISSUE TITLE
Light calendar with light popover

### ISSUE THREAD

**Issue by mrleblanc101** [nathanreyes/v-calendar#808]
Hi,
Would it be possible to have a light calendar with a light popover.
Currently this does not seem to be possible without manually overriding all the CSS.
<img width="294" alt="Capture d’écran, le 2021-03-05 à 10 57 46" src="https://user-images.githubusercontent.com/17392251/110140008-a49ea880-7da1-11eb-8e68-9e1706108078.png">

**Comment by nathanreyes** [comment]
Currently this isn't possible without doing the manual overrides as you mentioned. Perhaps a `navIsDark` prop could default to the current behavior but allow for manually overriding this.

**Comment by mrleblanc101** [comment]
Seems like a weird default, maybe light theme should have a light popover as default and dark as an option.
Here is what I was able to do.
![2021-03-14 14 51 42](https://user-images.githubusercontent.com/17392251/111080457-f3042380-84d4-11eb-95e7-a771a120bfb3.gif)

**Comment by mrleblanc101** [comment]
I tihnk this is now the default, closing
