### ISSUE TITLE
Hover style for dot

### ISSUE THREAD

**Issue by radian20** [nathanreyes/v-calendar#81]
Hello,  How to style the hovered dots?
Now the situation is this
![image](https://user-images.githubusercontent.com/26577173/36834207-535e8f6a-1d5c-11e8-8617-61d47b0f1e99.png)
![image](https://user-images.githubusercontent.com/26577173/36834253-81328f72-1d5c-11e8-8a10-903261c925e7.png)
but I want to do it like this, when hover
![image](https://user-images.githubusercontent.com/26577173/36834389-fc417994-1d5c-11e8-8fd1-898ce54d0cd9.png)
Sorry for bad english.
Thanks a lot

**Comment by nathanreyes** [comment]
Currently there is no support for configuring dots based on the hovered state. However, I do plan to implement such a feature. For now, you may try hacking away using the [day mouse events](https://docs.vcalendar.io/api.html#calendar-events) to modify your attributes when needed.

**Comment by nathanreyes** [comment]
You can now use functions to configure attribute sub-types.

For example,

```html
<v-calendar :attributes='attributes'>
</v-calendar>
```
```javascript
export default {
  data() {
    return {
      attributes: [
        dot({ isHovered}) {
          return {
            backgroundColor: isHovered ? 'pink' : 'white'
          }
        },
        dates: new Date()
      ]
    }
  }
}
```

**Comment by radian20** [comment]
Thanks a lot!
