### ISSUE TITLE
Vue3 (alpha): Import of DatePicker impossible

### ISSUE THREAD

**Issue by JarodXP** [nathanreyes/v-calendar#827]
In the root index.d.ts, DatePicker is not exported.
It leads to impossibility to use the components locally.

**Comment by danielhgasparin** [comment]
Ideally, the package needs type definitions for TypeScript, not only to be possible to import de package, but to have autocomplete and validations functions possible too.

Will be grateful if this can be implemented.

**Comment by Sadeghbayan** [comment]
+1

**Comment by dakt** [comment]
Wow, this is still not fixed?

**Comment by aguidis** [comment]
Thanks to this [answer](https://stackoverflow.com/questions/49152667/in-typescript-how-do-i-overried-index-d-ts-provided-with-a-3rd-party-lib-with-m?answertab=active#tab-top), I managed to add the missing export:

- create a new `index.d.ts` in your project (in my case I created it in this folder `src/types/dependencies/v-calendar/index.d.ts`

- update your tsconfig.json:
```
        "paths": {
            "@/*": [
                "src/*"
            ],
            "v-calendar": ["src/types/dependencies/v-calendar/index.d.ts"]
        },
```
