### ISSUE TITLE
Date picker slot usage in v-calendar@0.7.x stopped working

### ISSUE THREAD

**Issue by karol-f** [nathanreyes/v-calendar#83]
Date picker slot usage in v-calendar@0.7.x stoped working. 

* tried https://docs.vcalendar.io/datepicker.html#using-custom-slot in @0.7.2 and it didn't work - slot was ignored.
* tried above with @0.6.3 and it worked

Desired behaviour - datepicker scoped slot (e.g. for custom input) should work.

* Example that is NOT WORKING - https://codesandbox.io/s/50oryv567k
* The same example (WORKING) with only changed version to @0.6.3 - https://codesandbox.io/s/5003yw5pnn

Regards.

**Comment by nathanreyes** [comment]
Thanks for the catch. Will issue in a hotfix later today.

**Comment by karol-f** [comment]
Fantastic. Please release fixed version. Regards!

**Comment by nathanreyes** [comment]
Should be available now.

**Comment by karol-f** [comment]
Thank you, confirming that it's working.

**Comment by nathanreyes** [comment]
Please update to `v0.7.4` to address issue introduced by `v0.7.3`.
