### ISSUE TITLE
V-calendar size

### ISSUE THREAD

**Issue by jctiru** [nathanreyes/v-calendar#84]
How can I make the v-calendar into custom size? Or maybe respect the container to auto-resize? As you can see in my screenshot, it overflows in the container:

![image](https://user-images.githubusercontent.com/34016067/36901976-f441fd88-1e63-11e8-989d-7d6866a91981.png)

I'm using Bootstrap 4 to align my items and it clearly overflows. The only workaround I think is I must re-design the whole layout to accommodate the calendar although that doesn't sound elegant.

By the way, thanks for the great component!

**Comment by nathanreyes** [comment]
This section of the [docs](https://docs.vcalendar.io/layout.html#horizontal-layout) might help you. You can size it manually via `pane-width` or set `is-expanded` in order to expand to the width of its container.

**Comment by jctiru** [comment]
Hmmm maybe I should have read the docs first, sorry about that. Although I don't think it will still solve my problem because there is a set minimum width of 256px just like what the docs says. I guess I will just have to make do. Thanks for the fast reply!

**Comment by nathanreyes** [comment]
Not a problem. In your case, I might recommend reflowing the layout when the width becomes constrained (or showing the date picker as a popover by switching the `is-inline` prop). I think a calendar that narrow might cause problems for the users, though I'm now sure how narrow you would like to go.

**Comment by zachheine** [comment]
@nathanreyes Is there any thought to make a minimum width less than 256px? It seems like it could still be usable at smaller sizes.

**Comment by andrewizmaylov** [comment]
i found my solution by manualy changing this size in sourse code 
from `columnWidth: 'minmax(256px, 1fr)' `
to `columnWidth: 'minmax(180px, 1fr)',`
