### ISSUE TITLE
console.log

### ISSUE THREAD

**Issue by besil** [nathanreyes/v-calendar#85]
Hi,

It seems last built introduced a console.log.
Could it be switched off?
![image](https://user-images.githubusercontent.com/7081486/36909020-364b94fe-1e3d-11e8-98a0-fc55b5d18da7.png)

**Comment by nathanreyes** [comment]
Yes unfortunately it made it into the last patch. Today has been a looong morning already :).

It will have get fixed with some other changes coming down the pipe.
