### ISSUE TITLE
[VUE 3] BUG when use Vue 3 and Vue Router 4

### ISSUE THREAD

**Issue by Svarogbog** [nathanreyes/v-calendar#857]
Hi!
I use v-calendar 3.0.0-alpha.3 version, vue router 4 in my vue 3 project.
And in project use v-calendar ( Calendar )  as components to main page.  
When i create `<router-link to="/"></router-link>`  is displayed an error:

![зображення](https://user-images.githubusercontent.com/32750213/115718564-e6040b00-a383-11eb-90bd-a0d0781d61e9.png)

![зображення](https://user-images.githubusercontent.com/32750213/115718160-8b6aaf00-a383-11eb-8933-b0d86edc4608.png)

**Comment by saudsayed** [comment]
@Svarogbog I am facing the same issue

**Comment by Svarogbog** [comment]
https://github.com/nathanreyes/v-calendar/issues/914
