### ISSUE TITLE
initial value

### ISSUE THREAD

**Issue by rebotak** [nathanreyes/v-calendar#86]
how can I set the initial value for the calendar?

**Comment by nathanreyes** [comment]
Are you referring to trying to set an initial date value for `v-date-picker`? If so, just bind the value using `v-model` to your own state variable and assign that state variable whenever you would like to (on `created()` or `mounted()` lifecycle method, for example.

There is no concept of an initial value for `v-calendar` itself. It just woks with attributes.

If you are referring to the inital displayed month, you can use `from-page` prop for that.

[Docs reference](https://docs.vcalendar.io)

**Comment by nathanreyes** [comment]
Closing until further information is provided.

**Comment by gauravmak** [comment]
Note for myself: Initial value needs to be a Date object instead of a string for this to work.
