### ISSUE TITLE
[Vue 3] Can't get v-calendar to work in Vue 3

### ISSUE THREAD

**Issue by m4heshd** [nathanreyes/v-calendar#860]
Trying to use this component in Vue 3 but ends up with a lot of errors.
Versions: 
```js
{
   "v-calendar": "3.0.0-alpha.3",
   "vue": "^3.0.0"
}
```

Here's the error:

![image](https://user-images.githubusercontent.com/6711514/115977153-ed4d3380-a592-11eb-8ada-faf0baa2e16d.png)

Strangely, whenever I import this globally and not even use as a component, my already existing (error free) components starts throwing errors.

![image](https://user-images.githubusercontent.com/6711514/115977224-93993900-a593-11eb-8c2a-ebfdc1fc95cc.png)

None of these errors pop up if I get rid of v-calendar. It's so strange. Could be a build issue in the latest release?

**Comment by Helcostr** [comment]
I got v-calendar working with 3.0.11

This is probably what happens when u work with alpha stuff.

![image](https://user-images.githubusercontent.com/15018549/116021376-efe47300-a5fc-11eb-9ef0-4980f2116f7e.png)

**Comment by m4heshd** [comment]
@Helcostr Thank you for the response. But I ended up writing my own date picker. Much more flexibility for me. Even though the update is a minor version, updating a major dependency for me at the moment is a little too expensive since I'm working on a massive project.
