### ISSUE TITLE
I get warnings in console when using v-model

### ISSUE THREAD

**Issue by SudoGetBeer** [nathanreyes/v-calendar#87]
First of all thanks for this cool package.

I have a small issue. 

`
                            <v-date-picker
                                mode='range'
                                v-model='where.datesObjects'
                                :is-inline="true"
                            >
                            </v-date-picker>
`

This is my implementation.
Everthing works fine, but I get these three warnings everytime I change the value:
![screenshot 2018-03-07 09 57 23](https://user-images.githubusercontent.com/7324694/37082843-f1d4ce94-21ed-11e8-891f-08ee86c4c121.png)

I'm fairly new to Vue so I don't know if this a real problem.

**Comment by nathanreyes** [comment]
Can you post the code for your Vue instance (`export default` section if using single file component).

**Comment by nathanreyes** [comment]
Going to close this issue until further info provided. This is the first notice of this kind of issue, so I think it is probably associated with the using `v-model` with a nested property.
