### ISSUE TITLE
ISO device dot issue

### ISSUE THREAD

**Issue by alamindev** [nathanreyes/v-calendar#872]
Other devices are ok like this

![Screenshot_11](https://user-images.githubusercontent.com/35292883/117100241-1345b580-ad95-11eb-9678-92daa1bcb860.png)

ISO device showing this type of dots.

![Screenshot_10](https://user-images.githubusercontent.com/35292883/117100243-1476e280-ad95-11eb-968e-cef07eada0a7.png)

![Screenshot_12](https://user-images.githubusercontent.com/35292883/117100677-286f1400-ad96-11eb-9886-5c24ccc96538.png)

![Screenshot_14](https://user-images.githubusercontent.com/35292883/117100688-302eb880-ad96-11eb-8fc7-6daff70a4761.png)

![Screenshot_15](https://user-images.githubusercontent.com/35292883/117100683-2e64f500-ad96-11eb-94f6-14b45e591435.png)

![Screenshot_13](https://user-images.githubusercontent.com/35292883/117100690-31f87c00-ad96-11eb-9fff-36173cb53812.png)

**Comment by Hatar** [comment]
hi,
try this.

document.querySelectorAll(".vc-dots")
  .forEach( 
      vcdots => 
        vcdots.children.length > 1 &&
        vcdots.children.forEach((vcdot, i) => i != 0 && (vcdot.style.display = "none")
    )
)

**Comment by Hatar** [comment]
after u fill calendar with data.
execute the above code.

**Comment by alamindev** [comment]
is this working if I use this code in mounted life circle hook vuejs?

**Comment by Hatar** [comment]
yup ;)

**Comment by alamindev** [comment]
no luck. still same problem

**Comment by bazuka5801** [comment]
@alamindev V-Calendar devs make a mistake with convert data
I fixed it in #870 #871 
Try use ISO date (String)
like
dates: ["2014-03-01"]
And all woking good!
