### ISSUE TITLE
Opening date picker programmatically

### ISSUE THREAD

**Issue by luiztsmelo** [nathanreyes/v-calendar#88]
I need to open the date picker by clicking a button, conditionally. I've tried to use the [$refs ](https://jsfiddle.net/f706L1tk/)method, but it didn't work. Could an identifier be implemented, or something else to handle this case?

I need to do something like this:
https://www.airbnb.com/rooms/735683?s=0kE5IldB
Look at the booking box. When you click on the Check Availability button and the dates are null, it opens the date picker.

**Comment by nathanreyes** [comment]
For `v-date-picker`, set the `popover-visibility` initially to `"focus"`. Then, in your Check Availability click handler, do two things:
1. Set `popover-visibility` to `"visible"` to force the popover open.
2. On next tick (`this.$nextTick`) set `popover-visibility` back to `"focus"`

See if that works.

**Comment by luiztsmelo** [comment]
Didn't work. When `popover-visibility` back to `"focus"`, it closes the `v-date-picker`.

**Comment by nathanreyes** [comment]
I think you can use the `$refs` technique.
1. Set a ref on `v-date-picker`
```html
<button @click='showPicker'>Show Picker</button>
<v-date-picker
  ref='picker'>
</v-date-picker>
```
2. On button click, set focus on the ref component element on next tick
```javascript
methods: {
  showPicker() {
    this.$nextTick(() => this.$refs.picker.$el.focus());
  }
}
```

**Comment by luiztsmelo** [comment]
Now it worked! Thanks.

**Comment by zlajaa1** [comment]
`this.$nextTick(() => this.$refs.picker.popoverVisibility = 'visible')`

If you want to fire it on input focus, this should be a way? Works for me.

**Comment by A1rPun** [comment]
Why is this issue closed? Because it resolved a particular case with a workaround?
I'm currently having this issue and it's not easily fixable with above workarounds because I'm using custom slots.

My Component's HTML:
```html
<b-input-group>
  <b-input-group-prepend @click="focusInput">Click here</b-input-group-prepend>
  <v-date-picker
    mode="single"
    :value="selectedValue"
    @input="setValue"
  >
    <b-form-input
      type="text"
      slot-scope="{ inputValue, updateValue }"
      :value="inputValue"
      @input="updateValue($event, { formatInput: false, hidePopover: false })"
      @change="updateValue($event, { formatInput: true, hidePopover: false })"
    >
    </b-form-input>
  </v-date-picker>
</b-input-group>
```

Focussing the native element is easy, opening the popover isn't.

**Comment by Dagaflux** [comment]
The solution presented here do not work. Is it possible to reopen the issue please?

**Comment by obaidsamadian** [comment]
> The solution presented here does not work. Is it possible to reopen the issue please?
This should work
` showPicker() {
      this.$nextTick(() => this.$refs.picker.$el.querySelector('input'));
    }`

**Comment by AlyZidanDev** [comment]
Also it didn't work for me !

**Comment by floatingbits** [comment]
> This should work
showPicker() { this.$nextTick(() => this.$refs.picker.$el.querySelector('input')); }

I think, there is a ".focus()" missing. Should be: 
`showPicker() { this.$nextTick(() => this.$refs.picker.$el.querySelector('input').focus()); }`

**Comment by voodoocode** [comment]
> `showPicker() { this.$nextTick(() => this.$refs.picker.$el.querySelector('input').focus()); }`

For me this opens the popup for me for a very short moment, but  directly it automatically disappears again.

Happens with both `focus()` event and also with `click()`.

(I'm using `mode="date" is-range` if thats important)

**Comment by lb91** [comment]
@voodoocode you solved your problem, maybe? I have the same problem and I also use the is-range parameter...

**Comment by voodoocode** [comment]
> @voodoocode you solved your problem, maybe? I have the same problem and I also use the is-range parameter...

@lb91 no, sadly not. Maybereopen the issue?

**Comment by NicolaSpadari** [comment]
The focus technique is correct, just trigger the click with `@click.stop=myToggleFn()` and it will stay open

**Comment by SajanaK717** [comment]
Try `this.$refs. picker.$el.querySelector('input').click()`
