### ISSUE TITLE
Bug with Vue 3 and the input

### ISSUE THREAD

**Issue by sienael** [nathanreyes/v-calendar#888]
I think there is a Bug in date format on Vue 3 (next version). I have the following code:

`<v-date-picker v-model="date">
  <template #default="{ inputValue, inputEvents }">
    <input class="px-3 py-1 border rounded" :value="inputValue" v-on="inputEvents" />
  </template>
</v-date-picker>`

the input shows the format 22.03.2020. If i press backspace it deletes the wrong numbers or deletes the date. 

Example:
Date is 13.12.2019. Cursor is behind 2019, i press backspace -> date is deleted
Date is 01.01.2020. Cursor is behind the second 01 (month), i press backspace -> date convert to 01.12.2000

Is this a bug or did i make something wrong?

**Comment by peterghu** [comment]
I have a similar issue, can't type anything into the input without the current selected date in the date picker overwriting the input value. I used this setting to fix it: ` :update-on-input="false"`

**Comment by sienael** [comment]
Yes, this worked for me. Thank you very much!

**Comment by nathanreyes** [comment]
This should be patched in `3.0.0-alpha.5`.
