### ISSUE TITLE
2 month calendar 2-high instead of 2-wide

### ISSUE THREAD

**Issue by wimfarasyn** [nathanreyes/v-calendar#89]
Hi,
I’m using vCalendar in an event registration app for a local charity. It’s really a great package, which even for a JS noob has allowed a nice UX!
Current event season is only 2 weeks, so I get by with showing just one month, but in the summer time events will be spread over July & August.
Within the layout of the app, it would be better to get the 2 months showing one below the other opposed to 2 wide.
Any suggestion how I can achieve that?
Thanks again!
Wim

**Comment by EricMcRay** [comment]
I achieve this with simple proxy component. I put gist link below. You display as many calendar as you want. I know this is not a great solution but It works.

https://gist.github.com/EricMcRay/c5418a4d854b2b84be6a2cda5acabdf1

PS: I using vue for just few days so I pretty new about it. Dont judge the bad code :)
