### ISSUE TITLE
[Question] Is $screens compatible with vue3 and vite?

### ISSUE THREAD

**Issue by izaxen** [nathanreyes/v-calendar#893]
I have tried everything and get $screen is not a function.

//Best egards

**Comment by smogHead** [comment]
I'm having the same issue. Usage:

<v-date-picker
					v-model="currentDate"
					color="green"
					:firstDayOfWeek="1"
					show-weeknumbers
					:masks="dateFormats"
					:locale="appApiStore.locale"
					trim-weeks
					:columns="$screens({ default: 1, lg: 2 })"
					:rows="$screens({ default: 1, lg: 2 })"
					:is-expanded="$screens({ default: true, lg: false })"
				>

but I receive the following build error

src/components/pages/calendar/CalendarControl.vue:675:20 - error TS2304: Cannot find name '$screens'.

675      :is-expanded="$screens({ default: true, lg: false })"

Can you help?

**Comment by nathanreyes** [comment]
Are you importing the components as needed in your app?

You may need to still "use" `SetupCalendar` in your Vue app to register the screens plugin.

```js
import { createApp } from 'vue';
import { SetupCalendar } from 'v-calendar';

// Create the app
createApp(App)
  // Setup the plugin with optional defaults
  .use(SetupCalendar, {})
  // Mount the app
  .mount('#app');
```

**Comment by nemanja-ivanis** [comment]
Is there a solution for this? I have tried your example but i am still geting **$screens is not a function** error. I am also using vue3 and vite.

**Comment by chrisb34** [comment]
I'm seeing the same with Vue3 and Inertia.  I initialize the app as follows:

```
import { SetupCalendar, Calendar, DatePicker }  from 'v-calendar';

createInertiaApp({
  resolve: name => require(`./Pages/${name}`),
  title: title => `${title} - MyApp`,
  setup({ el, App, props, plugin }) {
    createApp({ render: () => h(App, props) })
    .use(plugin)
    .use(SetupCalendar,  {})
    .mount(el)
  },
})

```

**Comment by nathanreyes** [comment]
`$screens` is compatible with Vue 3. Here is a simple sandbox example of it being used to show 2 columns on large screens. You need to use `SetupCalendar` as shown in the example.
https://codesandbox.io/s/zen-gagarin-zbyiq?file=/src/main.js
I can't do much else unless an example repo is provided.
