### ISSUE TITLE
Uncaught TypeError: Object(...) is not a function error on Vue 2.6.12

### ISSUE THREAD

**Issue by suyoungpk** [nathanreyes/v-calendar#903]
my situation: ie11 support required.

current version in my project
Vue : 2.6.12 
(Requirement version from my client cuz Vue3.x doesn't support ie11 perfectly) 
v-calendar : 3.0.0-alpha.4
babel-polyfill : 6.26.0

it occurs this error "Module parse failed: Unexpected token (5222:58)" on console
so, I  tried to change the webpack.base.conf as below.
(I read posts related to this error on this issues board )
```
 {
        test: /\.js$/,
        loader: 'babel-loader',
        include: [resolve('src'), resolve('test'), resolve('node_modules/webpack-dev-server/client'), resolve('node_modules/v-calendar')]
      },
```

and then I got this error  "Uncaught TypeError: Object(...) is not a function " on chrome dev tool
and "export 'h' was not found in 'vue'" on console ....(eslint message)

What should i do for it?

**Comment by nathanreyes** [comment]
Version 3 of this plugin is only to be used with Vue 3. You can try version 2, but this plugin does not officially support IE11.
