### ISSUE TITLE
Vue3 Issue: Typing in a datetime field formats it to the wrong date

### ISSUE THREAD

**Issue by Robbe95** [nathanreyes/v-calendar#910]
When the user types something in their locale format, it interprets the date as an "MM-DD-YYYY" format while the date is in "DD-MM-YYYY".
Am I doing something wrong or is this a bug?
Thanks for making this great package!
I've included some screenshots and the code I am using

```
      <DatePicker class="w-full h-full my-auto" v-if="type=='date'" v-model="currentSearch[field]" mode="dateTime" is24hr :update-on-input="false">
        <template v-slot="{ inputValue, inputEvents }">
          <input
            class="w-full h-full my-auto text-xl font-bold rounded focus:outline-none focus:border-blue-300 bg-background"
            :value="inputValue"
            v-on="inputEvents"
            :id="'focus-' + searchId + '-' + field"
          />
        </template>
      </DatePicker>
```

<img src="https://user-images.githubusercontent.com/44748019/120814586-52f7ec80-c54f-11eb-9bbd-29ed3545fb66.png" alt="alt text" height="400px"> <img src="https://user-images.githubusercontent.com/44748019/120814733-7327ab80-c54f-11eb-81f6-5f110bfb56a8.png" alt="alt text" width="400px">

**Comment by illeb** [comment]
@Robbe95 Hi, we are experiencing this exact issue. How did you solve it?
