### ISSUE TITLE
Help the Korean people. Damn IE11 v-calendar layout Issue

### ISSUE THREAD

**Issue by kocat53** [nathanreyes/v-calendar#911]
hi there.. T^T

South Korea has a very high percentage of Internet Explorer.

Some people still use IE10, yes this is very shit

IE11 cannot be abandoned in Korea.

help me........ please.... 

Is there any way?

![image](https://user-images.githubusercontent.com/20110150/120962970-bfffc200-c79b-11eb-955d-582654d86498.png)

I think it can be solved with a prefix. (grid , flex)

but, i don't know how can do that

- Development environment: nuxt js
- calendar Version : 2.3.0
- what do you want : What works out in ie11.

ver Korean
야... 누가좀 도와줘봐라
얘네 지원 안해준다는데... 이건 뭐... 어카냐...
개똥 익스에서 나와야 하는데.. 하..
nuxt 에서 쓰고있음...
그리드 떄문에 안나오는 것 같은데
프리픽스가 안묵네 젠장

**Comment by kocat53** [comment]
내가 해결했다. 

그러나 정답은 알려주지 않겠다..! 메롱이다.

-----------------------------------------------------

I solved it.

But I won't tell you the answer. 😛  (lie..)

**Comment by isaac-gilmour-asknicely** [comment]
@kocat53 i think theres some work still maybe going on over here? 
https://github.com/nathanreyes/v-calendar/issues/452

**Comment by nathanreyes** [comment]
Closing this issue as IE11 is not officially supported.
