### ISSUE TITLE
Range inputs behaviour 

### ISSUE THREAD

**Issue by rafaelgfirmino** [nathanreyes/v-calendar#915]
Hi guys, I can change my poppover to correct dates ?

when i click in start date(01/01/2021)  and end date(12/01/2021) the poppover show the same date for both.

**Comment by bask-digital** [comment]
I think I have the same question.

When using a popover with range/inputs, how can I display the popover with the correctly focused month?

For example, if I have start/end inputs with values of 1/1/22 and 2/1/22 respectively, how can I display the range.end popover displaying February as default?
