### ISSUE TITLE
Year and month picker Vue3

### ISSUE THREAD

**Issue by Dan13le85** [nathanreyes/v-calendar#938]
Hi, this plugin is great, nice and very flexible.
Now, i am asking: can i specify granularity in terms of years and months?.
I want to realize a "month picker" where i can select year and month and not day (it can be 1st as deafault).

Something like this:
![immagine](https://user-images.githubusercontent.com/28354155/125649761-81a2cf81-32c1-4368-bfc1-265dfcd352e1.png)

I did't find anything in the docs

Thank you

**Comment by amantiwari1** [comment]
did you found it?

**Comment by Dan13le85** [comment]
no, i used another plugin

**Comment by amantiwari1** [comment]
which plugin

**Comment by amantiwari1** [comment]
@Dan13le85

**Comment by Dan13le85** [comment]
https://github.com/Vuepic/vue3-date-time-picker

**Comment by 4KDA** [comment]
+1
