### ISSUE TITLE
Is there a way to have minutes in steps for the timepicker

### ISSUE THREAD

**Issue by EamonSkelly** [nathanreyes/v-calendar#954]
Hello,

I was wondering that instead of the minutes in the timepicker increasing by 1 minute at a time, could we defined this, so in increments of 5, 10, 15 etc. Many other datepickers allow this, and I wondered if it wasn't there or was I just missing it in the documents.
Many Thanks
Eamon

**Comment by SansenSekai** [comment]
[:minute-increment](https://vcalendar.io/datepicker.html#date-time)

**Comment by EamonSkelly** [comment]
Thank you very much, I knew it was something I had missed!
