### ISSUE TITLE
Question: Make date clickable in calendar

### ISSUE THREAD

**Issue by gergo2007** [nathanreyes/v-calendar#99]
Hi

I saw the dayclick event, any way to pass some other data then the day?

Thanks!

**Comment by fbove** [comment]
Something like this?

```pug
v-calendar.shadow-1(is-double-paned is-expanded
  :attributes='attributes' :formats='formats' :theme-styles='themeStyles')
  div(slot='event-row' slot-scope='{ customData }')
    q-btn(flat :label='customData.name' dense size='sm'
      @click='goToEvent(customData)' color='primary' no-caps)
```

You could also use `router-link` with `:to` property.

**Comment by gergo2007** [comment]
@fbove That should also work, or when creating the attrs, add the customData there, and in the event called method check for customData.

Found it in the docs after a while.

Thanks!
