### ISSUE TITLE
Time cannot be null

### ISSUE THREAD

**Issue by lindseybradford** [nathanreyes/v-calendar#991]
### Existing behavior
Using [this example template](docs/.vuepress/components/github/772.vue) from the #772, the time component is disabled when the time property is set to null or becomes null after initialization if removed while typing.

### Desired behavior
The time component is functional when initialized with a null value so that a new time can be selected, and remains enabled if the user nullifies the value by removing the time while typing.

### Visuals
![time-null](https://user-images.githubusercontent.com/1048073/136292993-6455f6b3-5683-424c-b09e-aee5eccb3141.gif)

### Related Tickets
- #772 

### Packages
`vue`: `^3.2.18`
`v-calendar`: `^3.0.0-alpha.5`

---

Thank you for building this component and really appreciate any help here!

**Comment by nathanreyes** [comment]
@lindseybradford Sorry..ya the AM/PM toggle is disabled but not the select elements.

Now..it might be desirable to allow for customizing which date components get used when coming out of a null state. I don't know really how to handle that, may like a `fill-date` prop? Hard to know what exactly is the best route there.

**Comment by bahung1221** [comment]
Same issue here,

Added `modelConfig` but still not working:

```
// Template
<DatePicker
      is-inline
      :model-config="modelConfig"
      :minute-increment="15"
      mode="time"
      :model-value="modelValue"
      @update:model-value="val => $emit('update:modelValue', val)"
    >
      <template #default="{ inputValue, inputEvents }">
          ...
      </template>
    </DatePicker>
...
...
// Script
data() {
    return {
      modelConfig: {
        fillDate: {
          year: 1920,
        },
      },
    }
  }
```

![Screen Shot 2022-05-19 at 14 41 11](https://user-images.githubusercontent.com/27690861/169243461-381d71aa-65c4-4fe6-92ce-dac60baec7b2.png)

**Comment by Ronan-bkg** [comment]
Same issue.
I tried to use `fillDate` in the `modelConfig` but it doesn't fix it.

`vue`: `^3.2.25`
`v-calendar`: `^3.0.0-alpha.8`
