### ISSUE TITLE
Is there a way to open popover programmatically ?

### ISSUE THREAD

**Issue by kuza2010** [nathanreyes/v-calendar#999]
How can I open the date popup?

![image](https://user-images.githubusercontent.com/32107577/138687503-29cfbfd6-9ee4-4ccf-941d-cd2f6593421e.png)

**Comment by existe-deja** [comment]
see https://github.com/nathanreyes/v-calendar/issues/1014

**Comment by kuza2010** [comment]
@existe-deja thanks for your workaround
